// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XEQUALIZER_H
#define XEQUALIZER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xequalizer_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Eq_io_BaseAddress;
} XEqualizer_Config;
#endif

typedef struct {
    u32 Eq_io_BaseAddress;
    u32 IsReady;
} XEqualizer;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XEqualizer_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XEqualizer_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XEqualizer_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XEqualizer_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XEqualizer_Initialize(XEqualizer *InstancePtr, u16 DeviceId);
XEqualizer_Config* XEqualizer_LookupConfig(u16 DeviceId);
int XEqualizer_CfgInitialize(XEqualizer *InstancePtr, XEqualizer_Config *ConfigPtr);
#else
int XEqualizer_Initialize(XEqualizer *InstancePtr, const char* InstanceName);
int XEqualizer_Release(XEqualizer *InstancePtr);
#endif

void XEqualizer_Start(XEqualizer *InstancePtr);
u32 XEqualizer_IsDone(XEqualizer *InstancePtr);
u32 XEqualizer_IsIdle(XEqualizer *InstancePtr);
u32 XEqualizer_IsReady(XEqualizer *InstancePtr);
void XEqualizer_EnableAutoRestart(XEqualizer *InstancePtr);
void XEqualizer_DisableAutoRestart(XEqualizer *InstancePtr);

u32 XEqualizer_Get_y(XEqualizer *InstancePtr);
u32 XEqualizer_Get_y_vld(XEqualizer *InstancePtr);
void XEqualizer_Set_x(XEqualizer *InstancePtr, u32 Data);
u32 XEqualizer_Get_x(XEqualizer *InstancePtr);
void XEqualizer_Set_mode(XEqualizer *InstancePtr, u32 Data);
u32 XEqualizer_Get_mode(XEqualizer *InstancePtr);
u32 XEqualizer_Get_coeffs_BaseAddress(XEqualizer *InstancePtr);
u32 XEqualizer_Get_coeffs_HighAddress(XEqualizer *InstancePtr);
u32 XEqualizer_Get_coeffs_TotalBytes(XEqualizer *InstancePtr);
u32 XEqualizer_Get_coeffs_BitWidth(XEqualizer *InstancePtr);
u32 XEqualizer_Get_coeffs_Depth(XEqualizer *InstancePtr);
u32 XEqualizer_Write_coeffs_Words(XEqualizer *InstancePtr, int offset, int *data, int length);
u32 XEqualizer_Read_coeffs_Words(XEqualizer *InstancePtr, int offset, int *data, int length);
u32 XEqualizer_Write_coeffs_Bytes(XEqualizer *InstancePtr, int offset, char *data, int length);
u32 XEqualizer_Read_coeffs_Bytes(XEqualizer *InstancePtr, int offset, char *data, int length);

void XEqualizer_InterruptGlobalEnable(XEqualizer *InstancePtr);
void XEqualizer_InterruptGlobalDisable(XEqualizer *InstancePtr);
void XEqualizer_InterruptEnable(XEqualizer *InstancePtr, u32 Mask);
void XEqualizer_InterruptDisable(XEqualizer *InstancePtr, u32 Mask);
void XEqualizer_InterruptClear(XEqualizer *InstancePtr, u32 Mask);
u32 XEqualizer_InterruptGetEnabled(XEqualizer *InstancePtr);
u32 XEqualizer_InterruptGetStatus(XEqualizer *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
