-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eq is
generic (
    C_S_AXI_EQ_IO_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_EQ_IO_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_eq_io_AWVALID : IN STD_LOGIC;
    s_axi_eq_io_AWREADY : OUT STD_LOGIC;
    s_axi_eq_io_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_ADDR_WIDTH-1 downto 0);
    s_axi_eq_io_WVALID : IN STD_LOGIC;
    s_axi_eq_io_WREADY : OUT STD_LOGIC;
    s_axi_eq_io_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH-1 downto 0);
    s_axi_eq_io_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH/8-1 downto 0);
    s_axi_eq_io_ARVALID : IN STD_LOGIC;
    s_axi_eq_io_ARREADY : OUT STD_LOGIC;
    s_axi_eq_io_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_ADDR_WIDTH-1 downto 0);
    s_axi_eq_io_RVALID : OUT STD_LOGIC;
    s_axi_eq_io_RREADY : IN STD_LOGIC;
    s_axi_eq_io_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH-1 downto 0);
    s_axi_eq_io_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_eq_io_BVALID : OUT STD_LOGIC;
    s_axi_eq_io_BREADY : IN STD_LOGIC;
    s_axi_eq_io_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of eq is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "eq,hls_ip_2017_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.742000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=20,HLS_SYN_FF=8326,HLS_SYN_LUT=2383}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal b0 : STD_LOGIC_VECTOR (31 downto 0);
    signal b1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b2 : STD_LOGIC_VECTOR (31 downto 0);
    signal a1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2 : STD_LOGIC_VECTOR (31 downto 0);
    signal band : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleIn : STD_LOGIC_VECTOR (15 downto 0);
    signal sampleOut_ap_vld : STD_LOGIC;
    signal coeff_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal coeff_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal x1_fix_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal x1_fix_ce0 : STD_LOGIC;
    signal x1_fix_we0 : STD_LOGIC;
    signal x1_fix_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x2_fix_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal x2_fix_ce0 : STD_LOGIC;
    signal x2_fix_we0 : STD_LOGIC;
    signal x2_fix_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal y1_fix_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal y1_fix_ce0 : STD_LOGIC;
    signal y1_fix_we0 : STD_LOGIC;
    signal y1_fix_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal y2_fix_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal y2_fix_ce0 : STD_LOGIC;
    signal y2_fix_we0 : STD_LOGIC;
    signal y2_fix_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_reg_271 : STD_LOGIC_VECTOR (15 downto 0);
    signal i5_reg_283 : STD_LOGIC_VECTOR (5 downto 0);
    signal band_assign_reg_294 : STD_LOGIC_VECTOR (2 downto 0);
    signal sample_assign_reg_305 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal coeff_30_load_reg_1198 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_31_load_reg_1203 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_32_load_reg_1265 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_33_load_reg_1327 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_34_load_reg_1389 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_4_load_reg_1451 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_9_load_reg_1456 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_14_load_reg_1461 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_19_load_reg_1466 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_24_load_reg_1471 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_29_load_reg_1476 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_3_load_reg_1481 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_8_load_reg_1486 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_13_load_reg_1491 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_18_load_reg_1496 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_23_load_reg_1501 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_28_load_reg_1506 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_2_load_reg_1511 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_7_load_reg_1516 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_12_load_reg_1521 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_17_load_reg_1526 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_22_load_reg_1531 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_27_load_reg_1536 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_1_load_reg_1541 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_6_load_reg_1546 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_11_load_reg_1551 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_16_load_reg_1556 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_21_load_reg_1561 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_26_load_reg_1566 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_0_load_reg_1571 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_5_load_reg_1576 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_10_load_reg_1581 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_15_load_reg_1586 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_20_load_reg_1591 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeff_25_load_reg_1596 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_reg_1604 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011001 : BOOLEAN;
    signal ap_reg_pp0_iter1_exitcond_reg_1604 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_fu_713_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_reg_1608 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal sel_tmp4_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_reg_1613 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_reg_1618 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_reg_1623 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel3_fu_785_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel3_reg_1628 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel4_fu_793_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel4_reg_1633 : STD_LOGIC_VECTOR (31 downto 0);
    signal b1_assign_fu_800_p66 : STD_LOGIC_VECTOR (31 downto 0);
    signal b1_assign_reg_1638 : STD_LOGIC_VECTOR (31 downto 0);
    signal b2_assign_fu_870_p66 : STD_LOGIC_VECTOR (31 downto 0);
    signal b2_assign_reg_1643 : STD_LOGIC_VECTOR (31 downto 0);
    signal a1_assign_fu_940_p66 : STD_LOGIC_VECTOR (31 downto 0);
    signal a1_assign_reg_1648 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_assign_fu_1010_p66 : STD_LOGIC_VECTOR (31 downto 0);
    signal a2_assign_reg_1653 : STD_LOGIC_VECTOR (31 downto 0);
    signal x1_fix_addr_reg_1658 : STD_LOGIC_VECTOR (2 downto 0);
    signal x2_fix_addr_reg_1663 : STD_LOGIC_VECTOR (2 downto 0);
    signal y1_fix_addr_reg_1668 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_reg_pp0_iter1_y1_fix_addr_reg_1668 : STD_LOGIC_VECTOR (2 downto 0);
    signal y2_fix_addr_reg_1673 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_fu_1088_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_reg_1678 : STD_LOGIC_VECTOR (5 downto 0);
    signal b0_assign_fu_1103_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal b0_assign_reg_1683 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_flag00011001 : BOOLEAN;
    signal x1_fix_load_reg_1688 : STD_LOGIC_VECTOR (15 downto 0);
    signal x2_fix_load_reg_1693 : STD_LOGIC_VECTOR (15 downto 0);
    signal y1_fix_load_reg_1698 : STD_LOGIC_VECTOR (16 downto 0);
    signal y2_fix_load_reg_1703 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state4_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_flag00011001 : BOOLEAN;
    signal grp_fu_1113_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_reg_1733 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1121_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_i_reg_1738 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1129_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_i_reg_1743 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1137_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_i_reg_1748 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1145_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_i_reg_1753 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_i_reg_1758 : STD_LOGIC_VECTOR (16 downto 0);
    signal input_reg_1763 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_flag00011011 : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage2_flag00011011 : BOOLEAN;
    signal i5_phi_fu_287_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_flag00000000 : BOOLEAN;
    signal band_assign_phi_fu_298_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sample_assign_phi_fu_309_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage2_flag00000000 : BOOLEAN;
    signal tmp_1_reg_316 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_1_i_fu_1080_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_491_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_block_pp0_stage1_flag00000000 : BOOLEAN;
    signal tmp_5_fu_479_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_475_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_483_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sel_tmp1_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_755_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel1_fu_767_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond2_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_773_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond1_fu_1094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_1150_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_i_fu_1154_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_i_fu_1159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_fu_1164_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_flag00011011 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component eq_mux_646_32_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        din65_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (31 downto 0);
        din33 : IN STD_LOGIC_VECTOR (31 downto 0);
        din34 : IN STD_LOGIC_VECTOR (31 downto 0);
        din35 : IN STD_LOGIC_VECTOR (31 downto 0);
        din36 : IN STD_LOGIC_VECTOR (31 downto 0);
        din37 : IN STD_LOGIC_VECTOR (31 downto 0);
        din38 : IN STD_LOGIC_VECTOR (31 downto 0);
        din39 : IN STD_LOGIC_VECTOR (31 downto 0);
        din40 : IN STD_LOGIC_VECTOR (31 downto 0);
        din41 : IN STD_LOGIC_VECTOR (31 downto 0);
        din42 : IN STD_LOGIC_VECTOR (31 downto 0);
        din43 : IN STD_LOGIC_VECTOR (31 downto 0);
        din44 : IN STD_LOGIC_VECTOR (31 downto 0);
        din45 : IN STD_LOGIC_VECTOR (31 downto 0);
        din46 : IN STD_LOGIC_VECTOR (31 downto 0);
        din47 : IN STD_LOGIC_VECTOR (31 downto 0);
        din48 : IN STD_LOGIC_VECTOR (31 downto 0);
        din49 : IN STD_LOGIC_VECTOR (31 downto 0);
        din50 : IN STD_LOGIC_VECTOR (31 downto 0);
        din51 : IN STD_LOGIC_VECTOR (31 downto 0);
        din52 : IN STD_LOGIC_VECTOR (31 downto 0);
        din53 : IN STD_LOGIC_VECTOR (31 downto 0);
        din54 : IN STD_LOGIC_VECTOR (31 downto 0);
        din55 : IN STD_LOGIC_VECTOR (31 downto 0);
        din56 : IN STD_LOGIC_VECTOR (31 downto 0);
        din57 : IN STD_LOGIC_VECTOR (31 downto 0);
        din58 : IN STD_LOGIC_VECTOR (31 downto 0);
        din59 : IN STD_LOGIC_VECTOR (31 downto 0);
        din60 : IN STD_LOGIC_VECTOR (31 downto 0);
        din61 : IN STD_LOGIC_VECTOR (31 downto 0);
        din62 : IN STD_LOGIC_VECTOR (31 downto 0);
        din63 : IN STD_LOGIC_VECTOR (31 downto 0);
        din64 : IN STD_LOGIC_VECTOR (31 downto 0);
        din65 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component eq_mul_32s_16s_32_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component eq_mul_16s_32s_32_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component eq_mul_17s_32s_32_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component eq_x1_fix IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component eq_y1_fix IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (16 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component eq_eq_io_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        b0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        b1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        b2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        a1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        a2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        band : OUT STD_LOGIC_VECTOR (15 downto 0);
        sampleIn : OUT STD_LOGIC_VECTOR (15 downto 0);
        sampleOut : IN STD_LOGIC_VECTOR (15 downto 0);
        sampleOut_ap_vld : IN STD_LOGIC );
    end component;



begin
    x1_fix_U : component eq_x1_fix
    generic map (
        DataWidth => 16,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x1_fix_address0,
        ce0 => x1_fix_ce0,
        we0 => x1_fix_we0,
        d0 => sample_assign_phi_fu_309_p4,
        q0 => x1_fix_q0);

    x2_fix_U : component eq_x1_fix
    generic map (
        DataWidth => 16,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x2_fix_address0,
        ce0 => x2_fix_ce0,
        we0 => x2_fix_we0,
        d0 => x1_fix_q0,
        q0 => x2_fix_q0);

    y1_fix_U : component eq_y1_fix
    generic map (
        DataWidth => 17,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => y1_fix_address0,
        ce0 => y1_fix_ce0,
        we0 => y1_fix_we0,
        d0 => tmp_10_i_reg_1758,
        q0 => y1_fix_q0);

    y2_fix_U : component eq_y1_fix
    generic map (
        DataWidth => 17,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => y2_fix_address0,
        ce0 => y2_fix_ce0,
        we0 => y2_fix_we0,
        d0 => y1_fix_q0,
        q0 => y2_fix_q0);

    eq_eq_io_s_axi_U : component eq_eq_io_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_EQ_IO_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_EQ_IO_DATA_WIDTH)
    port map (
        AWVALID => s_axi_eq_io_AWVALID,
        AWREADY => s_axi_eq_io_AWREADY,
        AWADDR => s_axi_eq_io_AWADDR,
        WVALID => s_axi_eq_io_WVALID,
        WREADY => s_axi_eq_io_WREADY,
        WDATA => s_axi_eq_io_WDATA,
        WSTRB => s_axi_eq_io_WSTRB,
        ARVALID => s_axi_eq_io_ARVALID,
        ARREADY => s_axi_eq_io_ARREADY,
        ARADDR => s_axi_eq_io_ARADDR,
        RVALID => s_axi_eq_io_RVALID,
        RREADY => s_axi_eq_io_RREADY,
        RDATA => s_axi_eq_io_RDATA,
        RRESP => s_axi_eq_io_RRESP,
        BVALID => s_axi_eq_io_BVALID,
        BREADY => s_axi_eq_io_BREADY,
        BRESP => s_axi_eq_io_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        b0 => b0,
        b1 => b1,
        b2 => b2,
        a1 => a1,
        a2 => a2,
        band => band,
        sampleIn => sampleIn,
        sampleOut => tmp_1_reg_316,
        sampleOut_ap_vld => sampleOut_ap_vld);

    eq_mux_646_32_1_U0 : component eq_mux_646_32_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 32,
        din33_WIDTH => 32,
        din34_WIDTH => 32,
        din35_WIDTH => 32,
        din36_WIDTH => 32,
        din37_WIDTH => 32,
        din38_WIDTH => 32,
        din39_WIDTH => 32,
        din40_WIDTH => 32,
        din41_WIDTH => 32,
        din42_WIDTH => 32,
        din43_WIDTH => 32,
        din44_WIDTH => 32,
        din45_WIDTH => 32,
        din46_WIDTH => 32,
        din47_WIDTH => 32,
        din48_WIDTH => 32,
        din49_WIDTH => 32,
        din50_WIDTH => 32,
        din51_WIDTH => 32,
        din52_WIDTH => 32,
        din53_WIDTH => 32,
        din54_WIDTH => 32,
        din55_WIDTH => 32,
        din56_WIDTH => 32,
        din57_WIDTH => 32,
        din58_WIDTH => 32,
        din59_WIDTH => 32,
        din60_WIDTH => 32,
        din61_WIDTH => 32,
        din62_WIDTH => 32,
        din63_WIDTH => 32,
        din64_WIDTH => 32,
        din65_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din1 => coeff_1_load_reg_1541,
        din2 => coeff_31_load_reg_1203,
        din3 => coeff_31_load_reg_1203,
        din4 => coeff_31_load_reg_1203,
        din5 => coeff_31_load_reg_1203,
        din6 => coeff_6_load_reg_1546,
        din7 => coeff_31_load_reg_1203,
        din8 => coeff_31_load_reg_1203,
        din9 => coeff_31_load_reg_1203,
        din10 => coeff_31_load_reg_1203,
        din11 => coeff_11_load_reg_1551,
        din12 => coeff_31_load_reg_1203,
        din13 => coeff_31_load_reg_1203,
        din14 => coeff_31_load_reg_1203,
        din15 => coeff_31_load_reg_1203,
        din16 => coeff_16_load_reg_1556,
        din17 => coeff_31_load_reg_1203,
        din18 => coeff_31_load_reg_1203,
        din19 => coeff_31_load_reg_1203,
        din20 => coeff_31_load_reg_1203,
        din21 => coeff_21_load_reg_1561,
        din22 => coeff_31_load_reg_1203,
        din23 => coeff_31_load_reg_1203,
        din24 => coeff_31_load_reg_1203,
        din25 => coeff_31_load_reg_1203,
        din26 => coeff_26_load_reg_1566,
        din27 => coeff_31_load_reg_1203,
        din28 => coeff_31_load_reg_1203,
        din29 => coeff_31_load_reg_1203,
        din30 => coeff_31_load_reg_1203,
        din31 => coeff_31_load_reg_1203,
        din32 => coeff_31_load_reg_1203,
        din33 => coeff_31_load_reg_1203,
        din34 => coeff_31_load_reg_1203,
        din35 => coeff_31_load_reg_1203,
        din36 => coeff_31_load_reg_1203,
        din37 => coeff_31_load_reg_1203,
        din38 => coeff_31_load_reg_1203,
        din39 => coeff_31_load_reg_1203,
        din40 => coeff_31_load_reg_1203,
        din41 => coeff_31_load_reg_1203,
        din42 => coeff_31_load_reg_1203,
        din43 => coeff_31_load_reg_1203,
        din44 => coeff_31_load_reg_1203,
        din45 => coeff_31_load_reg_1203,
        din46 => coeff_31_load_reg_1203,
        din47 => coeff_31_load_reg_1203,
        din48 => coeff_31_load_reg_1203,
        din49 => coeff_31_load_reg_1203,
        din50 => coeff_31_load_reg_1203,
        din51 => coeff_31_load_reg_1203,
        din52 => coeff_31_load_reg_1203,
        din53 => coeff_31_load_reg_1203,
        din54 => coeff_31_load_reg_1203,
        din55 => coeff_31_load_reg_1203,
        din56 => coeff_31_load_reg_1203,
        din57 => coeff_31_load_reg_1203,
        din58 => coeff_31_load_reg_1203,
        din59 => coeff_31_load_reg_1203,
        din60 => coeff_31_load_reg_1203,
        din61 => coeff_31_load_reg_1203,
        din62 => coeff_31_load_reg_1203,
        din63 => coeff_31_load_reg_1203,
        din64 => coeff_31_load_reg_1203,
        din65 => i5_phi_fu_287_p4,
        dout => b1_assign_fu_800_p66);

    eq_mux_646_32_1_U1 : component eq_mux_646_32_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 32,
        din33_WIDTH => 32,
        din34_WIDTH => 32,
        din35_WIDTH => 32,
        din36_WIDTH => 32,
        din37_WIDTH => 32,
        din38_WIDTH => 32,
        din39_WIDTH => 32,
        din40_WIDTH => 32,
        din41_WIDTH => 32,
        din42_WIDTH => 32,
        din43_WIDTH => 32,
        din44_WIDTH => 32,
        din45_WIDTH => 32,
        din46_WIDTH => 32,
        din47_WIDTH => 32,
        din48_WIDTH => 32,
        din49_WIDTH => 32,
        din50_WIDTH => 32,
        din51_WIDTH => 32,
        din52_WIDTH => 32,
        din53_WIDTH => 32,
        din54_WIDTH => 32,
        din55_WIDTH => 32,
        din56_WIDTH => 32,
        din57_WIDTH => 32,
        din58_WIDTH => 32,
        din59_WIDTH => 32,
        din60_WIDTH => 32,
        din61_WIDTH => 32,
        din62_WIDTH => 32,
        din63_WIDTH => 32,
        din64_WIDTH => 32,
        din65_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din1 => coeff_2_load_reg_1511,
        din2 => coeff_32_load_reg_1265,
        din3 => coeff_32_load_reg_1265,
        din4 => coeff_32_load_reg_1265,
        din5 => coeff_32_load_reg_1265,
        din6 => coeff_7_load_reg_1516,
        din7 => coeff_32_load_reg_1265,
        din8 => coeff_32_load_reg_1265,
        din9 => coeff_32_load_reg_1265,
        din10 => coeff_32_load_reg_1265,
        din11 => coeff_12_load_reg_1521,
        din12 => coeff_32_load_reg_1265,
        din13 => coeff_32_load_reg_1265,
        din14 => coeff_32_load_reg_1265,
        din15 => coeff_32_load_reg_1265,
        din16 => coeff_17_load_reg_1526,
        din17 => coeff_32_load_reg_1265,
        din18 => coeff_32_load_reg_1265,
        din19 => coeff_32_load_reg_1265,
        din20 => coeff_32_load_reg_1265,
        din21 => coeff_22_load_reg_1531,
        din22 => coeff_32_load_reg_1265,
        din23 => coeff_32_load_reg_1265,
        din24 => coeff_32_load_reg_1265,
        din25 => coeff_32_load_reg_1265,
        din26 => coeff_27_load_reg_1536,
        din27 => coeff_32_load_reg_1265,
        din28 => coeff_32_load_reg_1265,
        din29 => coeff_32_load_reg_1265,
        din30 => coeff_32_load_reg_1265,
        din31 => coeff_32_load_reg_1265,
        din32 => coeff_32_load_reg_1265,
        din33 => coeff_32_load_reg_1265,
        din34 => coeff_32_load_reg_1265,
        din35 => coeff_32_load_reg_1265,
        din36 => coeff_32_load_reg_1265,
        din37 => coeff_32_load_reg_1265,
        din38 => coeff_32_load_reg_1265,
        din39 => coeff_32_load_reg_1265,
        din40 => coeff_32_load_reg_1265,
        din41 => coeff_32_load_reg_1265,
        din42 => coeff_32_load_reg_1265,
        din43 => coeff_32_load_reg_1265,
        din44 => coeff_32_load_reg_1265,
        din45 => coeff_32_load_reg_1265,
        din46 => coeff_32_load_reg_1265,
        din47 => coeff_32_load_reg_1265,
        din48 => coeff_32_load_reg_1265,
        din49 => coeff_32_load_reg_1265,
        din50 => coeff_32_load_reg_1265,
        din51 => coeff_32_load_reg_1265,
        din52 => coeff_32_load_reg_1265,
        din53 => coeff_32_load_reg_1265,
        din54 => coeff_32_load_reg_1265,
        din55 => coeff_32_load_reg_1265,
        din56 => coeff_32_load_reg_1265,
        din57 => coeff_32_load_reg_1265,
        din58 => coeff_32_load_reg_1265,
        din59 => coeff_32_load_reg_1265,
        din60 => coeff_32_load_reg_1265,
        din61 => coeff_32_load_reg_1265,
        din62 => coeff_32_load_reg_1265,
        din63 => coeff_32_load_reg_1265,
        din64 => coeff_32_load_reg_1265,
        din65 => i5_phi_fu_287_p4,
        dout => b2_assign_fu_870_p66);

    eq_mux_646_32_1_U2 : component eq_mux_646_32_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 32,
        din33_WIDTH => 32,
        din34_WIDTH => 32,
        din35_WIDTH => 32,
        din36_WIDTH => 32,
        din37_WIDTH => 32,
        din38_WIDTH => 32,
        din39_WIDTH => 32,
        din40_WIDTH => 32,
        din41_WIDTH => 32,
        din42_WIDTH => 32,
        din43_WIDTH => 32,
        din44_WIDTH => 32,
        din45_WIDTH => 32,
        din46_WIDTH => 32,
        din47_WIDTH => 32,
        din48_WIDTH => 32,
        din49_WIDTH => 32,
        din50_WIDTH => 32,
        din51_WIDTH => 32,
        din52_WIDTH => 32,
        din53_WIDTH => 32,
        din54_WIDTH => 32,
        din55_WIDTH => 32,
        din56_WIDTH => 32,
        din57_WIDTH => 32,
        din58_WIDTH => 32,
        din59_WIDTH => 32,
        din60_WIDTH => 32,
        din61_WIDTH => 32,
        din62_WIDTH => 32,
        din63_WIDTH => 32,
        din64_WIDTH => 32,
        din65_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din1 => coeff_3_load_reg_1481,
        din2 => coeff_33_load_reg_1327,
        din3 => coeff_33_load_reg_1327,
        din4 => coeff_33_load_reg_1327,
        din5 => coeff_33_load_reg_1327,
        din6 => coeff_8_load_reg_1486,
        din7 => coeff_33_load_reg_1327,
        din8 => coeff_33_load_reg_1327,
        din9 => coeff_33_load_reg_1327,
        din10 => coeff_33_load_reg_1327,
        din11 => coeff_13_load_reg_1491,
        din12 => coeff_33_load_reg_1327,
        din13 => coeff_33_load_reg_1327,
        din14 => coeff_33_load_reg_1327,
        din15 => coeff_33_load_reg_1327,
        din16 => coeff_18_load_reg_1496,
        din17 => coeff_33_load_reg_1327,
        din18 => coeff_33_load_reg_1327,
        din19 => coeff_33_load_reg_1327,
        din20 => coeff_33_load_reg_1327,
        din21 => coeff_23_load_reg_1501,
        din22 => coeff_33_load_reg_1327,
        din23 => coeff_33_load_reg_1327,
        din24 => coeff_33_load_reg_1327,
        din25 => coeff_33_load_reg_1327,
        din26 => coeff_28_load_reg_1506,
        din27 => coeff_33_load_reg_1327,
        din28 => coeff_33_load_reg_1327,
        din29 => coeff_33_load_reg_1327,
        din30 => coeff_33_load_reg_1327,
        din31 => coeff_33_load_reg_1327,
        din32 => coeff_33_load_reg_1327,
        din33 => coeff_33_load_reg_1327,
        din34 => coeff_33_load_reg_1327,
        din35 => coeff_33_load_reg_1327,
        din36 => coeff_33_load_reg_1327,
        din37 => coeff_33_load_reg_1327,
        din38 => coeff_33_load_reg_1327,
        din39 => coeff_33_load_reg_1327,
        din40 => coeff_33_load_reg_1327,
        din41 => coeff_33_load_reg_1327,
        din42 => coeff_33_load_reg_1327,
        din43 => coeff_33_load_reg_1327,
        din44 => coeff_33_load_reg_1327,
        din45 => coeff_33_load_reg_1327,
        din46 => coeff_33_load_reg_1327,
        din47 => coeff_33_load_reg_1327,
        din48 => coeff_33_load_reg_1327,
        din49 => coeff_33_load_reg_1327,
        din50 => coeff_33_load_reg_1327,
        din51 => coeff_33_load_reg_1327,
        din52 => coeff_33_load_reg_1327,
        din53 => coeff_33_load_reg_1327,
        din54 => coeff_33_load_reg_1327,
        din55 => coeff_33_load_reg_1327,
        din56 => coeff_33_load_reg_1327,
        din57 => coeff_33_load_reg_1327,
        din58 => coeff_33_load_reg_1327,
        din59 => coeff_33_load_reg_1327,
        din60 => coeff_33_load_reg_1327,
        din61 => coeff_33_load_reg_1327,
        din62 => coeff_33_load_reg_1327,
        din63 => coeff_33_load_reg_1327,
        din64 => coeff_33_load_reg_1327,
        din65 => i5_phi_fu_287_p4,
        dout => a1_assign_fu_940_p66);

    eq_mux_646_32_1_U3 : component eq_mux_646_32_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 32,
        din33_WIDTH => 32,
        din34_WIDTH => 32,
        din35_WIDTH => 32,
        din36_WIDTH => 32,
        din37_WIDTH => 32,
        din38_WIDTH => 32,
        din39_WIDTH => 32,
        din40_WIDTH => 32,
        din41_WIDTH => 32,
        din42_WIDTH => 32,
        din43_WIDTH => 32,
        din44_WIDTH => 32,
        din45_WIDTH => 32,
        din46_WIDTH => 32,
        din47_WIDTH => 32,
        din48_WIDTH => 32,
        din49_WIDTH => 32,
        din50_WIDTH => 32,
        din51_WIDTH => 32,
        din52_WIDTH => 32,
        din53_WIDTH => 32,
        din54_WIDTH => 32,
        din55_WIDTH => 32,
        din56_WIDTH => 32,
        din57_WIDTH => 32,
        din58_WIDTH => 32,
        din59_WIDTH => 32,
        din60_WIDTH => 32,
        din61_WIDTH => 32,
        din62_WIDTH => 32,
        din63_WIDTH => 32,
        din64_WIDTH => 32,
        din65_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din1 => coeff_4_load_reg_1451,
        din2 => coeff_34_load_reg_1389,
        din3 => coeff_34_load_reg_1389,
        din4 => coeff_34_load_reg_1389,
        din5 => coeff_34_load_reg_1389,
        din6 => coeff_9_load_reg_1456,
        din7 => coeff_34_load_reg_1389,
        din8 => coeff_34_load_reg_1389,
        din9 => coeff_34_load_reg_1389,
        din10 => coeff_34_load_reg_1389,
        din11 => coeff_14_load_reg_1461,
        din12 => coeff_34_load_reg_1389,
        din13 => coeff_34_load_reg_1389,
        din14 => coeff_34_load_reg_1389,
        din15 => coeff_34_load_reg_1389,
        din16 => coeff_19_load_reg_1466,
        din17 => coeff_34_load_reg_1389,
        din18 => coeff_34_load_reg_1389,
        din19 => coeff_34_load_reg_1389,
        din20 => coeff_34_load_reg_1389,
        din21 => coeff_24_load_reg_1471,
        din22 => coeff_34_load_reg_1389,
        din23 => coeff_34_load_reg_1389,
        din24 => coeff_34_load_reg_1389,
        din25 => coeff_34_load_reg_1389,
        din26 => coeff_29_load_reg_1476,
        din27 => coeff_34_load_reg_1389,
        din28 => coeff_34_load_reg_1389,
        din29 => coeff_34_load_reg_1389,
        din30 => coeff_34_load_reg_1389,
        din31 => coeff_34_load_reg_1389,
        din32 => coeff_34_load_reg_1389,
        din33 => coeff_34_load_reg_1389,
        din34 => coeff_34_load_reg_1389,
        din35 => coeff_34_load_reg_1389,
        din36 => coeff_34_load_reg_1389,
        din37 => coeff_34_load_reg_1389,
        din38 => coeff_34_load_reg_1389,
        din39 => coeff_34_load_reg_1389,
        din40 => coeff_34_load_reg_1389,
        din41 => coeff_34_load_reg_1389,
        din42 => coeff_34_load_reg_1389,
        din43 => coeff_34_load_reg_1389,
        din44 => coeff_34_load_reg_1389,
        din45 => coeff_34_load_reg_1389,
        din46 => coeff_34_load_reg_1389,
        din47 => coeff_34_load_reg_1389,
        din48 => coeff_34_load_reg_1389,
        din49 => coeff_34_load_reg_1389,
        din50 => coeff_34_load_reg_1389,
        din51 => coeff_34_load_reg_1389,
        din52 => coeff_34_load_reg_1389,
        din53 => coeff_34_load_reg_1389,
        din54 => coeff_34_load_reg_1389,
        din55 => coeff_34_load_reg_1389,
        din56 => coeff_34_load_reg_1389,
        din57 => coeff_34_load_reg_1389,
        din58 => coeff_34_load_reg_1389,
        din59 => coeff_34_load_reg_1389,
        din60 => coeff_34_load_reg_1389,
        din61 => coeff_34_load_reg_1389,
        din62 => coeff_34_load_reg_1389,
        din63 => coeff_34_load_reg_1389,
        din64 => coeff_34_load_reg_1389,
        din65 => i5_phi_fu_287_p4,
        dout => a2_assign_fu_1010_p66);

    eq_mul_32s_16s_32_2_U4 : component eq_mul_32s_16s_32_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => b0_assign_reg_1683,
        din1 => sample_assign_phi_fu_309_p4,
        ce => ap_const_logic_1,
        dout => grp_fu_1113_p2);

    eq_mul_16s_32s_32_2_U5 : component eq_mul_16s_32s_32_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => x1_fix_load_reg_1688,
        din1 => b1_assign_reg_1638,
        ce => ap_const_logic_1,
        dout => grp_fu_1121_p2);

    eq_mul_16s_32s_32_2_U6 : component eq_mul_16s_32s_32_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => x2_fix_load_reg_1693,
        din1 => b2_assign_reg_1643,
        ce => ap_const_logic_1,
        dout => grp_fu_1129_p2);

    eq_mul_17s_32s_32_2_U7 : component eq_mul_17s_32s_32_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => y1_fix_load_reg_1698,
        din1 => a1_assign_reg_1648,
        ce => ap_const_logic_1,
        dout => grp_fu_1137_p2);

    eq_mul_17s_32s_32_2_U8 : component eq_mul_17s_32s_32_2
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => y2_fix_load_reg_1703,
        din1 => a2_assign_reg_1653,
        ce => ap_const_logic_1,
        dout => grp_fu_1145_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_block_pp0_stage2_flag00011011 = ap_const_boolean_0))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 xor ap_const_logic_1);
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011011 = ap_const_boolean_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    band_assign_reg_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                band_assign_reg_294 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
                band_assign_reg_294 <= b_reg_1608;
            end if; 
        end if;
    end process;

    i5_reg_283_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                i5_reg_283 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
                i5_reg_283 <= i_reg_1678;
            end if; 
        end if;
    end process;

    sample_assign_reg_305_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                sample_assign_reg_305 <= sampleIn;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
                sample_assign_reg_305 <= input_reg_1763;
            end if; 
        end if;
    end process;

    tmp_1_reg_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                tmp_1_reg_316 <= tmp_6_reg_271;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1))) then 
                tmp_1_reg_316 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_6_reg_271_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then 
                tmp_6_reg_271 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
                tmp_6_reg_271 <= input_reg_1763;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_fu_707_p2))) then
                a1_assign_reg_1648 <= a1_assign_fu_940_p66;
                a2_assign_reg_1653 <= a2_assign_fu_1010_p66;
                b1_assign_reg_1638 <= b1_assign_fu_800_p66;
                b2_assign_reg_1643 <= b2_assign_fu_870_p66;
                newSel3_reg_1628 <= newSel3_fu_785_p3;
                newSel4_reg_1633 <= newSel4_fu_793_p3;
                or_cond_reg_1623 <= or_cond_fu_761_p2;
                sel_tmp4_reg_1613 <= sel_tmp4_fu_731_p2;
                sel_tmp6_reg_1618 <= sel_tmp6_fu_737_p2;
                x1_fix_addr_reg_1658 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
                x2_fix_addr_reg_1663 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
                y1_fix_addr_reg_1668 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
                y2_fix_addr_reg_1673 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then
                ap_reg_pp0_iter1_exitcond_reg_1604 <= exitcond_reg_1604;
                ap_reg_pp0_iter1_y1_fix_addr_reg_1668 <= y1_fix_addr_reg_1668;
                exitcond_reg_1604 <= exitcond_fu_707_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604))) then
                b0_assign_reg_1683 <= b0_assign_fu_1103_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0))) then
                b_reg_1608 <= b_fu_713_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (ap_const_lv6_0 = tmp_3_fu_491_p2))) then
                coeff_0 <= b0;
                coeff_1 <= b1;
                coeff_2 <= b2;
                coeff_3 <= a1;
                coeff_4 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then
                coeff_0_load_reg_1571 <= coeff_0;
                coeff_10_load_reg_1581 <= coeff_10;
                coeff_11_load_reg_1551 <= coeff_11;
                coeff_12_load_reg_1521 <= coeff_12;
                coeff_13_load_reg_1491 <= coeff_13;
                coeff_14_load_reg_1461 <= coeff_14;
                coeff_15_load_reg_1586 <= coeff_15;
                coeff_16_load_reg_1556 <= coeff_16;
                coeff_17_load_reg_1526 <= coeff_17;
                coeff_18_load_reg_1496 <= coeff_18;
                coeff_19_load_reg_1466 <= coeff_19;
                coeff_1_load_reg_1541 <= coeff_1;
                coeff_20_load_reg_1591 <= coeff_20;
                coeff_21_load_reg_1561 <= coeff_21;
                coeff_22_load_reg_1531 <= coeff_22;
                coeff_23_load_reg_1501 <= coeff_23;
                coeff_24_load_reg_1471 <= coeff_24;
                coeff_25_load_reg_1596 <= coeff_25;
                coeff_26_load_reg_1566 <= coeff_26;
                coeff_27_load_reg_1536 <= coeff_27;
                coeff_28_load_reg_1506 <= coeff_28;
                coeff_29_load_reg_1476 <= coeff_29;
                coeff_2_load_reg_1511 <= coeff_2;
                coeff_30_load_reg_1198 <= coeff_30;
                coeff_31_load_reg_1203 <= coeff_31;
                coeff_32_load_reg_1265 <= coeff_32;
                coeff_33_load_reg_1327 <= coeff_33;
                coeff_34_load_reg_1389 <= coeff_34;
                coeff_3_load_reg_1481 <= coeff_3;
                coeff_4_load_reg_1451 <= coeff_4;
                coeff_5_load_reg_1576 <= coeff_5;
                coeff_6_load_reg_1546 <= coeff_6;
                coeff_7_load_reg_1516 <= coeff_7;
                coeff_8_load_reg_1486 <= coeff_8;
                coeff_9_load_reg_1456 <= coeff_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (tmp_3_fu_491_p2 = ap_const_lv6_A))) then
                coeff_10 <= b0;
                coeff_11 <= b1;
                coeff_12 <= b2;
                coeff_13 <= a1;
                coeff_14 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (tmp_3_fu_491_p2 = ap_const_lv6_F))) then
                coeff_15 <= b0;
                coeff_16 <= b1;
                coeff_17 <= b2;
                coeff_18 <= a1;
                coeff_19 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (tmp_3_fu_491_p2 = ap_const_lv6_14))) then
                coeff_20 <= b0;
                coeff_21 <= b1;
                coeff_22 <= b2;
                coeff_23 <= a1;
                coeff_24 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (tmp_3_fu_491_p2 = ap_const_lv6_19))) then
                coeff_25 <= b0;
                coeff_26 <= b1;
                coeff_27 <= b2;
                coeff_28 <= a1;
                coeff_29 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and not((ap_const_lv6_0 = tmp_3_fu_491_p2)) and not((tmp_3_fu_491_p2 = ap_const_lv6_5)) and not((tmp_3_fu_491_p2 = ap_const_lv6_A)) and not((tmp_3_fu_491_p2 = ap_const_lv6_F)) and not((tmp_3_fu_491_p2 = ap_const_lv6_14)) and not((tmp_3_fu_491_p2 = ap_const_lv6_19)))) then
                coeff_30 <= b0;
                coeff_31 <= b1;
                coeff_32 <= b2;
                coeff_33 <= a1;
                coeff_34 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1) and (tmp_3_fu_491_p2 = ap_const_lv6_5))) then
                coeff_5 <= b0;
                coeff_6 <= b1;
                coeff_7 <= b2;
                coeff_8 <= a1;
                coeff_9 <= a2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_0 = exitcond_fu_707_p2))) then
                i_reg_1678 <= i_fu_1088_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
                input_reg_1763 <= out_fu_1164_p2(30 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604))) then
                tmp_10_i_reg_1758 <= out_fu_1164_p2(31 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604))) then
                tmp_2_i_reg_1738 <= grp_fu_1121_p2;
                tmp_3_i_reg_1743 <= grp_fu_1129_p2;
                tmp_4_i_reg_1748 <= grp_fu_1137_p2;
                tmp_5_i_reg_1753 <= grp_fu_1145_p2;
                tmp_i_reg_1733 <= grp_fu_1113_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604))) then
                x1_fix_load_reg_1688 <= x1_fix_q0;
                x2_fix_load_reg_1693 <= x2_fix_q0;
                y1_fix_load_reg_1698 <= y1_fix_q0;
                y2_fix_load_reg_1703 <= y2_fix_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_s_fu_329_p2, exitcond_fu_707_p2, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00011011, ap_block_pp0_stage2_flag00011011, ap_block_pp0_stage1_flag00011011)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_s_fu_329_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (exitcond_fu_707_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (exitcond_fu_707_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_block_pp0_stage1_flag00011011 = ap_const_boolean_0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (((ap_block_pp0_stage2_flag00011011 = ap_const_boolean_0) and not(((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage2_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage2_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(4);
    ap_CS_fsm_state9 <= ap_CS_fsm(5);
        ap_block_pp0_stage0_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_flag00011001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_flag00011011 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_flag00011001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_flag00011011 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_flag00011001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_flag00011011 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_fu_707_p2)
    begin
        if ((exitcond_fu_707_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b0_assign_fu_1103_p3 <= 
        newSel3_reg_1628 when (or_cond3_fu_1098_p2(0) = '1') else 
        newSel4_reg_1633;
    b_fu_713_p2 <= std_logic_vector(unsigned(band_assign_phi_fu_298_p4) + unsigned(ap_const_lv3_1));

    band_assign_phi_fu_298_p4_assign_proc : process(band_assign_reg_294, exitcond_reg_1604, ap_CS_fsm_pp0_stage0, b_reg_1608, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_0 = exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            band_assign_phi_fu_298_p4 <= b_reg_1608;
        else 
            band_assign_phi_fu_298_p4 <= band_assign_reg_294;
        end if; 
    end process;

    exitcond_fu_707_p2 <= "1" when (band_assign_phi_fu_298_p4 = ap_const_lv3_7) else "0";

    i5_phi_fu_287_p4_assign_proc : process(i5_reg_283, exitcond_reg_1604, ap_CS_fsm_pp0_stage0, i_reg_1678, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_lv1_0 = exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            i5_phi_fu_287_p4 <= i_reg_1678;
        else 
            i5_phi_fu_287_p4 <= i5_reg_283;
        end if; 
    end process;

    i_fu_1088_p2 <= std_logic_vector(unsigned(i5_phi_fu_287_p4) + unsigned(ap_const_lv6_5));
    newSel1_fu_767_p3 <= 
        coeff_20_load_reg_1591 when (sel_tmp6_fu_737_p2(0) = '1') else 
        coeff_15_load_reg_1586;
    newSel2_fu_773_p3 <= 
        coeff_10_load_reg_1581 when (sel_tmp2_fu_725_p2(0) = '1') else 
        coeff_5_load_reg_1576;
    newSel3_fu_785_p3 <= 
        newSel_fu_755_p3 when (or_cond_fu_761_p2(0) = '1') else 
        newSel1_fu_767_p3;
    newSel4_fu_793_p3 <= 
        newSel2_fu_773_p3 when (or_cond2_fu_779_p2(0) = '1') else 
        coeff_30_load_reg_1198;
    newSel_fu_755_p3 <= 
        coeff_0_load_reg_1571 when (sel_tmp1_fu_749_p2(0) = '1') else 
        coeff_25_load_reg_1596;
    or_cond1_fu_1094_p2 <= (sel_tmp6_reg_1618 or sel_tmp4_reg_1613);
    or_cond2_fu_779_p2 <= (sel_tmp2_fu_725_p2 or sel_tmp_fu_719_p2);
    or_cond3_fu_1098_p2 <= (or_cond_reg_1623 or or_cond1_fu_1094_p2);
    or_cond_fu_761_p2 <= (sel_tmp1_fu_749_p2 or sel_tmp8_fu_743_p2);
    out_fu_1164_p2 <= std_logic_vector(unsigned(tmp_8_i_fu_1159_p2) - unsigned(tmp_5_i_reg_1753));

    sampleOut_ap_vld_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            sampleOut_ap_vld <= ap_const_logic_1;
        else 
            sampleOut_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    sample_assign_phi_fu_309_p4_assign_proc : process(sample_assign_reg_305, ap_reg_pp0_iter1_exitcond_reg_1604, ap_CS_fsm_pp0_stage2, input_reg_1763, ap_enable_reg_pp0_iter1, ap_block_pp0_stage2_flag00000000)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage2_flag00000000 = ap_const_boolean_0))) then 
            sample_assign_phi_fu_309_p4 <= input_reg_1763;
        else 
            sample_assign_phi_fu_309_p4 <= sample_assign_reg_305;
        end if; 
    end process;

    sel_tmp1_fu_749_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_0) else "0";
    sel_tmp2_fu_725_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_A) else "0";
    sel_tmp4_fu_731_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_F) else "0";
    sel_tmp6_fu_737_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_14) else "0";
    sel_tmp8_fu_743_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_19) else "0";
    sel_tmp_fu_719_p2 <= "1" when (i5_phi_fu_287_p4 = ap_const_lv6_5) else "0";
    tmp1_fu_1150_p2 <= std_logic_vector(unsigned(tmp_i_reg_1733) + unsigned(tmp_3_i_reg_1743));
    tmp_1_i_fu_1080_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(band_assign_phi_fu_298_p4),32));
    tmp_2_fu_475_p1 <= band(6 - 1 downto 0);
    tmp_3_fu_491_p2 <= std_logic_vector(unsigned(tmp_2_fu_475_p1) + unsigned(tmp_fu_483_p3));
    tmp_5_fu_479_p1 <= band(4 - 1 downto 0);
    tmp_7_i_fu_1154_p2 <= std_logic_vector(unsigned(tmp1_fu_1150_p2) + unsigned(tmp_2_i_reg_1738));
    tmp_8_i_fu_1159_p2 <= std_logic_vector(unsigned(tmp_7_i_fu_1154_p2) - unsigned(tmp_4_i_reg_1748));
    tmp_fu_483_p3 <= (tmp_5_fu_479_p1 & ap_const_lv2_0);
    tmp_s_fu_329_p2 <= "1" when (signed(band) < signed(ap_const_lv16_7)) else "0";

    x1_fix_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, x1_fix_addr_reg_1658, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0_flag00000000, ap_block_pp0_stage2_flag00000000, tmp_1_i_fu_1080_p1)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter0)) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00000000 = ap_const_boolean_0))) then 
                x1_fix_address0 <= x1_fix_addr_reg_1658;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
                x1_fix_address0 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
            else 
                x1_fix_address0 <= "XXX";
            end if;
        else 
            x1_fix_address0 <= "XXX";
        end if; 
    end process;


    x1_fix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_flag00011001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0)))) then 
            x1_fix_ce0 <= ap_const_logic_1;
        else 
            x1_fix_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x1_fix_we0_assign_proc : process(exitcond_reg_1604, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_0 = exitcond_reg_1604) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0))) then 
            x1_fix_we0 <= ap_const_logic_1;
        else 
            x1_fix_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x2_fix_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, x2_fix_addr_reg_1663, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_flag00000000, tmp_1_i_fu_1080_p1, ap_block_pp0_stage1_flag00000000)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter0)) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00000000 = ap_const_boolean_0))) then 
                x2_fix_address0 <= x2_fix_addr_reg_1663;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
                x2_fix_address0 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
            else 
                x2_fix_address0 <= "XXX";
            end if;
        else 
            x2_fix_address0 <= "XXX";
        end if; 
    end process;


    x2_fix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_flag00011001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0)))) then 
            x2_fix_ce0 <= ap_const_logic_1;
        else 
            x2_fix_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x2_fix_we0_assign_proc : process(exitcond_reg_1604, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604))) then 
            x2_fix_we0 <= ap_const_logic_1;
        else 
            x2_fix_we0 <= ap_const_logic_0;
        end if; 
    end process;


    y1_fix_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_reg_pp0_iter1_y1_fix_addr_reg_1668, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000, ap_block_pp0_stage2_flag00000000, tmp_1_i_fu_1080_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage2_flag00000000 = ap_const_boolean_0))) then 
            y1_fix_address0 <= ap_reg_pp0_iter1_y1_fix_addr_reg_1668;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
            y1_fix_address0 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
        else 
            y1_fix_address0 <= "XXX";
        end if; 
    end process;


    y1_fix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_flag00011001, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1)))) then 
            y1_fix_ce0 <= ap_const_logic_1;
        else 
            y1_fix_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y1_fix_we0_assign_proc : process(ap_reg_pp0_iter1_exitcond_reg_1604, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_flag00011001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_block_pp0_stage2_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_reg_1604) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            y1_fix_we0 <= ap_const_logic_1;
        else 
            y1_fix_we0 <= ap_const_logic_0;
        end if; 
    end process;


    y2_fix_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, y2_fix_addr_reg_1673, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_flag00000000, tmp_1_i_fu_1080_p1, ap_block_pp0_stage1_flag00000000)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter0)) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00000000 = ap_const_boolean_0))) then 
                y2_fix_address0 <= y2_fix_addr_reg_1673;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0))) then 
                y2_fix_address0 <= tmp_1_i_fu_1080_p1(3 - 1 downto 0);
            else 
                y2_fix_address0 <= "XXX";
            end if;
        else 
            y2_fix_address0 <= "XXX";
        end if; 
    end process;


    y2_fix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_flag00011001, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_flag00011001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0)))) then 
            y2_fix_ce0 <= ap_const_logic_1;
        else 
            y2_fix_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y2_fix_we0_assign_proc : process(exitcond_reg_1604, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_block_pp0_stage1_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_reg_1604))) then 
            y2_fix_we0 <= ap_const_logic_1;
        else 
            y2_fix_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
