// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="eq,hls_ip_2017_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.742000,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=20,HLS_SYN_FF=8326,HLS_SYN_LUT=2383}" *)

module eq (
        ap_clk,
        ap_rst_n,
        s_axi_eq_io_AWVALID,
        s_axi_eq_io_AWREADY,
        s_axi_eq_io_AWADDR,
        s_axi_eq_io_WVALID,
        s_axi_eq_io_WREADY,
        s_axi_eq_io_WDATA,
        s_axi_eq_io_WSTRB,
        s_axi_eq_io_ARVALID,
        s_axi_eq_io_ARREADY,
        s_axi_eq_io_ARADDR,
        s_axi_eq_io_RVALID,
        s_axi_eq_io_RREADY,
        s_axi_eq_io_RDATA,
        s_axi_eq_io_RRESP,
        s_axi_eq_io_BVALID,
        s_axi_eq_io_BREADY,
        s_axi_eq_io_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_state8 = 6'd16;
parameter    ap_ST_fsm_state9 = 6'd32;
parameter    C_S_AXI_EQ_IO_DATA_WIDTH = 32;
parameter    C_S_AXI_EQ_IO_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_EQ_IO_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_eq_io_AWVALID;
output   s_axi_eq_io_AWREADY;
input  [C_S_AXI_EQ_IO_ADDR_WIDTH - 1:0] s_axi_eq_io_AWADDR;
input   s_axi_eq_io_WVALID;
output   s_axi_eq_io_WREADY;
input  [C_S_AXI_EQ_IO_DATA_WIDTH - 1:0] s_axi_eq_io_WDATA;
input  [C_S_AXI_EQ_IO_WSTRB_WIDTH - 1:0] s_axi_eq_io_WSTRB;
input   s_axi_eq_io_ARVALID;
output   s_axi_eq_io_ARREADY;
input  [C_S_AXI_EQ_IO_ADDR_WIDTH - 1:0] s_axi_eq_io_ARADDR;
output   s_axi_eq_io_RVALID;
input   s_axi_eq_io_RREADY;
output  [C_S_AXI_EQ_IO_DATA_WIDTH - 1:0] s_axi_eq_io_RDATA;
output  [1:0] s_axi_eq_io_RRESP;
output   s_axi_eq_io_BVALID;
input   s_axi_eq_io_BREADY;
output  [1:0] s_axi_eq_io_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] b0;
wire   [31:0] b1;
wire   [31:0] b2;
wire   [31:0] a1;
wire   [31:0] a2;
wire   [15:0] band;
wire   [15:0] sampleIn;
reg    sampleOut_ap_vld;
reg   [31:0] coeff_30;
reg   [31:0] coeff_31;
reg   [31:0] coeff_32;
reg   [31:0] coeff_33;
reg   [31:0] coeff_34;
reg   [31:0] coeff_4;
reg   [31:0] coeff_9;
reg   [31:0] coeff_14;
reg   [31:0] coeff_19;
reg   [31:0] coeff_24;
reg   [31:0] coeff_29;
reg   [31:0] coeff_3;
reg   [31:0] coeff_8;
reg   [31:0] coeff_13;
reg   [31:0] coeff_18;
reg   [31:0] coeff_23;
reg   [31:0] coeff_28;
reg   [31:0] coeff_2;
reg   [31:0] coeff_7;
reg   [31:0] coeff_12;
reg   [31:0] coeff_17;
reg   [31:0] coeff_22;
reg   [31:0] coeff_27;
reg   [31:0] coeff_1;
reg   [31:0] coeff_6;
reg   [31:0] coeff_11;
reg   [31:0] coeff_16;
reg   [31:0] coeff_21;
reg   [31:0] coeff_26;
reg   [31:0] coeff_0;
reg   [31:0] coeff_5;
reg   [31:0] coeff_10;
reg   [31:0] coeff_15;
reg   [31:0] coeff_20;
reg   [31:0] coeff_25;
reg   [2:0] x1_fix_address0;
reg    x1_fix_ce0;
reg    x1_fix_we0;
wire   [15:0] x1_fix_q0;
reg   [2:0] x2_fix_address0;
reg    x2_fix_ce0;
reg    x2_fix_we0;
wire   [15:0] x2_fix_q0;
reg   [2:0] y1_fix_address0;
reg    y1_fix_ce0;
reg    y1_fix_we0;
wire   [16:0] y1_fix_q0;
reg   [2:0] y2_fix_address0;
reg    y2_fix_ce0;
reg    y2_fix_we0;
wire   [16:0] y2_fix_q0;
reg   [15:0] tmp_6_reg_271;
reg   [5:0] i5_reg_283;
reg   [2:0] band_assign_reg_294;
reg   [15:0] sample_assign_reg_305;
wire   [0:0] tmp_s_fu_329_p2;
reg   [31:0] coeff_30_load_reg_1198;
reg   [31:0] coeff_31_load_reg_1203;
reg   [31:0] coeff_32_load_reg_1265;
reg   [31:0] coeff_33_load_reg_1327;
reg   [31:0] coeff_34_load_reg_1389;
reg   [31:0] coeff_4_load_reg_1451;
reg   [31:0] coeff_9_load_reg_1456;
reg   [31:0] coeff_14_load_reg_1461;
reg   [31:0] coeff_19_load_reg_1466;
reg   [31:0] coeff_24_load_reg_1471;
reg   [31:0] coeff_29_load_reg_1476;
reg   [31:0] coeff_3_load_reg_1481;
reg   [31:0] coeff_8_load_reg_1486;
reg   [31:0] coeff_13_load_reg_1491;
reg   [31:0] coeff_18_load_reg_1496;
reg   [31:0] coeff_23_load_reg_1501;
reg   [31:0] coeff_28_load_reg_1506;
reg   [31:0] coeff_2_load_reg_1511;
reg   [31:0] coeff_7_load_reg_1516;
reg   [31:0] coeff_12_load_reg_1521;
reg   [31:0] coeff_17_load_reg_1526;
reg   [31:0] coeff_22_load_reg_1531;
reg   [31:0] coeff_27_load_reg_1536;
reg   [31:0] coeff_1_load_reg_1541;
reg   [31:0] coeff_6_load_reg_1546;
reg   [31:0] coeff_11_load_reg_1551;
reg   [31:0] coeff_16_load_reg_1556;
reg   [31:0] coeff_21_load_reg_1561;
reg   [31:0] coeff_26_load_reg_1566;
reg   [31:0] coeff_0_load_reg_1571;
reg   [31:0] coeff_5_load_reg_1576;
reg   [31:0] coeff_10_load_reg_1581;
reg   [31:0] coeff_15_load_reg_1586;
reg   [31:0] coeff_20_load_reg_1591;
reg   [31:0] coeff_25_load_reg_1596;
wire   [0:0] exitcond_fu_707_p2;
reg   [0:0] exitcond_reg_1604;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_reg_1604;
wire   [2:0] b_fu_713_p2;
reg   [2:0] b_reg_1608;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] sel_tmp4_fu_731_p2;
reg   [0:0] sel_tmp4_reg_1613;
wire   [0:0] sel_tmp6_fu_737_p2;
reg   [0:0] sel_tmp6_reg_1618;
wire   [0:0] or_cond_fu_761_p2;
reg   [0:0] or_cond_reg_1623;
wire   [31:0] newSel3_fu_785_p3;
reg   [31:0] newSel3_reg_1628;
wire   [31:0] newSel4_fu_793_p3;
reg   [31:0] newSel4_reg_1633;
wire  signed [31:0] b1_assign_fu_800_p66;
reg  signed [31:0] b1_assign_reg_1638;
wire  signed [31:0] b2_assign_fu_870_p66;
reg  signed [31:0] b2_assign_reg_1643;
wire  signed [31:0] a1_assign_fu_940_p66;
reg  signed [31:0] a1_assign_reg_1648;
wire  signed [31:0] a2_assign_fu_1010_p66;
reg  signed [31:0] a2_assign_reg_1653;
reg   [2:0] x1_fix_addr_reg_1658;
reg   [2:0] x2_fix_addr_reg_1663;
reg   [2:0] y1_fix_addr_reg_1668;
reg   [2:0] ap_reg_pp0_iter1_y1_fix_addr_reg_1668;
reg   [2:0] y2_fix_addr_reg_1673;
wire   [5:0] i_fu_1088_p2;
reg   [5:0] i_reg_1678;
wire  signed [31:0] b0_assign_fu_1103_p3;
reg  signed [31:0] b0_assign_reg_1683;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_flag00011001;
reg  signed [15:0] x1_fix_load_reg_1688;
reg  signed [15:0] x2_fix_load_reg_1693;
reg  signed [16:0] y1_fix_load_reg_1698;
reg  signed [16:0] y2_fix_load_reg_1703;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_flag00011001;
wire   [31:0] grp_fu_1113_p2;
reg   [31:0] tmp_i_reg_1733;
wire   [31:0] grp_fu_1121_p2;
reg   [31:0] tmp_2_i_reg_1738;
wire   [31:0] grp_fu_1129_p2;
reg   [31:0] tmp_3_i_reg_1743;
wire   [31:0] grp_fu_1137_p2;
reg   [31:0] tmp_4_i_reg_1748;
wire   [31:0] grp_fu_1145_p2;
reg   [31:0] tmp_5_i_reg_1753;
reg   [16:0] tmp_10_i_reg_1758;
reg   [15:0] input_reg_1763;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage2_flag00011011;
reg   [5:0] i5_phi_fu_287_p4;
wire    ap_block_pp0_stage0_flag00000000;
reg   [2:0] band_assign_phi_fu_298_p4;
reg   [15:0] sample_assign_phi_fu_309_p4;
wire    ap_block_pp0_stage2_flag00000000;
reg   [15:0] tmp_1_reg_316;
wire    ap_CS_fsm_state8;
wire   [31:0] tmp_1_i_fu_1080_p1;
wire   [5:0] tmp_3_fu_491_p2;
wire    ap_CS_fsm_state9;
wire    ap_block_pp0_stage1_flag00000000;
wire   [3:0] tmp_5_fu_479_p1;
wire   [5:0] tmp_2_fu_475_p1;
wire   [5:0] tmp_fu_483_p3;
wire   [0:0] sel_tmp1_fu_749_p2;
wire   [0:0] sel_tmp8_fu_743_p2;
wire   [0:0] sel_tmp2_fu_725_p2;
wire   [0:0] sel_tmp_fu_719_p2;
wire   [31:0] newSel_fu_755_p3;
wire   [31:0] newSel1_fu_767_p3;
wire   [0:0] or_cond2_fu_779_p2;
wire   [31:0] newSel2_fu_773_p3;
wire   [0:0] or_cond1_fu_1094_p2;
wire   [0:0] or_cond3_fu_1098_p2;
wire   [31:0] tmp1_fu_1150_p2;
wire   [31:0] tmp_7_i_fu_1154_p2;
wire   [31:0] tmp_8_i_fu_1159_p2;
wire   [31:0] out_fu_1164_p2;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_flag00011011;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 coeff_30 = 32'd0;
#0 coeff_31 = 32'd0;
#0 coeff_32 = 32'd0;
#0 coeff_33 = 32'd0;
#0 coeff_34 = 32'd0;
#0 coeff_4 = 32'd0;
#0 coeff_9 = 32'd0;
#0 coeff_14 = 32'd0;
#0 coeff_19 = 32'd0;
#0 coeff_24 = 32'd0;
#0 coeff_29 = 32'd0;
#0 coeff_3 = 32'd0;
#0 coeff_8 = 32'd0;
#0 coeff_13 = 32'd0;
#0 coeff_18 = 32'd0;
#0 coeff_23 = 32'd0;
#0 coeff_28 = 32'd0;
#0 coeff_2 = 32'd0;
#0 coeff_7 = 32'd0;
#0 coeff_12 = 32'd0;
#0 coeff_17 = 32'd0;
#0 coeff_22 = 32'd0;
#0 coeff_27 = 32'd0;
#0 coeff_1 = 32'd0;
#0 coeff_6 = 32'd0;
#0 coeff_11 = 32'd0;
#0 coeff_16 = 32'd0;
#0 coeff_21 = 32'd0;
#0 coeff_26 = 32'd0;
#0 coeff_0 = 32'd0;
#0 coeff_5 = 32'd0;
#0 coeff_10 = 32'd0;
#0 coeff_15 = 32'd0;
#0 coeff_20 = 32'd0;
#0 coeff_25 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

eq_x1_fix #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
x1_fix_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x1_fix_address0),
    .ce0(x1_fix_ce0),
    .we0(x1_fix_we0),
    .d0(sample_assign_phi_fu_309_p4),
    .q0(x1_fix_q0)
);

eq_x1_fix #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
x2_fix_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x2_fix_address0),
    .ce0(x2_fix_ce0),
    .we0(x2_fix_we0),
    .d0(x1_fix_q0),
    .q0(x2_fix_q0)
);

eq_y1_fix #(
    .DataWidth( 17 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
y1_fix_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(y1_fix_address0),
    .ce0(y1_fix_ce0),
    .we0(y1_fix_we0),
    .d0(tmp_10_i_reg_1758),
    .q0(y1_fix_q0)
);

eq_y1_fix #(
    .DataWidth( 17 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
y2_fix_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(y2_fix_address0),
    .ce0(y2_fix_ce0),
    .we0(y2_fix_we0),
    .d0(y1_fix_q0),
    .q0(y2_fix_q0)
);

eq_eq_io_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_EQ_IO_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_EQ_IO_DATA_WIDTH ))
eq_eq_io_s_axi_U(
    .AWVALID(s_axi_eq_io_AWVALID),
    .AWREADY(s_axi_eq_io_AWREADY),
    .AWADDR(s_axi_eq_io_AWADDR),
    .WVALID(s_axi_eq_io_WVALID),
    .WREADY(s_axi_eq_io_WREADY),
    .WDATA(s_axi_eq_io_WDATA),
    .WSTRB(s_axi_eq_io_WSTRB),
    .ARVALID(s_axi_eq_io_ARVALID),
    .ARREADY(s_axi_eq_io_ARREADY),
    .ARADDR(s_axi_eq_io_ARADDR),
    .RVALID(s_axi_eq_io_RVALID),
    .RREADY(s_axi_eq_io_RREADY),
    .RDATA(s_axi_eq_io_RDATA),
    .RRESP(s_axi_eq_io_RRESP),
    .BVALID(s_axi_eq_io_BVALID),
    .BREADY(s_axi_eq_io_BREADY),
    .BRESP(s_axi_eq_io_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .b0(b0),
    .b1(b1),
    .b2(b2),
    .a1(a1),
    .a2(a2),
    .band(band),
    .sampleIn(sampleIn),
    .sampleOut(tmp_1_reg_316),
    .sampleOut_ap_vld(sampleOut_ap_vld)
);

eq_mux_646_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
eq_mux_646_32_1_U0(
    .din1(coeff_1_load_reg_1541),
    .din2(coeff_31_load_reg_1203),
    .din3(coeff_31_load_reg_1203),
    .din4(coeff_31_load_reg_1203),
    .din5(coeff_31_load_reg_1203),
    .din6(coeff_6_load_reg_1546),
    .din7(coeff_31_load_reg_1203),
    .din8(coeff_31_load_reg_1203),
    .din9(coeff_31_load_reg_1203),
    .din10(coeff_31_load_reg_1203),
    .din11(coeff_11_load_reg_1551),
    .din12(coeff_31_load_reg_1203),
    .din13(coeff_31_load_reg_1203),
    .din14(coeff_31_load_reg_1203),
    .din15(coeff_31_load_reg_1203),
    .din16(coeff_16_load_reg_1556),
    .din17(coeff_31_load_reg_1203),
    .din18(coeff_31_load_reg_1203),
    .din19(coeff_31_load_reg_1203),
    .din20(coeff_31_load_reg_1203),
    .din21(coeff_21_load_reg_1561),
    .din22(coeff_31_load_reg_1203),
    .din23(coeff_31_load_reg_1203),
    .din24(coeff_31_load_reg_1203),
    .din25(coeff_31_load_reg_1203),
    .din26(coeff_26_load_reg_1566),
    .din27(coeff_31_load_reg_1203),
    .din28(coeff_31_load_reg_1203),
    .din29(coeff_31_load_reg_1203),
    .din30(coeff_31_load_reg_1203),
    .din31(coeff_31_load_reg_1203),
    .din32(coeff_31_load_reg_1203),
    .din33(coeff_31_load_reg_1203),
    .din34(coeff_31_load_reg_1203),
    .din35(coeff_31_load_reg_1203),
    .din36(coeff_31_load_reg_1203),
    .din37(coeff_31_load_reg_1203),
    .din38(coeff_31_load_reg_1203),
    .din39(coeff_31_load_reg_1203),
    .din40(coeff_31_load_reg_1203),
    .din41(coeff_31_load_reg_1203),
    .din42(coeff_31_load_reg_1203),
    .din43(coeff_31_load_reg_1203),
    .din44(coeff_31_load_reg_1203),
    .din45(coeff_31_load_reg_1203),
    .din46(coeff_31_load_reg_1203),
    .din47(coeff_31_load_reg_1203),
    .din48(coeff_31_load_reg_1203),
    .din49(coeff_31_load_reg_1203),
    .din50(coeff_31_load_reg_1203),
    .din51(coeff_31_load_reg_1203),
    .din52(coeff_31_load_reg_1203),
    .din53(coeff_31_load_reg_1203),
    .din54(coeff_31_load_reg_1203),
    .din55(coeff_31_load_reg_1203),
    .din56(coeff_31_load_reg_1203),
    .din57(coeff_31_load_reg_1203),
    .din58(coeff_31_load_reg_1203),
    .din59(coeff_31_load_reg_1203),
    .din60(coeff_31_load_reg_1203),
    .din61(coeff_31_load_reg_1203),
    .din62(coeff_31_load_reg_1203),
    .din63(coeff_31_load_reg_1203),
    .din64(coeff_31_load_reg_1203),
    .din65(i5_phi_fu_287_p4),
    .dout(b1_assign_fu_800_p66)
);

eq_mux_646_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
eq_mux_646_32_1_U1(
    .din1(coeff_2_load_reg_1511),
    .din2(coeff_32_load_reg_1265),
    .din3(coeff_32_load_reg_1265),
    .din4(coeff_32_load_reg_1265),
    .din5(coeff_32_load_reg_1265),
    .din6(coeff_7_load_reg_1516),
    .din7(coeff_32_load_reg_1265),
    .din8(coeff_32_load_reg_1265),
    .din9(coeff_32_load_reg_1265),
    .din10(coeff_32_load_reg_1265),
    .din11(coeff_12_load_reg_1521),
    .din12(coeff_32_load_reg_1265),
    .din13(coeff_32_load_reg_1265),
    .din14(coeff_32_load_reg_1265),
    .din15(coeff_32_load_reg_1265),
    .din16(coeff_17_load_reg_1526),
    .din17(coeff_32_load_reg_1265),
    .din18(coeff_32_load_reg_1265),
    .din19(coeff_32_load_reg_1265),
    .din20(coeff_32_load_reg_1265),
    .din21(coeff_22_load_reg_1531),
    .din22(coeff_32_load_reg_1265),
    .din23(coeff_32_load_reg_1265),
    .din24(coeff_32_load_reg_1265),
    .din25(coeff_32_load_reg_1265),
    .din26(coeff_27_load_reg_1536),
    .din27(coeff_32_load_reg_1265),
    .din28(coeff_32_load_reg_1265),
    .din29(coeff_32_load_reg_1265),
    .din30(coeff_32_load_reg_1265),
    .din31(coeff_32_load_reg_1265),
    .din32(coeff_32_load_reg_1265),
    .din33(coeff_32_load_reg_1265),
    .din34(coeff_32_load_reg_1265),
    .din35(coeff_32_load_reg_1265),
    .din36(coeff_32_load_reg_1265),
    .din37(coeff_32_load_reg_1265),
    .din38(coeff_32_load_reg_1265),
    .din39(coeff_32_load_reg_1265),
    .din40(coeff_32_load_reg_1265),
    .din41(coeff_32_load_reg_1265),
    .din42(coeff_32_load_reg_1265),
    .din43(coeff_32_load_reg_1265),
    .din44(coeff_32_load_reg_1265),
    .din45(coeff_32_load_reg_1265),
    .din46(coeff_32_load_reg_1265),
    .din47(coeff_32_load_reg_1265),
    .din48(coeff_32_load_reg_1265),
    .din49(coeff_32_load_reg_1265),
    .din50(coeff_32_load_reg_1265),
    .din51(coeff_32_load_reg_1265),
    .din52(coeff_32_load_reg_1265),
    .din53(coeff_32_load_reg_1265),
    .din54(coeff_32_load_reg_1265),
    .din55(coeff_32_load_reg_1265),
    .din56(coeff_32_load_reg_1265),
    .din57(coeff_32_load_reg_1265),
    .din58(coeff_32_load_reg_1265),
    .din59(coeff_32_load_reg_1265),
    .din60(coeff_32_load_reg_1265),
    .din61(coeff_32_load_reg_1265),
    .din62(coeff_32_load_reg_1265),
    .din63(coeff_32_load_reg_1265),
    .din64(coeff_32_load_reg_1265),
    .din65(i5_phi_fu_287_p4),
    .dout(b2_assign_fu_870_p66)
);

eq_mux_646_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
eq_mux_646_32_1_U2(
    .din1(coeff_3_load_reg_1481),
    .din2(coeff_33_load_reg_1327),
    .din3(coeff_33_load_reg_1327),
    .din4(coeff_33_load_reg_1327),
    .din5(coeff_33_load_reg_1327),
    .din6(coeff_8_load_reg_1486),
    .din7(coeff_33_load_reg_1327),
    .din8(coeff_33_load_reg_1327),
    .din9(coeff_33_load_reg_1327),
    .din10(coeff_33_load_reg_1327),
    .din11(coeff_13_load_reg_1491),
    .din12(coeff_33_load_reg_1327),
    .din13(coeff_33_load_reg_1327),
    .din14(coeff_33_load_reg_1327),
    .din15(coeff_33_load_reg_1327),
    .din16(coeff_18_load_reg_1496),
    .din17(coeff_33_load_reg_1327),
    .din18(coeff_33_load_reg_1327),
    .din19(coeff_33_load_reg_1327),
    .din20(coeff_33_load_reg_1327),
    .din21(coeff_23_load_reg_1501),
    .din22(coeff_33_load_reg_1327),
    .din23(coeff_33_load_reg_1327),
    .din24(coeff_33_load_reg_1327),
    .din25(coeff_33_load_reg_1327),
    .din26(coeff_28_load_reg_1506),
    .din27(coeff_33_load_reg_1327),
    .din28(coeff_33_load_reg_1327),
    .din29(coeff_33_load_reg_1327),
    .din30(coeff_33_load_reg_1327),
    .din31(coeff_33_load_reg_1327),
    .din32(coeff_33_load_reg_1327),
    .din33(coeff_33_load_reg_1327),
    .din34(coeff_33_load_reg_1327),
    .din35(coeff_33_load_reg_1327),
    .din36(coeff_33_load_reg_1327),
    .din37(coeff_33_load_reg_1327),
    .din38(coeff_33_load_reg_1327),
    .din39(coeff_33_load_reg_1327),
    .din40(coeff_33_load_reg_1327),
    .din41(coeff_33_load_reg_1327),
    .din42(coeff_33_load_reg_1327),
    .din43(coeff_33_load_reg_1327),
    .din44(coeff_33_load_reg_1327),
    .din45(coeff_33_load_reg_1327),
    .din46(coeff_33_load_reg_1327),
    .din47(coeff_33_load_reg_1327),
    .din48(coeff_33_load_reg_1327),
    .din49(coeff_33_load_reg_1327),
    .din50(coeff_33_load_reg_1327),
    .din51(coeff_33_load_reg_1327),
    .din52(coeff_33_load_reg_1327),
    .din53(coeff_33_load_reg_1327),
    .din54(coeff_33_load_reg_1327),
    .din55(coeff_33_load_reg_1327),
    .din56(coeff_33_load_reg_1327),
    .din57(coeff_33_load_reg_1327),
    .din58(coeff_33_load_reg_1327),
    .din59(coeff_33_load_reg_1327),
    .din60(coeff_33_load_reg_1327),
    .din61(coeff_33_load_reg_1327),
    .din62(coeff_33_load_reg_1327),
    .din63(coeff_33_load_reg_1327),
    .din64(coeff_33_load_reg_1327),
    .din65(i5_phi_fu_287_p4),
    .dout(a1_assign_fu_940_p66)
);

eq_mux_646_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
eq_mux_646_32_1_U3(
    .din1(coeff_4_load_reg_1451),
    .din2(coeff_34_load_reg_1389),
    .din3(coeff_34_load_reg_1389),
    .din4(coeff_34_load_reg_1389),
    .din5(coeff_34_load_reg_1389),
    .din6(coeff_9_load_reg_1456),
    .din7(coeff_34_load_reg_1389),
    .din8(coeff_34_load_reg_1389),
    .din9(coeff_34_load_reg_1389),
    .din10(coeff_34_load_reg_1389),
    .din11(coeff_14_load_reg_1461),
    .din12(coeff_34_load_reg_1389),
    .din13(coeff_34_load_reg_1389),
    .din14(coeff_34_load_reg_1389),
    .din15(coeff_34_load_reg_1389),
    .din16(coeff_19_load_reg_1466),
    .din17(coeff_34_load_reg_1389),
    .din18(coeff_34_load_reg_1389),
    .din19(coeff_34_load_reg_1389),
    .din20(coeff_34_load_reg_1389),
    .din21(coeff_24_load_reg_1471),
    .din22(coeff_34_load_reg_1389),
    .din23(coeff_34_load_reg_1389),
    .din24(coeff_34_load_reg_1389),
    .din25(coeff_34_load_reg_1389),
    .din26(coeff_29_load_reg_1476),
    .din27(coeff_34_load_reg_1389),
    .din28(coeff_34_load_reg_1389),
    .din29(coeff_34_load_reg_1389),
    .din30(coeff_34_load_reg_1389),
    .din31(coeff_34_load_reg_1389),
    .din32(coeff_34_load_reg_1389),
    .din33(coeff_34_load_reg_1389),
    .din34(coeff_34_load_reg_1389),
    .din35(coeff_34_load_reg_1389),
    .din36(coeff_34_load_reg_1389),
    .din37(coeff_34_load_reg_1389),
    .din38(coeff_34_load_reg_1389),
    .din39(coeff_34_load_reg_1389),
    .din40(coeff_34_load_reg_1389),
    .din41(coeff_34_load_reg_1389),
    .din42(coeff_34_load_reg_1389),
    .din43(coeff_34_load_reg_1389),
    .din44(coeff_34_load_reg_1389),
    .din45(coeff_34_load_reg_1389),
    .din46(coeff_34_load_reg_1389),
    .din47(coeff_34_load_reg_1389),
    .din48(coeff_34_load_reg_1389),
    .din49(coeff_34_load_reg_1389),
    .din50(coeff_34_load_reg_1389),
    .din51(coeff_34_load_reg_1389),
    .din52(coeff_34_load_reg_1389),
    .din53(coeff_34_load_reg_1389),
    .din54(coeff_34_load_reg_1389),
    .din55(coeff_34_load_reg_1389),
    .din56(coeff_34_load_reg_1389),
    .din57(coeff_34_load_reg_1389),
    .din58(coeff_34_load_reg_1389),
    .din59(coeff_34_load_reg_1389),
    .din60(coeff_34_load_reg_1389),
    .din61(coeff_34_load_reg_1389),
    .din62(coeff_34_load_reg_1389),
    .din63(coeff_34_load_reg_1389),
    .din64(coeff_34_load_reg_1389),
    .din65(i5_phi_fu_287_p4),
    .dout(a2_assign_fu_1010_p66)
);

eq_mul_32s_16s_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
eq_mul_32s_16s_32_2_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(b0_assign_reg_1683),
    .din1(sample_assign_phi_fu_309_p4),
    .ce(1'b1),
    .dout(grp_fu_1113_p2)
);

eq_mul_16s_32s_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
eq_mul_16s_32s_32_2_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(x1_fix_load_reg_1688),
    .din1(b1_assign_reg_1638),
    .ce(1'b1),
    .dout(grp_fu_1121_p2)
);

eq_mul_16s_32s_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
eq_mul_16s_32s_32_2_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(x2_fix_load_reg_1693),
    .din1(b2_assign_reg_1643),
    .ce(1'b1),
    .dout(grp_fu_1129_p2)
);

eq_mul_17s_32s_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
eq_mul_17s_32s_32_2_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(y1_fix_load_reg_1698),
    .din1(a1_assign_reg_1648),
    .ce(1'b1),
    .dout(grp_fu_1137_p2)
);

eq_mul_17s_32s_32_2 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
eq_mul_17s_32s_32_2_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(y2_fix_load_reg_1703),
    .din1(a2_assign_reg_1653),
    .ce(1'b1),
    .dout(grp_fu_1145_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (ap_block_pp0_stage2_flag00011011 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011011 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
        band_assign_reg_294 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        band_assign_reg_294 <= b_reg_1608;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
        i5_reg_283 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        i5_reg_283 <= i_reg_1678;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
        sample_assign_reg_305 <= sampleIn;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        sample_assign_reg_305 <= input_reg_1763;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_1_reg_316 <= tmp_6_reg_271;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1))) begin
        tmp_1_reg_316 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
        tmp_6_reg_271 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        tmp_6_reg_271 <= input_reg_1763;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_fu_707_p2))) begin
        a1_assign_reg_1648 <= a1_assign_fu_940_p66;
        a2_assign_reg_1653 <= a2_assign_fu_1010_p66;
        b1_assign_reg_1638 <= b1_assign_fu_800_p66;
        b2_assign_reg_1643 <= b2_assign_fu_870_p66;
        newSel3_reg_1628 <= newSel3_fu_785_p3;
        newSel4_reg_1633 <= newSel4_fu_793_p3;
        or_cond_reg_1623 <= or_cond_fu_761_p2;
        sel_tmp4_reg_1613 <= sel_tmp4_fu_731_p2;
        sel_tmp6_reg_1618 <= sel_tmp6_fu_737_p2;
        x1_fix_addr_reg_1658 <= tmp_1_i_fu_1080_p1;
        x2_fix_addr_reg_1663 <= tmp_1_i_fu_1080_p1;
        y1_fix_addr_reg_1668 <= tmp_1_i_fu_1080_p1;
        y2_fix_addr_reg_1673 <= tmp_1_i_fu_1080_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond_reg_1604 <= exitcond_reg_1604;
        ap_reg_pp0_iter1_y1_fix_addr_reg_1668 <= y1_fix_addr_reg_1668;
        exitcond_reg_1604 <= exitcond_fu_707_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604))) begin
        b0_assign_reg_1683 <= b0_assign_fu_1103_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        b_reg_1608 <= b_fu_713_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (6'd0 == tmp_3_fu_491_p2))) begin
        coeff_0 <= b0;
        coeff_1 <= b1;
        coeff_2 <= b2;
        coeff_3 <= a1;
        coeff_4 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
        coeff_0_load_reg_1571 <= coeff_0;
        coeff_10_load_reg_1581 <= coeff_10;
        coeff_11_load_reg_1551 <= coeff_11;
        coeff_12_load_reg_1521 <= coeff_12;
        coeff_13_load_reg_1491 <= coeff_13;
        coeff_14_load_reg_1461 <= coeff_14;
        coeff_15_load_reg_1586 <= coeff_15;
        coeff_16_load_reg_1556 <= coeff_16;
        coeff_17_load_reg_1526 <= coeff_17;
        coeff_18_load_reg_1496 <= coeff_18;
        coeff_19_load_reg_1466 <= coeff_19;
        coeff_1_load_reg_1541 <= coeff_1;
        coeff_20_load_reg_1591 <= coeff_20;
        coeff_21_load_reg_1561 <= coeff_21;
        coeff_22_load_reg_1531 <= coeff_22;
        coeff_23_load_reg_1501 <= coeff_23;
        coeff_24_load_reg_1471 <= coeff_24;
        coeff_25_load_reg_1596 <= coeff_25;
        coeff_26_load_reg_1566 <= coeff_26;
        coeff_27_load_reg_1536 <= coeff_27;
        coeff_28_load_reg_1506 <= coeff_28;
        coeff_29_load_reg_1476 <= coeff_29;
        coeff_2_load_reg_1511 <= coeff_2;
        coeff_30_load_reg_1198 <= coeff_30;
        coeff_31_load_reg_1203 <= coeff_31;
        coeff_32_load_reg_1265 <= coeff_32;
        coeff_33_load_reg_1327 <= coeff_33;
        coeff_34_load_reg_1389 <= coeff_34;
        coeff_3_load_reg_1481 <= coeff_3;
        coeff_4_load_reg_1451 <= coeff_4;
        coeff_5_load_reg_1576 <= coeff_5;
        coeff_6_load_reg_1546 <= coeff_6;
        coeff_7_load_reg_1516 <= coeff_7;
        coeff_8_load_reg_1486 <= coeff_8;
        coeff_9_load_reg_1456 <= coeff_9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (tmp_3_fu_491_p2 == 6'd10))) begin
        coeff_10 <= b0;
        coeff_11 <= b1;
        coeff_12 <= b2;
        coeff_13 <= a1;
        coeff_14 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (tmp_3_fu_491_p2 == 6'd15))) begin
        coeff_15 <= b0;
        coeff_16 <= b1;
        coeff_17 <= b2;
        coeff_18 <= a1;
        coeff_19 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (tmp_3_fu_491_p2 == 6'd20))) begin
        coeff_20 <= b0;
        coeff_21 <= b1;
        coeff_22 <= b2;
        coeff_23 <= a1;
        coeff_24 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (tmp_3_fu_491_p2 == 6'd25))) begin
        coeff_25 <= b0;
        coeff_26 <= b1;
        coeff_27 <= b2;
        coeff_28 <= a1;
        coeff_29 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & ~(6'd0 == tmp_3_fu_491_p2) & ~(tmp_3_fu_491_p2 == 6'd5) & ~(tmp_3_fu_491_p2 == 6'd10) & ~(tmp_3_fu_491_p2 == 6'd15) & ~(tmp_3_fu_491_p2 == 6'd20) & ~(tmp_3_fu_491_p2 == 6'd25))) begin
        coeff_30 <= b0;
        coeff_31 <= b1;
        coeff_32 <= b2;
        coeff_33 <= a1;
        coeff_34 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1) & (tmp_3_fu_491_p2 == 6'd5))) begin
        coeff_5 <= b0;
        coeff_6 <= b1;
        coeff_7 <= b2;
        coeff_8 <= a1;
        coeff_9 <= a2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_fu_707_p2))) begin
        i_reg_1678 <= i_fu_1088_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        input_reg_1763 <= {{out_fu_1164_p2[30:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604))) begin
        tmp_10_i_reg_1758 <= {{out_fu_1164_p2[31:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604))) begin
        tmp_2_i_reg_1738 <= grp_fu_1121_p2;
        tmp_3_i_reg_1743 <= grp_fu_1129_p2;
        tmp_4_i_reg_1748 <= grp_fu_1137_p2;
        tmp_5_i_reg_1753 <= grp_fu_1145_p2;
        tmp_i_reg_1733 <= grp_fu_1113_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604))) begin
        x1_fix_load_reg_1688 <= x1_fix_q0;
        x2_fix_load_reg_1693 <= x2_fix_q0;
        y1_fix_load_reg_1698 <= y1_fix_q0;
        y2_fix_load_reg_1703 <= y2_fix_q0;
    end
end

always @ (*) begin
    if ((exitcond_fu_707_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        band_assign_phi_fu_298_p4 = b_reg_1608;
    end else begin
        band_assign_phi_fu_298_p4 = band_assign_reg_294;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd0 == exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        i5_phi_fu_287_p4 = i_reg_1678;
    end else begin
        i5_phi_fu_287_p4 = i5_reg_283;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sampleOut_ap_vld = 1'b1;
    end else begin
        sampleOut_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage2_flag00000000 == 1'b0))) begin
        sample_assign_phi_fu_309_p4 = input_reg_1763;
    end else begin
        sample_assign_phi_fu_309_p4 = sample_assign_reg_305;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00000000 == 1'b0))) begin
            x1_fix_address0 = x1_fix_addr_reg_1658;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
            x1_fix_address0 = tmp_1_i_fu_1080_p1;
        end else begin
            x1_fix_address0 = 'bx;
        end
    end else begin
        x1_fix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0)))) begin
        x1_fix_ce0 = 1'b1;
    end else begin
        x1_fix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_reg_1604) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0))) begin
        x1_fix_we0 = 1'b1;
    end else begin
        x1_fix_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
            x2_fix_address0 = x2_fix_addr_reg_1663;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
            x2_fix_address0 = tmp_1_i_fu_1080_p1;
        end else begin
            x2_fix_address0 = 'bx;
        end
    end else begin
        x2_fix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0)))) begin
        x2_fix_ce0 = 1'b1;
    end else begin
        x2_fix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604))) begin
        x2_fix_we0 = 1'b1;
    end else begin
        x2_fix_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage2_flag00000000 == 1'b0))) begin
        y1_fix_address0 = ap_reg_pp0_iter1_y1_fix_addr_reg_1668;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        y1_fix_address0 = tmp_1_i_fu_1080_p1;
    end else begin
        y1_fix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        y1_fix_ce0 = 1'b1;
    end else begin
        y1_fix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_reg_1604) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        y1_fix_we0 = 1'b1;
    end else begin
        y1_fix_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
            y2_fix_address0 = y2_fix_addr_reg_1673;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
            y2_fix_address0 = tmp_1_i_fu_1080_p1;
        end else begin
            y2_fix_address0 = 'bx;
        end
    end else begin
        y2_fix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0)))) begin
        y2_fix_ce0 = 1'b1;
    end else begin
        y2_fix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_1604))) begin
        y2_fix_we0 = 1'b1;
    end else begin
        y2_fix_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_s_fu_329_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_block_pp0_stage0_flag00011011 == 1'b0) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_fu_707_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_fu_707_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((ap_block_pp0_stage1_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_block_pp0_stage2_flag00011011 == 1'b0) & ~((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage2_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage2_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00011001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00011011 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_flag00011001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_flag00011011 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_flag00011001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_flag00011011 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b0_assign_fu_1103_p3 = ((or_cond3_fu_1098_p2[0:0] === 1'b1) ? newSel3_reg_1628 : newSel4_reg_1633);

assign b_fu_713_p2 = (band_assign_phi_fu_298_p4 + 3'd1);

assign exitcond_fu_707_p2 = ((band_assign_phi_fu_298_p4 == 3'd7) ? 1'b1 : 1'b0);

assign i_fu_1088_p2 = (i5_phi_fu_287_p4 + 6'd5);

assign newSel1_fu_767_p3 = ((sel_tmp6_fu_737_p2[0:0] === 1'b1) ? coeff_20_load_reg_1591 : coeff_15_load_reg_1586);

assign newSel2_fu_773_p3 = ((sel_tmp2_fu_725_p2[0:0] === 1'b1) ? coeff_10_load_reg_1581 : coeff_5_load_reg_1576);

assign newSel3_fu_785_p3 = ((or_cond_fu_761_p2[0:0] === 1'b1) ? newSel_fu_755_p3 : newSel1_fu_767_p3);

assign newSel4_fu_793_p3 = ((or_cond2_fu_779_p2[0:0] === 1'b1) ? newSel2_fu_773_p3 : coeff_30_load_reg_1198);

assign newSel_fu_755_p3 = ((sel_tmp1_fu_749_p2[0:0] === 1'b1) ? coeff_0_load_reg_1571 : coeff_25_load_reg_1596);

assign or_cond1_fu_1094_p2 = (sel_tmp6_reg_1618 | sel_tmp4_reg_1613);

assign or_cond2_fu_779_p2 = (sel_tmp2_fu_725_p2 | sel_tmp_fu_719_p2);

assign or_cond3_fu_1098_p2 = (or_cond_reg_1623 | or_cond1_fu_1094_p2);

assign or_cond_fu_761_p2 = (sel_tmp1_fu_749_p2 | sel_tmp8_fu_743_p2);

assign out_fu_1164_p2 = (tmp_8_i_fu_1159_p2 - tmp_5_i_reg_1753);

assign sel_tmp1_fu_749_p2 = ((i5_phi_fu_287_p4 == 6'd0) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_725_p2 = ((i5_phi_fu_287_p4 == 6'd10) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_731_p2 = ((i5_phi_fu_287_p4 == 6'd15) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_737_p2 = ((i5_phi_fu_287_p4 == 6'd20) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_743_p2 = ((i5_phi_fu_287_p4 == 6'd25) ? 1'b1 : 1'b0);

assign sel_tmp_fu_719_p2 = ((i5_phi_fu_287_p4 == 6'd5) ? 1'b1 : 1'b0);

assign tmp1_fu_1150_p2 = (tmp_i_reg_1733 + tmp_3_i_reg_1743);

assign tmp_1_i_fu_1080_p1 = band_assign_phi_fu_298_p4;

assign tmp_2_fu_475_p1 = band[5:0];

assign tmp_3_fu_491_p2 = (tmp_2_fu_475_p1 + tmp_fu_483_p3);

assign tmp_5_fu_479_p1 = band[3:0];

assign tmp_7_i_fu_1154_p2 = (tmp1_fu_1150_p2 + tmp_2_i_reg_1738);

assign tmp_8_i_fu_1159_p2 = (tmp_7_i_fu_1154_p2 - tmp_4_i_reg_1748);

assign tmp_fu_483_p3 = {{tmp_5_fu_479_p1}, {2'd0}};

assign tmp_s_fu_329_p2 = (($signed(band) < $signed(16'd7)) ? 1'b1 : 1'b0);

endmodule //eq
