// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _equalizer_HH_
#define _equalizer_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "equalizer_faddfsucud.h"
#include "equalizer_fmul_32dEe.h"
#include "equalizer_iir_coebkb.h"
#include "equalizer_iir_x_1.h"
#include "equalizer_eq_io_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_EQ_IO_ADDR_WIDTH = 8,
         unsigned int C_S_AXI_EQ_IO_DATA_WIDTH = 32>
struct equalizer : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_eq_io_AWVALID;
    sc_out< sc_logic > s_axi_eq_io_AWREADY;
    sc_in< sc_uint<C_S_AXI_EQ_IO_ADDR_WIDTH> > s_axi_eq_io_AWADDR;
    sc_in< sc_logic > s_axi_eq_io_WVALID;
    sc_out< sc_logic > s_axi_eq_io_WREADY;
    sc_in< sc_uint<C_S_AXI_EQ_IO_DATA_WIDTH> > s_axi_eq_io_WDATA;
    sc_in< sc_uint<C_S_AXI_EQ_IO_DATA_WIDTH/8> > s_axi_eq_io_WSTRB;
    sc_in< sc_logic > s_axi_eq_io_ARVALID;
    sc_out< sc_logic > s_axi_eq_io_ARREADY;
    sc_in< sc_uint<C_S_AXI_EQ_IO_ADDR_WIDTH> > s_axi_eq_io_ARADDR;
    sc_out< sc_logic > s_axi_eq_io_RVALID;
    sc_in< sc_logic > s_axi_eq_io_RREADY;
    sc_out< sc_uint<C_S_AXI_EQ_IO_DATA_WIDTH> > s_axi_eq_io_RDATA;
    sc_out< sc_lv<2> > s_axi_eq_io_RRESP;
    sc_out< sc_logic > s_axi_eq_io_BVALID;
    sc_in< sc_logic > s_axi_eq_io_BREADY;
    sc_out< sc_lv<2> > s_axi_eq_io_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    equalizer(sc_module_name name);
    SC_HAS_PROCESS(equalizer);

    ~equalizer();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    equalizer_iir_coebkb* iir_coeff_array_U;
    equalizer_iir_x_1* iir_x_1_U;
    equalizer_iir_x_1* iir_x_0_U;
    equalizer_iir_x_1* iir_y_1_U;
    equalizer_iir_x_1* iir_y_2_U;
    equalizer_eq_io_s_axi<C_S_AXI_EQ_IO_ADDR_WIDTH,C_S_AXI_EQ_IO_DATA_WIDTH>* equalizer_eq_io_s_axi_U;
    equalizer_faddfsucud<1,7,32,32,32>* equalizer_faddfsucud_U0;
    equalizer_fmul_32dEe<1,4,32,32,32>* equalizer_fmul_32dEe_U1;
    equalizer_fmul_32dEe<1,4,32,32,32>* equalizer_fmul_32dEe_U2;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<38> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > y_ap_vld;
    sc_signal< sc_lv<32> > x;
    sc_signal< sc_lv<32> > mode;
    sc_signal< sc_lv<5> > coeffs_address0;
    sc_signal< sc_logic > coeffs_ce0;
    sc_signal< sc_lv<32> > coeffs_q0;
    sc_signal< sc_lv<5> > iir_coeff_array_address0;
    sc_signal< sc_logic > iir_coeff_array_ce0;
    sc_signal< sc_logic > iir_coeff_array_we0;
    sc_signal< sc_lv<32> > iir_coeff_array_q0;
    sc_signal< sc_lv<5> > iir_coeff_array_address1;
    sc_signal< sc_logic > iir_coeff_array_ce1;
    sc_signal< sc_lv<32> > iir_coeff_array_q1;
    sc_signal< sc_logic > iir_x_1_ce0;
    sc_signal< sc_logic > iir_x_1_we0;
    sc_signal< sc_lv<32> > iir_x_1_q0;
    sc_signal< sc_lv<3> > iir_x_0_address0;
    sc_signal< sc_logic > iir_x_0_ce0;
    sc_signal< sc_logic > iir_x_0_we0;
    sc_signal< sc_lv<32> > iir_x_0_q0;
    sc_signal< sc_logic > iir_y_1_ce0;
    sc_signal< sc_logic > iir_y_1_we0;
    sc_signal< sc_lv<32> > iir_y_1_q0;
    sc_signal< sc_logic > iir_y_2_ce0;
    sc_signal< sc_logic > iir_y_2_we0;
    sc_signal< sc_lv<32> > iir_y_2_q0;
    sc_signal< sc_lv<32> > reg_270;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > reg_275;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<32> > grp_fu_261_p2;
    sc_signal< sc_lv<32> > reg_281;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<32> > reg_287;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > grp_fu_257_p2;
    sc_signal< sc_lv<32> > reg_292;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_logic > ap_CS_fsm_state37;
    sc_signal< sc_lv<1> > tmp_1_fu_299_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_470;
    sc_signal< sc_lv<6> > tmp_s_fu_325_p2;
    sc_signal< sc_lv<6> > tmp_s_reg_474;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<3> > i_1_fu_337_p2;
    sc_signal< sc_lv<3> > i_1_reg_482;
    sc_signal< sc_lv<5> > iir_coeff_array_addr_2_reg_497;
    sc_signal< sc_lv<5> > iir_coeff_array_addr_3_reg_502;
    sc_signal< sc_lv<5> > iir_coeff_array_addr_4_reg_507;
    sc_signal< sc_lv<3> > i_fu_432_p2;
    sc_signal< sc_lv<3> > i_reg_515;
    sc_signal< sc_lv<3> > iir_x_1_addr_reg_520;
    sc_signal< sc_lv<1> > exitcond_i_fu_426_p2;
    sc_signal< sc_lv<3> > iir_x_0_addr_reg_525;
    sc_signal< sc_lv<3> > iir_y_1_addr_reg_530;
    sc_signal< sc_lv<3> > iir_y_2_addr_reg_535;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > iir_coeff_array_addr_5_reg_545;
    sc_signal< sc_lv<3> > j_fu_459_p2;
    sc_signal< sc_lv<3> > j_reg_553;
    sc_signal< sc_lv<32> > iir_x_0_load_reg_558;
    sc_signal< sc_lv<32> > b2_reg_564;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > iir_x_1_load_reg_569;
    sc_signal< sc_lv<32> > grp_fu_266_p2;
    sc_signal< sc_lv<32> > tmp_3_i_reg_574;
    sc_signal< sc_lv<32> > iir_y_1_load_reg_579;
    sc_signal< sc_lv<32> > iir_y_2_load_reg_585;
    sc_signal< sc_lv<3> > i_i1_reg_212;
    sc_signal< sc_lv<1> > exitcond_i2_fu_453_p2;
    sc_signal< sc_lv<32> > temp_i_reg_223;
    sc_signal< sc_logic > ap_CS_fsm_state38;
    sc_signal< sc_lv<3> > i_i_reg_235;
    sc_signal< sc_lv<3> > j_i_reg_246;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > exitcond1_i_fu_331_p2;
    sc_signal< sc_lv<32> > tmp_3_cast_fu_377_p1;
    sc_signal< sc_lv<32> > tmp_4_cast_fu_388_p1;
    sc_signal< sc_lv<32> > tmp_5_cast_fu_399_p1;
    sc_signal< sc_lv<32> > tmp_6_cast_fu_410_p1;
    sc_signal< sc_lv<32> > tmp_7_cast_fu_421_p1;
    sc_signal< sc_lv<32> > i_i_cast3_fu_343_p1;
    sc_signal< sc_lv<32> > tmp_11_cast_fu_447_p1;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<32> > grp_fu_257_p0;
    sc_signal< sc_lv<32> > grp_fu_257_p1;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state31;
    sc_signal< sc_lv<32> > grp_fu_261_p0;
    sc_signal< sc_lv<32> > grp_fu_261_p1;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<4> > tmp_9_fu_313_p3;
    sc_signal< sc_lv<6> > tmp_8_fu_305_p3;
    sc_signal< sc_lv<6> > p_shl3_cast_fu_321_p1;
    sc_signal< sc_lv<4> > tmp_2_fu_359_p3;
    sc_signal< sc_lv<6> > tmp_fu_351_p3;
    sc_signal< sc_lv<6> > p_shl1_cast_fu_367_p1;
    sc_signal< sc_lv<6> > tmp_3_fu_371_p2;
    sc_signal< sc_lv<6> > tmp_4_fu_382_p2;
    sc_signal< sc_lv<6> > tmp_5_fu_393_p2;
    sc_signal< sc_lv<6> > tmp_6_fu_404_p2;
    sc_signal< sc_lv<6> > tmp_7_fu_415_p2;
    sc_signal< sc_lv<6> > j_i_cast1_cast_fu_438_p1;
    sc_signal< sc_lv<6> > tmp_10_fu_442_p2;
    sc_signal< sc_lv<2> > grp_fu_257_opcode;
    sc_signal< sc_lv<38> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<38> ap_ST_fsm_state1;
    static const sc_lv<38> ap_ST_fsm_state2;
    static const sc_lv<38> ap_ST_fsm_state3;
    static const sc_lv<38> ap_ST_fsm_state4;
    static const sc_lv<38> ap_ST_fsm_state5;
    static const sc_lv<38> ap_ST_fsm_state6;
    static const sc_lv<38> ap_ST_fsm_state7;
    static const sc_lv<38> ap_ST_fsm_state8;
    static const sc_lv<38> ap_ST_fsm_state9;
    static const sc_lv<38> ap_ST_fsm_state10;
    static const sc_lv<38> ap_ST_fsm_state11;
    static const sc_lv<38> ap_ST_fsm_state12;
    static const sc_lv<38> ap_ST_fsm_state13;
    static const sc_lv<38> ap_ST_fsm_state14;
    static const sc_lv<38> ap_ST_fsm_state15;
    static const sc_lv<38> ap_ST_fsm_state16;
    static const sc_lv<38> ap_ST_fsm_state17;
    static const sc_lv<38> ap_ST_fsm_state18;
    static const sc_lv<38> ap_ST_fsm_state19;
    static const sc_lv<38> ap_ST_fsm_state20;
    static const sc_lv<38> ap_ST_fsm_state21;
    static const sc_lv<38> ap_ST_fsm_state22;
    static const sc_lv<38> ap_ST_fsm_state23;
    static const sc_lv<38> ap_ST_fsm_state24;
    static const sc_lv<38> ap_ST_fsm_state25;
    static const sc_lv<38> ap_ST_fsm_state26;
    static const sc_lv<38> ap_ST_fsm_state27;
    static const sc_lv<38> ap_ST_fsm_state28;
    static const sc_lv<38> ap_ST_fsm_state29;
    static const sc_lv<38> ap_ST_fsm_state30;
    static const sc_lv<38> ap_ST_fsm_state31;
    static const sc_lv<38> ap_ST_fsm_state32;
    static const sc_lv<38> ap_ST_fsm_state33;
    static const sc_lv<38> ap_ST_fsm_state34;
    static const sc_lv<38> ap_ST_fsm_state35;
    static const sc_lv<38> ap_ST_fsm_state36;
    static const sc_lv<38> ap_ST_fsm_state37;
    static const sc_lv<38> ap_ST_fsm_state38;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<6> ap_const_lv6_2;
    static const sc_lv<6> ap_const_lv6_4;
    static const sc_lv<6> ap_const_lv6_5;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state38();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_coeffs_address0();
    void thread_coeffs_ce0();
    void thread_exitcond1_i_fu_331_p2();
    void thread_exitcond_i2_fu_453_p2();
    void thread_exitcond_i_fu_426_p2();
    void thread_grp_fu_257_opcode();
    void thread_grp_fu_257_p0();
    void thread_grp_fu_257_p1();
    void thread_grp_fu_261_p0();
    void thread_grp_fu_261_p1();
    void thread_i_1_fu_337_p2();
    void thread_i_fu_432_p2();
    void thread_i_i_cast3_fu_343_p1();
    void thread_iir_coeff_array_address0();
    void thread_iir_coeff_array_address1();
    void thread_iir_coeff_array_ce0();
    void thread_iir_coeff_array_ce1();
    void thread_iir_coeff_array_we0();
    void thread_iir_x_0_address0();
    void thread_iir_x_0_ce0();
    void thread_iir_x_0_we0();
    void thread_iir_x_1_ce0();
    void thread_iir_x_1_we0();
    void thread_iir_y_1_ce0();
    void thread_iir_y_1_we0();
    void thread_iir_y_2_ce0();
    void thread_iir_y_2_we0();
    void thread_j_fu_459_p2();
    void thread_j_i_cast1_cast_fu_438_p1();
    void thread_p_shl1_cast_fu_367_p1();
    void thread_p_shl3_cast_fu_321_p1();
    void thread_tmp_10_fu_442_p2();
    void thread_tmp_11_cast_fu_447_p1();
    void thread_tmp_1_fu_299_p2();
    void thread_tmp_2_fu_359_p3();
    void thread_tmp_3_cast_fu_377_p1();
    void thread_tmp_3_fu_371_p2();
    void thread_tmp_4_cast_fu_388_p1();
    void thread_tmp_4_fu_382_p2();
    void thread_tmp_5_cast_fu_399_p1();
    void thread_tmp_5_fu_393_p2();
    void thread_tmp_6_cast_fu_410_p1();
    void thread_tmp_6_fu_404_p2();
    void thread_tmp_7_cast_fu_421_p1();
    void thread_tmp_7_fu_415_p2();
    void thread_tmp_8_fu_305_p3();
    void thread_tmp_9_fu_313_p3();
    void thread_tmp_fu_351_p3();
    void thread_tmp_s_fu_325_p2();
    void thread_y_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
