// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "equalizer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic equalizer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic equalizer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<54> equalizer::ap_ST_fsm_state1 = "1";
const sc_lv<54> equalizer::ap_ST_fsm_state2 = "10";
const sc_lv<54> equalizer::ap_ST_fsm_state3 = "100";
const sc_lv<54> equalizer::ap_ST_fsm_state4 = "1000";
const sc_lv<54> equalizer::ap_ST_fsm_state5 = "10000";
const sc_lv<54> equalizer::ap_ST_fsm_state6 = "100000";
const sc_lv<54> equalizer::ap_ST_fsm_state7 = "1000000";
const sc_lv<54> equalizer::ap_ST_fsm_state8 = "10000000";
const sc_lv<54> equalizer::ap_ST_fsm_state9 = "100000000";
const sc_lv<54> equalizer::ap_ST_fsm_state10 = "1000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state11 = "10000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state12 = "100000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<54> equalizer::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<32> equalizer::ap_const_lv32_0 = "00000000000000000000000000000000";
const int equalizer::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> equalizer::ap_const_lv32_4 = "100";
const sc_lv<32> equalizer::ap_const_lv32_8 = "1000";
const sc_lv<32> equalizer::ap_const_lv32_12 = "10010";
const sc_lv<32> equalizer::ap_const_lv32_5 = "101";
const sc_lv<32> equalizer::ap_const_lv32_18 = "11000";
const sc_lv<32> equalizer::ap_const_lv32_1F = "11111";
const sc_lv<32> equalizer::ap_const_lv32_26 = "100110";
const sc_lv<32> equalizer::ap_const_lv32_2D = "101101";
const sc_lv<32> equalizer::ap_const_lv32_34 = "110100";
const sc_lv<32> equalizer::ap_const_lv32_1 = "1";
const sc_lv<1> equalizer::ap_const_lv1_0 = "0";
const sc_lv<1> equalizer::ap_const_lv1_1 = "1";
const sc_lv<32> equalizer::ap_const_lv32_2 = "10";
const sc_lv<32> equalizer::ap_const_lv32_9 = "1001";
const sc_lv<32> equalizer::ap_const_lv32_16 = "10110";
const sc_lv<3> equalizer::ap_const_lv3_0 = "000";
const sc_lv<32> equalizer::ap_const_lv32_35 = "110101";
const sc_lv<32> equalizer::ap_const_lv32_3 = "11";
const sc_lv<32> equalizer::ap_const_lv32_7 = "111";
const sc_lv<32> equalizer::ap_const_lv32_11 = "10001";
const sc_lv<32> equalizer::ap_const_lv32_19 = "11001";
const sc_lv<32> equalizer::ap_const_lv32_20 = "100000";
const sc_lv<32> equalizer::ap_const_lv32_27 = "100111";
const sc_lv<32> equalizer::ap_const_lv32_2E = "101110";
const sc_lv<32> equalizer::ap_const_lv32_6 = "110";
const sc_lv<32> equalizer::ap_const_lv32_13 = "10011";
const sc_lv<32> equalizer::ap_const_lv32_10 = "10000";
const sc_lv<32> equalizer::ap_const_lv32_17 = "10111";
const sc_lv<3> equalizer::ap_const_lv3_5 = "101";
const sc_lv<3> equalizer::ap_const_lv3_1 = "1";
const sc_lv<6> equalizer::ap_const_lv6_1 = "1";
const sc_lv<6> equalizer::ap_const_lv6_2 = "10";
const sc_lv<6> equalizer::ap_const_lv6_3 = "11";
const sc_lv<6> equalizer::ap_const_lv6_4 = "100";
const sc_lv<6> equalizer::ap_const_lv6_5 = "101";
const sc_lv<3> equalizer::ap_const_lv3_6 = "110";
const sc_lv<2> equalizer::ap_const_lv2_0 = "00";
const sc_lv<2> equalizer::ap_const_lv2_1 = "1";
const bool equalizer::ap_const_boolean_1 = true;

equalizer::equalizer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    iir_coeff_array_U = new equalizer_iir_coebkb("iir_coeff_array_U");
    iir_coeff_array_U->clk(ap_clk);
    iir_coeff_array_U->reset(ap_rst_n_inv);
    iir_coeff_array_U->address0(iir_coeff_array_address0);
    iir_coeff_array_U->ce0(iir_coeff_array_ce0);
    iir_coeff_array_U->we0(iir_coeff_array_we0);
    iir_coeff_array_U->d0(coeffs_q0);
    iir_coeff_array_U->q0(iir_coeff_array_q0);
    iir_coeff_array_U->address1(iir_coeff_array_address1);
    iir_coeff_array_U->ce1(iir_coeff_array_ce1);
    iir_coeff_array_U->q1(iir_coeff_array_q1);
    iir_x_1_U = new equalizer_iir_x_1("iir_x_1_U");
    iir_x_1_U->clk(ap_clk);
    iir_x_1_U->reset(ap_rst_n_inv);
    iir_x_1_U->address0(iir_x_1_addr_reg_563);
    iir_x_1_U->ce0(iir_x_1_ce0);
    iir_x_1_U->we0(iir_x_1_we0);
    iir_x_1_U->d0(iir_x_0_load_reg_601);
    iir_x_1_U->q0(iir_x_1_q0);
    iir_x_0_U = new equalizer_iir_x_1("iir_x_0_U");
    iir_x_0_U->clk(ap_clk);
    iir_x_0_U->reset(ap_rst_n_inv);
    iir_x_0_U->address0(iir_x_0_address0);
    iir_x_0_U->ce0(iir_x_0_ce0);
    iir_x_0_U->we0(iir_x_0_we0);
    iir_x_0_U->d0(temp_i_reg_233);
    iir_x_0_U->q0(iir_x_0_q0);
    iir_y_1_U = new equalizer_iir_x_1("iir_y_1_U");
    iir_y_1_U->clk(ap_clk);
    iir_y_1_U->reset(ap_rst_n_inv);
    iir_y_1_U->address0(iir_y_1_addr_reg_573);
    iir_y_1_U->ce0(iir_y_1_ce0);
    iir_y_1_U->we0(iir_y_1_we0);
    iir_y_1_U->d0(reg_319);
    iir_y_1_U->q0(iir_y_1_q0);
    iir_y_2_U = new equalizer_iir_x_1("iir_y_2_U");
    iir_y_2_U->clk(ap_clk);
    iir_y_2_U->reset(ap_rst_n_inv);
    iir_y_2_U->address0(iir_y_2_addr_reg_578);
    iir_y_2_U->ce0(iir_y_2_ce0);
    iir_y_2_U->we0(iir_y_2_we0);
    iir_y_2_U->d0(iir_y_1_q0);
    iir_y_2_U->q0(iir_y_2_q0);
    equalizer_eq_io_s_axi_U = new equalizer_eq_io_s_axi<C_S_AXI_EQ_IO_ADDR_WIDTH,C_S_AXI_EQ_IO_DATA_WIDTH>("equalizer_eq_io_s_axi_U");
    equalizer_eq_io_s_axi_U->AWVALID(s_axi_eq_io_AWVALID);
    equalizer_eq_io_s_axi_U->AWREADY(s_axi_eq_io_AWREADY);
    equalizer_eq_io_s_axi_U->AWADDR(s_axi_eq_io_AWADDR);
    equalizer_eq_io_s_axi_U->WVALID(s_axi_eq_io_WVALID);
    equalizer_eq_io_s_axi_U->WREADY(s_axi_eq_io_WREADY);
    equalizer_eq_io_s_axi_U->WDATA(s_axi_eq_io_WDATA);
    equalizer_eq_io_s_axi_U->WSTRB(s_axi_eq_io_WSTRB);
    equalizer_eq_io_s_axi_U->ARVALID(s_axi_eq_io_ARVALID);
    equalizer_eq_io_s_axi_U->ARREADY(s_axi_eq_io_ARREADY);
    equalizer_eq_io_s_axi_U->ARADDR(s_axi_eq_io_ARADDR);
    equalizer_eq_io_s_axi_U->RVALID(s_axi_eq_io_RVALID);
    equalizer_eq_io_s_axi_U->RREADY(s_axi_eq_io_RREADY);
    equalizer_eq_io_s_axi_U->RDATA(s_axi_eq_io_RDATA);
    equalizer_eq_io_s_axi_U->RRESP(s_axi_eq_io_RRESP);
    equalizer_eq_io_s_axi_U->BVALID(s_axi_eq_io_BVALID);
    equalizer_eq_io_s_axi_U->BREADY(s_axi_eq_io_BREADY);
    equalizer_eq_io_s_axi_U->BRESP(s_axi_eq_io_BRESP);
    equalizer_eq_io_s_axi_U->ACLK(ap_clk);
    equalizer_eq_io_s_axi_U->ARESET(ap_rst_n_inv);
    equalizer_eq_io_s_axi_U->ACLK_EN(ap_var_for_const0);
    equalizer_eq_io_s_axi_U->ap_start(ap_start);
    equalizer_eq_io_s_axi_U->interrupt(interrupt);
    equalizer_eq_io_s_axi_U->ap_ready(ap_ready);
    equalizer_eq_io_s_axi_U->ap_done(ap_done);
    equalizer_eq_io_s_axi_U->ap_idle(ap_idle);
    equalizer_eq_io_s_axi_U->y(temp_i_reg_233);
    equalizer_eq_io_s_axi_U->y_ap_vld(y_ap_vld);
    equalizer_eq_io_s_axi_U->x(x);
    equalizer_eq_io_s_axi_U->mode(mode);
    equalizer_eq_io_s_axi_U->coeffs_address0(coeffs_address0);
    equalizer_eq_io_s_axi_U->coeffs_ce0(coeffs_ce0);
    equalizer_eq_io_s_axi_U->coeffs_q0(coeffs_q0);
    equalizer_faddfsucud_U0 = new equalizer_faddfsucud<1,7,32,32,32>("equalizer_faddfsucud_U0");
    equalizer_faddfsucud_U0->clk(ap_clk);
    equalizer_faddfsucud_U0->reset(ap_rst_n_inv);
    equalizer_faddfsucud_U0->din0(grp_fu_267_p0);
    equalizer_faddfsucud_U0->din1(grp_fu_267_p1);
    equalizer_faddfsucud_U0->opcode(grp_fu_267_opcode);
    equalizer_faddfsucud_U0->ce(ap_var_for_const0);
    equalizer_faddfsucud_U0->dout(grp_fu_267_p2);
    equalizer_fmul_32dEe_U1 = new equalizer_fmul_32dEe<1,4,32,32,32>("equalizer_fmul_32dEe_U1");
    equalizer_fmul_32dEe_U1->clk(ap_clk);
    equalizer_fmul_32dEe_U1->reset(ap_rst_n_inv);
    equalizer_fmul_32dEe_U1->din0(grp_fu_271_p0);
    equalizer_fmul_32dEe_U1->din1(grp_fu_271_p1);
    equalizer_fmul_32dEe_U1->ce(ap_var_for_const0);
    equalizer_fmul_32dEe_U1->dout(grp_fu_271_p2);
    equalizer_fmul_32dEe_U2 = new equalizer_fmul_32dEe<1,4,32,32,32>("equalizer_fmul_32dEe_U2");
    equalizer_fmul_32dEe_U2->clk(ap_clk);
    equalizer_fmul_32dEe_U2->reset(ap_rst_n_inv);
    equalizer_fmul_32dEe_U2->din0(grp_fu_276_p0);
    equalizer_fmul_32dEe_U2->din1(grp_fu_276_p1);
    equalizer_fmul_32dEe_U2->ce(ap_var_for_const0);
    equalizer_fmul_32dEe_U2->dout(grp_fu_276_p2);
    equalizer_fdiv_32eOg_U3 = new equalizer_fdiv_32eOg<1,16,32,32,32>("equalizer_fdiv_32eOg_U3");
    equalizer_fdiv_32eOg_U3->clk(ap_clk);
    equalizer_fdiv_32eOg_U3->reset(ap_rst_n_inv);
    equalizer_fdiv_32eOg_U3->din0(grp_fu_280_p0);
    equalizer_fdiv_32eOg_U3->din1(reg_288);
    equalizer_fdiv_32eOg_U3->ce(ap_var_for_const0);
    equalizer_fdiv_32eOg_U3->dout(grp_fu_280_p2);
    equalizer_fdiv_32eOg_U4 = new equalizer_fdiv_32eOg<1,16,32,32,32>("equalizer_fdiv_32eOg_U4");
    equalizer_fdiv_32eOg_U4->clk(ap_clk);
    equalizer_fdiv_32eOg_U4->reset(ap_rst_n_inv);
    equalizer_fdiv_32eOg_U4->din0(grp_fu_284_p0);
    equalizer_fdiv_32eOg_U4->din1(reg_288);
    equalizer_fdiv_32eOg_U4->ce(ap_var_for_const0);
    equalizer_fdiv_32eOg_U4->dout(grp_fu_284_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state53);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state54);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_464_p2 );
    sensitive << ( exitcond1_i_fu_358_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_464_p2 );
    sensitive << ( exitcond1_i_fu_358_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_coeffs_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_12_cast_fu_485_p1 );

    SC_METHOD(thread_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_exitcond1_i_fu_358_p2);
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i1_reg_222 );

    SC_METHOD(thread_exitcond_i2_fu_491_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_i_reg_256 );

    SC_METHOD(thread_exitcond_i_fu_464_p2);
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i_reg_245 );

    SC_METHOD(thread_grp_fu_267_opcode);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_grp_fu_267_p0);
    sensitive << ( reg_308 );
    sensitive << ( reg_319 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_grp_fu_267_p1);
    sensitive << ( reg_308 );
    sensitive << ( reg_314 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( ap_CS_fsm_state40 );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_grp_fu_271_p0);
    sensitive << ( reg_288 );
    sensitive << ( reg_295 );
    sensitive << ( reg_301 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_271_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( iir_x_1_load_reg_607 );
    sensitive << ( iir_y_1_load_reg_627 );
    sensitive << ( temp_i_reg_233 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_276_p0);
    sensitive << ( reg_295 );
    sensitive << ( reg_301 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_276_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( iir_x_0_load_reg_601 );
    sensitive << ( iir_y_2_load_reg_632 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_280_p0);
    sensitive << ( tmp_i_reg_612 );
    sensitive << ( tmp_7_i_reg_622 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_i_3_reg_637 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_284_p0);
    sensitive << ( tmp_4_i_reg_617 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_10_i_reg_642 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_i_1_fu_364_p2);
    sensitive << ( i_i1_reg_222 );

    SC_METHOD(thread_i_fu_470_p2);
    sensitive << ( i_i_reg_245 );

    SC_METHOD(thread_i_i_cast3_fu_370_p1);
    sensitive << ( i_i_reg_245 );

    SC_METHOD(thread_iir_coeff_array_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_coeff_array_addr_3_reg_540 );
    sensitive << ( iir_coeff_array_addr_5_reg_550 );
    sensitive << ( iir_coeff_array_addr_6_reg_588 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_3_cast_fu_404_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_coeff_array_addr_2_reg_535 );
    sensitive << ( iir_coeff_array_addr_4_reg_545 );
    sensitive << ( tmp_4_cast_fu_415_p1 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_iir_x_0_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_x_0_addr_reg_568 );
    sensitive << ( i_i_cast3_fu_370_p1 );

    SC_METHOD(thread_iir_x_0_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_iir_x_0_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_iir_x_1_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_iir_x_1_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_iir_y_1_ce0);
    sensitive << ( ap_CS_fsm_state54 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_y_1_we0);
    sensitive << ( ap_CS_fsm_state54 );

    SC_METHOD(thread_iir_y_2_ce0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_y_2_we0);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_j_fu_497_p2);
    sensitive << ( j_i_reg_256 );

    SC_METHOD(thread_j_i_cast1_cast_fu_476_p1);
    sensitive << ( j_i_reg_256 );

    SC_METHOD(thread_p_shl1_cast_fu_394_p1);
    sensitive << ( tmp_2_fu_386_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_348_p1);
    sensitive << ( tmp_s_fu_340_p3 );

    SC_METHOD(thread_tmp_10_fu_352_p2);
    sensitive << ( tmp_9_fu_332_p3 );
    sensitive << ( p_shl3_cast_fu_348_p1 );

    SC_METHOD(thread_tmp_11_fu_480_p2);
    sensitive << ( tmp_10_reg_512 );
    sensitive << ( j_i_cast1_cast_fu_476_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_485_p1);
    sensitive << ( tmp_11_fu_480_p2 );

    SC_METHOD(thread_tmp_1_fu_326_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );

    SC_METHOD(thread_tmp_2_fu_386_p3);
    sensitive << ( i_i_reg_245 );

    SC_METHOD(thread_tmp_3_cast_fu_404_p1);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_3_fu_398_p2);
    sensitive << ( tmp_fu_378_p3 );
    sensitive << ( p_shl1_cast_fu_394_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_415_p1);
    sensitive << ( tmp_4_fu_409_p2 );

    SC_METHOD(thread_tmp_4_fu_409_p2);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_5_cast_fu_426_p1);
    sensitive << ( tmp_5_fu_420_p2 );

    SC_METHOD(thread_tmp_5_fu_420_p2);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_6_cast_fu_437_p1);
    sensitive << ( tmp_6_fu_431_p2 );

    SC_METHOD(thread_tmp_6_fu_431_p2);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_7_cast_fu_448_p1);
    sensitive << ( tmp_7_fu_442_p2 );

    SC_METHOD(thread_tmp_7_fu_442_p2);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_8_cast_fu_459_p1);
    sensitive << ( tmp_8_fu_453_p2 );

    SC_METHOD(thread_tmp_8_fu_453_p2);
    sensitive << ( tmp_3_fu_398_p2 );

    SC_METHOD(thread_tmp_9_fu_332_p3);
    sensitive << ( i_i1_reg_222 );

    SC_METHOD(thread_tmp_fu_378_p3);
    sensitive << ( i_i_reg_245 );

    SC_METHOD(thread_tmp_s_fu_340_p3);
    sensitive << ( i_i1_reg_222 );

    SC_METHOD(thread_y_ap_vld);
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_464_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_reg_508 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_464_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i2_fu_491_p2 );
    sensitive << ( exitcond1_i_fu_358_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "equalizer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_eq_io_AWVALID, "(port)s_axi_eq_io_AWVALID");
    sc_trace(mVcdFile, s_axi_eq_io_AWREADY, "(port)s_axi_eq_io_AWREADY");
    sc_trace(mVcdFile, s_axi_eq_io_AWADDR, "(port)s_axi_eq_io_AWADDR");
    sc_trace(mVcdFile, s_axi_eq_io_WVALID, "(port)s_axi_eq_io_WVALID");
    sc_trace(mVcdFile, s_axi_eq_io_WREADY, "(port)s_axi_eq_io_WREADY");
    sc_trace(mVcdFile, s_axi_eq_io_WDATA, "(port)s_axi_eq_io_WDATA");
    sc_trace(mVcdFile, s_axi_eq_io_WSTRB, "(port)s_axi_eq_io_WSTRB");
    sc_trace(mVcdFile, s_axi_eq_io_ARVALID, "(port)s_axi_eq_io_ARVALID");
    sc_trace(mVcdFile, s_axi_eq_io_ARREADY, "(port)s_axi_eq_io_ARREADY");
    sc_trace(mVcdFile, s_axi_eq_io_ARADDR, "(port)s_axi_eq_io_ARADDR");
    sc_trace(mVcdFile, s_axi_eq_io_RVALID, "(port)s_axi_eq_io_RVALID");
    sc_trace(mVcdFile, s_axi_eq_io_RREADY, "(port)s_axi_eq_io_RREADY");
    sc_trace(mVcdFile, s_axi_eq_io_RDATA, "(port)s_axi_eq_io_RDATA");
    sc_trace(mVcdFile, s_axi_eq_io_RRESP, "(port)s_axi_eq_io_RRESP");
    sc_trace(mVcdFile, s_axi_eq_io_BVALID, "(port)s_axi_eq_io_BVALID");
    sc_trace(mVcdFile, s_axi_eq_io_BREADY, "(port)s_axi_eq_io_BREADY");
    sc_trace(mVcdFile, s_axi_eq_io_BRESP, "(port)s_axi_eq_io_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, y_ap_vld, "y_ap_vld");
    sc_trace(mVcdFile, x, "x");
    sc_trace(mVcdFile, mode, "mode");
    sc_trace(mVcdFile, coeffs_address0, "coeffs_address0");
    sc_trace(mVcdFile, coeffs_ce0, "coeffs_ce0");
    sc_trace(mVcdFile, coeffs_q0, "coeffs_q0");
    sc_trace(mVcdFile, iir_coeff_array_address0, "iir_coeff_array_address0");
    sc_trace(mVcdFile, iir_coeff_array_ce0, "iir_coeff_array_ce0");
    sc_trace(mVcdFile, iir_coeff_array_we0, "iir_coeff_array_we0");
    sc_trace(mVcdFile, iir_coeff_array_q0, "iir_coeff_array_q0");
    sc_trace(mVcdFile, iir_coeff_array_address1, "iir_coeff_array_address1");
    sc_trace(mVcdFile, iir_coeff_array_ce1, "iir_coeff_array_ce1");
    sc_trace(mVcdFile, iir_coeff_array_q1, "iir_coeff_array_q1");
    sc_trace(mVcdFile, iir_x_1_ce0, "iir_x_1_ce0");
    sc_trace(mVcdFile, iir_x_1_we0, "iir_x_1_we0");
    sc_trace(mVcdFile, iir_x_1_q0, "iir_x_1_q0");
    sc_trace(mVcdFile, iir_x_0_address0, "iir_x_0_address0");
    sc_trace(mVcdFile, iir_x_0_ce0, "iir_x_0_ce0");
    sc_trace(mVcdFile, iir_x_0_we0, "iir_x_0_we0");
    sc_trace(mVcdFile, iir_x_0_q0, "iir_x_0_q0");
    sc_trace(mVcdFile, iir_y_1_ce0, "iir_y_1_ce0");
    sc_trace(mVcdFile, iir_y_1_we0, "iir_y_1_we0");
    sc_trace(mVcdFile, iir_y_1_q0, "iir_y_1_q0");
    sc_trace(mVcdFile, iir_y_2_ce0, "iir_y_2_ce0");
    sc_trace(mVcdFile, iir_y_2_we0, "iir_y_2_we0");
    sc_trace(mVcdFile, iir_y_2_q0, "iir_y_2_q0");
    sc_trace(mVcdFile, reg_288, "reg_288");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, reg_295, "reg_295");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, reg_301, "reg_301");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_280_p2, "grp_fu_280_p2");
    sc_trace(mVcdFile, reg_308, "reg_308");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, grp_fu_284_p2, "grp_fu_284_p2");
    sc_trace(mVcdFile, reg_314, "reg_314");
    sc_trace(mVcdFile, grp_fu_267_p2, "grp_fu_267_p2");
    sc_trace(mVcdFile, reg_319, "reg_319");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, ap_CS_fsm_state53, "ap_CS_fsm_state53");
    sc_trace(mVcdFile, tmp_1_fu_326_p2, "tmp_1_fu_326_p2");
    sc_trace(mVcdFile, tmp_1_reg_508, "tmp_1_reg_508");
    sc_trace(mVcdFile, tmp_10_fu_352_p2, "tmp_10_fu_352_p2");
    sc_trace(mVcdFile, tmp_10_reg_512, "tmp_10_reg_512");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_364_p2, "i_1_fu_364_p2");
    sc_trace(mVcdFile, i_1_reg_520, "i_1_reg_520");
    sc_trace(mVcdFile, iir_coeff_array_addr_2_reg_535, "iir_coeff_array_addr_2_reg_535");
    sc_trace(mVcdFile, iir_coeff_array_addr_3_reg_540, "iir_coeff_array_addr_3_reg_540");
    sc_trace(mVcdFile, iir_coeff_array_addr_4_reg_545, "iir_coeff_array_addr_4_reg_545");
    sc_trace(mVcdFile, iir_coeff_array_addr_5_reg_550, "iir_coeff_array_addr_5_reg_550");
    sc_trace(mVcdFile, i_fu_470_p2, "i_fu_470_p2");
    sc_trace(mVcdFile, i_reg_558, "i_reg_558");
    sc_trace(mVcdFile, iir_x_1_addr_reg_563, "iir_x_1_addr_reg_563");
    sc_trace(mVcdFile, exitcond_i_fu_464_p2, "exitcond_i_fu_464_p2");
    sc_trace(mVcdFile, iir_x_0_addr_reg_568, "iir_x_0_addr_reg_568");
    sc_trace(mVcdFile, iir_y_1_addr_reg_573, "iir_y_1_addr_reg_573");
    sc_trace(mVcdFile, iir_y_2_addr_reg_578, "iir_y_2_addr_reg_578");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, iir_coeff_array_addr_6_reg_588, "iir_coeff_array_addr_6_reg_588");
    sc_trace(mVcdFile, j_fu_497_p2, "j_fu_497_p2");
    sc_trace(mVcdFile, j_reg_596, "j_reg_596");
    sc_trace(mVcdFile, iir_x_0_load_reg_601, "iir_x_0_load_reg_601");
    sc_trace(mVcdFile, iir_x_1_load_reg_607, "iir_x_1_load_reg_607");
    sc_trace(mVcdFile, grp_fu_271_p2, "grp_fu_271_p2");
    sc_trace(mVcdFile, tmp_i_reg_612, "tmp_i_reg_612");
    sc_trace(mVcdFile, grp_fu_276_p2, "grp_fu_276_p2");
    sc_trace(mVcdFile, tmp_4_i_reg_617, "tmp_4_i_reg_617");
    sc_trace(mVcdFile, tmp_7_i_reg_622, "tmp_7_i_reg_622");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, iir_y_1_load_reg_627, "iir_y_1_load_reg_627");
    sc_trace(mVcdFile, iir_y_2_load_reg_632, "iir_y_2_load_reg_632");
    sc_trace(mVcdFile, tmp_i_3_reg_637, "tmp_i_3_reg_637");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, tmp_10_i_reg_642, "tmp_10_i_reg_642");
    sc_trace(mVcdFile, i_i1_reg_222, "i_i1_reg_222");
    sc_trace(mVcdFile, exitcond_i2_fu_491_p2, "exitcond_i2_fu_491_p2");
    sc_trace(mVcdFile, temp_i_reg_233, "temp_i_reg_233");
    sc_trace(mVcdFile, ap_CS_fsm_state54, "ap_CS_fsm_state54");
    sc_trace(mVcdFile, i_i_reg_245, "i_i_reg_245");
    sc_trace(mVcdFile, j_i_reg_256, "j_i_reg_256");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond1_i_fu_358_p2, "exitcond1_i_fu_358_p2");
    sc_trace(mVcdFile, tmp_3_cast_fu_404_p1, "tmp_3_cast_fu_404_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_415_p1, "tmp_4_cast_fu_415_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_426_p1, "tmp_5_cast_fu_426_p1");
    sc_trace(mVcdFile, tmp_6_cast_fu_437_p1, "tmp_6_cast_fu_437_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_448_p1, "tmp_7_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_459_p1, "tmp_8_cast_fu_459_p1");
    sc_trace(mVcdFile, i_i_cast3_fu_370_p1, "i_i_cast3_fu_370_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_485_p1, "tmp_12_cast_fu_485_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_267_p0, "grp_fu_267_p0");
    sc_trace(mVcdFile, grp_fu_267_p1, "grp_fu_267_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, grp_fu_271_p0, "grp_fu_271_p0");
    sc_trace(mVcdFile, grp_fu_271_p1, "grp_fu_271_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, grp_fu_276_p0, "grp_fu_276_p0");
    sc_trace(mVcdFile, grp_fu_276_p1, "grp_fu_276_p1");
    sc_trace(mVcdFile, grp_fu_280_p0, "grp_fu_280_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_284_p0, "grp_fu_284_p0");
    sc_trace(mVcdFile, tmp_s_fu_340_p3, "tmp_s_fu_340_p3");
    sc_trace(mVcdFile, tmp_9_fu_332_p3, "tmp_9_fu_332_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_348_p1, "p_shl3_cast_fu_348_p1");
    sc_trace(mVcdFile, tmp_2_fu_386_p3, "tmp_2_fu_386_p3");
    sc_trace(mVcdFile, tmp_fu_378_p3, "tmp_fu_378_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_394_p1, "p_shl1_cast_fu_394_p1");
    sc_trace(mVcdFile, tmp_3_fu_398_p2, "tmp_3_fu_398_p2");
    sc_trace(mVcdFile, tmp_4_fu_409_p2, "tmp_4_fu_409_p2");
    sc_trace(mVcdFile, tmp_5_fu_420_p2, "tmp_5_fu_420_p2");
    sc_trace(mVcdFile, tmp_6_fu_431_p2, "tmp_6_fu_431_p2");
    sc_trace(mVcdFile, tmp_7_fu_442_p2, "tmp_7_fu_442_p2");
    sc_trace(mVcdFile, tmp_8_fu_453_p2, "tmp_8_fu_453_p2");
    sc_trace(mVcdFile, j_i_cast1_cast_fu_476_p1, "j_i_cast1_cast_fu_476_p1");
    sc_trace(mVcdFile, tmp_11_fu_480_p2, "tmp_11_fu_480_p2");
    sc_trace(mVcdFile, grp_fu_267_opcode, "grp_fu_267_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("equalizer.hdltvin.dat");
    mHdltvoutHandle.open("equalizer.hdltvout.dat");
}

equalizer::~equalizer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete iir_coeff_array_U;
    delete iir_x_1_U;
    delete iir_x_0_U;
    delete iir_y_1_U;
    delete iir_y_2_U;
    delete equalizer_eq_io_s_axi_U;
    delete equalizer_faddfsucud_U0;
    delete equalizer_fmul_32dEe_U1;
    delete equalizer_fmul_32dEe_U2;
    delete equalizer_fdiv_32eOg_U3;
    delete equalizer_fdiv_32eOg_U4;
}

void equalizer::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void equalizer::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_326_p2.read(), ap_const_lv1_0))) {
        i_i1_reg_222 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i2_fu_491_p2.read()))) {
        i_i1_reg_222 = i_1_reg_520.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_326_p2.read(), ap_const_lv1_1))) {
        i_i_reg_245 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read())) {
        i_i_reg_245 = i_reg_558.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_358_p2.read()))) {
        j_i_reg_256 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_i_reg_256 = j_reg_596.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        reg_301 = iir_coeff_array_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        reg_301 = iir_coeff_array_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_326_p2.read(), ap_const_lv1_1))) {
        temp_i_reg_233 = x.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read())) {
        temp_i_reg_233 = reg_319.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_0))) {
        i_1_reg_520 = i_1_fu_364_p2.read();
        tmp_10_reg_512 = tmp_10_fu_352_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1))) {
        i_reg_558 = i_fu_470_p2.read();
        iir_coeff_array_addr_2_reg_535 =  (sc_lv<5>) (tmp_5_cast_fu_426_p1.read());
        iir_coeff_array_addr_3_reg_540 =  (sc_lv<5>) (tmp_6_cast_fu_437_p1.read());
        iir_coeff_array_addr_4_reg_545 =  (sc_lv<5>) (tmp_7_cast_fu_448_p1.read());
        iir_coeff_array_addr_5_reg_550 =  (sc_lv<5>) (tmp_8_cast_fu_459_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        iir_coeff_array_addr_6_reg_588 =  (sc_lv<5>) (tmp_12_cast_fu_485_p1.read());
        j_reg_596 = j_fu_497_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_464_p2.read()))) {
        iir_x_0_addr_reg_568 =  (sc_lv<3>) (i_i_cast3_fu_370_p1.read());
        iir_x_1_addr_reg_563 =  (sc_lv<3>) (i_i_cast3_fu_370_p1.read());
        iir_y_1_addr_reg_573 =  (sc_lv<3>) (i_i_cast3_fu_370_p1.read());
        iir_y_2_addr_reg_578 =  (sc_lv<3>) (i_i_cast3_fu_370_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_load_reg_601 = iir_x_0_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        iir_x_1_load_reg_607 = iir_x_1_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        iir_y_1_load_reg_627 = iir_y_1_q0.read();
        iir_y_2_load_reg_632 = iir_y_2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_288 = iir_coeff_array_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        reg_295 = iir_coeff_array_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read()))) {
        reg_308 = grp_fu_280_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read()))) {
        reg_314 = grp_fu_284_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read()))) {
        reg_319 = grp_fu_267_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        tmp_10_i_reg_642 = grp_fu_276_p2.read();
        tmp_i_3_reg_637 = grp_fu_271_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_1_reg_508 = tmp_1_fu_326_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_4_i_reg_617 = grp_fu_276_p2.read();
        tmp_i_reg_612 = grp_fu_271_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_7_i_reg_622 = grp_fu_271_p2.read();
    }
}

void equalizer::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void equalizer::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void equalizer::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void equalizer::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void equalizer::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void equalizer::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void equalizer::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void equalizer::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void equalizer::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void equalizer::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void equalizer::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void equalizer::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void equalizer::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void equalizer::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void equalizer::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[38];
}

void equalizer::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void equalizer::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void equalizer::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void equalizer::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void equalizer::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void equalizer::thread_ap_CS_fsm_state53() {
    ap_CS_fsm_state53 = ap_CS_fsm.read()[52];
}

void equalizer::thread_ap_CS_fsm_state54() {
    ap_CS_fsm_state54 = ap_CS_fsm.read()[53];
}

void equalizer::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void equalizer::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void equalizer::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void equalizer::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void equalizer::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         ((esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_464_p2.read())) || 
          (esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_358_p2.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void equalizer::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void equalizer::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         ((esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_464_p2.read())) || 
          (esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_358_p2.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void equalizer::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void equalizer::thread_coeffs_address0() {
    coeffs_address0 =  (sc_lv<5>) (tmp_12_cast_fu_485_p1.read());
}

void equalizer::thread_coeffs_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        coeffs_ce0 = ap_const_logic_1;
    } else {
        coeffs_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_exitcond1_i_fu_358_p2() {
    exitcond1_i_fu_358_p2 = (!i_i1_reg_222.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_222.read() == ap_const_lv3_5);
}

void equalizer::thread_exitcond_i2_fu_491_p2() {
    exitcond_i2_fu_491_p2 = (!j_i_reg_256.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_256.read() == ap_const_lv3_6);
}

void equalizer::thread_exitcond_i_fu_464_p2() {
    exitcond_i_fu_464_p2 = (!i_i_reg_245.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_245.read() == ap_const_lv3_5);
}

void equalizer::thread_grp_fu_267_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        grp_fu_267_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()))) {
        grp_fu_267_opcode = ap_const_lv2_0;
    } else {
        grp_fu_267_opcode = "XX";
    }
}

void equalizer::thread_grp_fu_267_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        grp_fu_267_p0 = reg_319.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        grp_fu_267_p0 = reg_308.read();
    } else {
        grp_fu_267_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_267_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()))) {
        grp_fu_267_p1 = reg_308.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        grp_fu_267_p1 = reg_314.read();
    } else {
        grp_fu_267_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_271_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_271_p0 = reg_295.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_271_p0 = reg_301.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_271_p0 = reg_288.read();
    } else {
        grp_fu_271_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_271_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_271_p1 = iir_y_1_load_reg_627.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_271_p1 = iir_x_1_load_reg_607.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_271_p1 = temp_i_reg_233.read();
    } else {
        grp_fu_271_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_276_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_276_p0 = reg_301.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_276_p0 = reg_295.read();
    } else {
        grp_fu_276_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_276_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_276_p1 = iir_y_2_load_reg_632.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_276_p1 = iir_x_0_load_reg_601.read();
    } else {
        grp_fu_276_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_280_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_280_p0 = tmp_i_3_reg_637.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_280_p0 = tmp_7_i_reg_622.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_280_p0 = tmp_i_reg_612.read();
    } else {
        grp_fu_280_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_284_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_284_p0 = tmp_10_i_reg_642.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_284_p0 = tmp_4_i_reg_617.read();
    } else {
        grp_fu_284_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_i_1_fu_364_p2() {
    i_1_fu_364_p2 = (!i_i1_reg_222.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i1_reg_222.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_i_fu_470_p2() {
    i_fu_470_p2 = (!i_i_reg_245.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i_reg_245.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_i_i_cast3_fu_370_p1() {
    i_i_cast3_fu_370_p1 = esl_zext<32,3>(i_i_reg_245.read());
}

void equalizer::thread_iir_coeff_array_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        iir_coeff_array_address0 = iir_coeff_array_addr_5_reg_550.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        iir_coeff_array_address0 = iir_coeff_array_addr_3_reg_540.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        iir_coeff_array_address0 = iir_coeff_array_addr_6_reg_588.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_coeff_array_address0 =  (sc_lv<5>) (tmp_3_cast_fu_404_p1.read());
    } else {
        iir_coeff_array_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void equalizer::thread_iir_coeff_array_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        iir_coeff_array_address1 = iir_coeff_array_addr_4_reg_545.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_coeff_array_address1 = iir_coeff_array_addr_2_reg_535.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_coeff_array_address1 =  (sc_lv<5>) (tmp_4_cast_fu_415_p1.read());
    } else {
        iir_coeff_array_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void equalizer::thread_iir_coeff_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_coeff_array_ce0 = ap_const_logic_1;
    } else {
        iir_coeff_array_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_coeff_array_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_coeff_array_ce1 = ap_const_logic_1;
    } else {
        iir_coeff_array_ce1 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_coeff_array_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        iir_coeff_array_we0 = ap_const_logic_1;
    } else {
        iir_coeff_array_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_address0 = iir_x_0_addr_reg_568.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_x_0_address0 =  (sc_lv<3>) (i_i_cast3_fu_370_p1.read());
    } else {
        iir_x_0_address0 =  (sc_lv<3>) ("XXX");
    }
}

void equalizer::thread_iir_x_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        iir_x_0_ce0 = ap_const_logic_1;
    } else {
        iir_x_0_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_we0 = ap_const_logic_1;
    } else {
        iir_x_0_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        iir_x_1_ce0 = ap_const_logic_1;
    } else {
        iir_x_1_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        iir_x_1_we0 = ap_const_logic_1;
    } else {
        iir_x_1_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_y_1_ce0 = ap_const_logic_1;
    } else {
        iir_y_1_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state54.read())) {
        iir_y_1_we0 = ap_const_logic_1;
    } else {
        iir_y_1_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_y_2_ce0 = ap_const_logic_1;
    } else {
        iir_y_2_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        iir_y_2_we0 = ap_const_logic_1;
    } else {
        iir_y_2_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_j_fu_497_p2() {
    j_fu_497_p2 = (!j_i_reg_256.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_i_reg_256.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_j_i_cast1_cast_fu_476_p1() {
    j_i_cast1_cast_fu_476_p1 = esl_zext<6,3>(j_i_reg_256.read());
}

void equalizer::thread_p_shl1_cast_fu_394_p1() {
    p_shl1_cast_fu_394_p1 = esl_zext<6,4>(tmp_2_fu_386_p3.read());
}

void equalizer::thread_p_shl3_cast_fu_348_p1() {
    p_shl3_cast_fu_348_p1 = esl_zext<6,4>(tmp_s_fu_340_p3.read());
}

void equalizer::thread_tmp_10_fu_352_p2() {
    tmp_10_fu_352_p2 = (!tmp_9_fu_332_p3.read().is_01() || !p_shl3_cast_fu_348_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_9_fu_332_p3.read()) - sc_biguint<6>(p_shl3_cast_fu_348_p1.read()));
}

void equalizer::thread_tmp_11_fu_480_p2() {
    tmp_11_fu_480_p2 = (!tmp_10_reg_512.read().is_01() || !j_i_cast1_cast_fu_476_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_10_reg_512.read()) + sc_biguint<6>(j_i_cast1_cast_fu_476_p1.read()));
}

void equalizer::thread_tmp_12_cast_fu_485_p1() {
    tmp_12_cast_fu_485_p1 = esl_sext<32,6>(tmp_11_fu_480_p2.read());
}

void equalizer::thread_tmp_1_fu_326_p2() {
    tmp_1_fu_326_p2 = (!mode.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(mode.read() == ap_const_lv32_1);
}

void equalizer::thread_tmp_2_fu_386_p3() {
    tmp_2_fu_386_p3 = esl_concat<3,1>(i_i_reg_245.read(), ap_const_lv1_0);
}

void equalizer::thread_tmp_3_cast_fu_404_p1() {
    tmp_3_cast_fu_404_p1 = esl_sext<32,6>(tmp_3_fu_398_p2.read());
}

void equalizer::thread_tmp_3_fu_398_p2() {
    tmp_3_fu_398_p2 = (!tmp_fu_378_p3.read().is_01() || !p_shl1_cast_fu_394_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_fu_378_p3.read()) - sc_biguint<6>(p_shl1_cast_fu_394_p1.read()));
}

void equalizer::thread_tmp_4_cast_fu_415_p1() {
    tmp_4_cast_fu_415_p1 = esl_zext<32,6>(tmp_4_fu_409_p2.read());
}

void equalizer::thread_tmp_4_fu_409_p2() {
    tmp_4_fu_409_p2 = (tmp_3_fu_398_p2.read() | ap_const_lv6_1);
}

void equalizer::thread_tmp_5_cast_fu_426_p1() {
    tmp_5_cast_fu_426_p1 = esl_sext<32,6>(tmp_5_fu_420_p2.read());
}

void equalizer::thread_tmp_5_fu_420_p2() {
    tmp_5_fu_420_p2 = (!tmp_3_fu_398_p2.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_398_p2.read()) + sc_biguint<6>(ap_const_lv6_2));
}

void equalizer::thread_tmp_6_cast_fu_437_p1() {
    tmp_6_cast_fu_437_p1 = esl_sext<32,6>(tmp_6_fu_431_p2.read());
}

void equalizer::thread_tmp_6_fu_431_p2() {
    tmp_6_fu_431_p2 = (!tmp_3_fu_398_p2.read().is_01() || !ap_const_lv6_3.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_398_p2.read()) + sc_biguint<6>(ap_const_lv6_3));
}

void equalizer::thread_tmp_7_cast_fu_448_p1() {
    tmp_7_cast_fu_448_p1 = esl_sext<32,6>(tmp_7_fu_442_p2.read());
}

void equalizer::thread_tmp_7_fu_442_p2() {
    tmp_7_fu_442_p2 = (!tmp_3_fu_398_p2.read().is_01() || !ap_const_lv6_4.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_398_p2.read()) + sc_biguint<6>(ap_const_lv6_4));
}

void equalizer::thread_tmp_8_cast_fu_459_p1() {
    tmp_8_cast_fu_459_p1 = esl_sext<32,6>(tmp_8_fu_453_p2.read());
}

void equalizer::thread_tmp_8_fu_453_p2() {
    tmp_8_fu_453_p2 = (!tmp_3_fu_398_p2.read().is_01() || !ap_const_lv6_5.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_398_p2.read()) + sc_biguint<6>(ap_const_lv6_5));
}

void equalizer::thread_tmp_9_fu_332_p3() {
    tmp_9_fu_332_p3 = esl_concat<3,3>(i_i1_reg_222.read(), ap_const_lv3_0);
}

void equalizer::thread_tmp_fu_378_p3() {
    tmp_fu_378_p3 = esl_concat<3,3>(i_i_reg_245.read(), ap_const_lv3_0);
}

void equalizer::thread_tmp_s_fu_340_p3() {
    tmp_s_fu_340_p3 = esl_concat<3,1>(i_i1_reg_222.read(), ap_const_lv1_0);
}

void equalizer::thread_y_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_464_p2.read()))) {
        y_ap_vld = ap_const_logic_1;
    } else {
        y_ap_vld = ap_const_logic_0;
    }
}

void equalizer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && ((esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_464_p2.read())) || 
  (esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_358_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_508.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_464_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i2_fu_491_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state46;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state48;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_fsm_state49;
            break;
        case 281474976710656 : 
            ap_NS_fsm = ap_ST_fsm_state50;
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_fsm_state51;
            break;
        case 1125899906842624 : 
            ap_NS_fsm = ap_ST_fsm_state52;
            break;
        case 2251799813685248 : 
            ap_NS_fsm = ap_ST_fsm_state53;
            break;
        case 4503599627370496 : 
            ap_NS_fsm = ap_ST_fsm_state54;
            break;
        case 9007199254740992 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<54>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void equalizer::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_AWVALID\" :  \"" << s_axi_eq_io_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_eq_io_AWREADY\" :  \"" << s_axi_eq_io_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_AWADDR\" :  \"" << s_axi_eq_io_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WVALID\" :  \"" << s_axi_eq_io_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_WREADY\" :  \"" << s_axi_eq_io_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WDATA\" :  \"" << s_axi_eq_io_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WSTRB\" :  \"" << s_axi_eq_io_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_ARVALID\" :  \"" << s_axi_eq_io_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_ARREADY\" :  \"" << s_axi_eq_io_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_ARADDR\" :  \"" << s_axi_eq_io_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RVALID\" :  \"" << s_axi_eq_io_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_RREADY\" :  \"" << s_axi_eq_io_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RDATA\" :  \"" << s_axi_eq_io_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RRESP\" :  \"" << s_axi_eq_io_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_BVALID\" :  \"" << s_axi_eq_io_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_BREADY\" :  \"" << s_axi_eq_io_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_BRESP\" :  \"" << s_axi_eq_io_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

