// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "equalizer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic equalizer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic equalizer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<38> equalizer::ap_ST_fsm_state1 = "1";
const sc_lv<38> equalizer::ap_ST_fsm_state2 = "10";
const sc_lv<38> equalizer::ap_ST_fsm_state3 = "100";
const sc_lv<38> equalizer::ap_ST_fsm_state4 = "1000";
const sc_lv<38> equalizer::ap_ST_fsm_state5 = "10000";
const sc_lv<38> equalizer::ap_ST_fsm_state6 = "100000";
const sc_lv<38> equalizer::ap_ST_fsm_state7 = "1000000";
const sc_lv<38> equalizer::ap_ST_fsm_state8 = "10000000";
const sc_lv<38> equalizer::ap_ST_fsm_state9 = "100000000";
const sc_lv<38> equalizer::ap_ST_fsm_state10 = "1000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state11 = "10000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state12 = "100000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<38> equalizer::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<32> equalizer::ap_const_lv32_0 = "00000000000000000000000000000000";
const int equalizer::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> equalizer::ap_const_lv32_4 = "100";
const sc_lv<32> equalizer::ap_const_lv32_12 = "10010";
const sc_lv<32> equalizer::ap_const_lv32_13 = "10011";
const sc_lv<32> equalizer::ap_const_lv32_8 = "1000";
const sc_lv<32> equalizer::ap_const_lv32_16 = "10110";
const sc_lv<32> equalizer::ap_const_lv32_9 = "1001";
const sc_lv<32> equalizer::ap_const_lv32_17 = "10111";
const sc_lv<32> equalizer::ap_const_lv32_F = "1111";
const sc_lv<32> equalizer::ap_const_lv32_1D = "11101";
const sc_lv<32> equalizer::ap_const_lv32_24 = "100100";
const sc_lv<32> equalizer::ap_const_lv32_1 = "1";
const sc_lv<1> equalizer::ap_const_lv1_0 = "0";
const sc_lv<1> equalizer::ap_const_lv1_1 = "1";
const sc_lv<32> equalizer::ap_const_lv32_2 = "10";
const sc_lv<32> equalizer::ap_const_lv32_5 = "101";
const sc_lv<3> equalizer::ap_const_lv3_0 = "000";
const sc_lv<32> equalizer::ap_const_lv32_25 = "100101";
const sc_lv<32> equalizer::ap_const_lv32_3 = "11";
const sc_lv<32> equalizer::ap_const_lv32_11 = "10001";
const sc_lv<32> equalizer::ap_const_lv32_10 = "10000";
const sc_lv<32> equalizer::ap_const_lv32_1E = "11110";
const sc_lv<32> equalizer::ap_const_lv32_6 = "110";
const sc_lv<32> equalizer::ap_const_lv32_14 = "10100";
const sc_lv<3> equalizer::ap_const_lv3_5 = "101";
const sc_lv<3> equalizer::ap_const_lv3_1 = "1";
const sc_lv<6> equalizer::ap_const_lv6_1 = "1";
const sc_lv<6> equalizer::ap_const_lv6_2 = "10";
const sc_lv<6> equalizer::ap_const_lv6_4 = "100";
const sc_lv<6> equalizer::ap_const_lv6_5 = "101";
const sc_lv<3> equalizer::ap_const_lv3_6 = "110";
const sc_lv<2> equalizer::ap_const_lv2_0 = "00";
const sc_lv<2> equalizer::ap_const_lv2_1 = "1";
const bool equalizer::ap_const_boolean_1 = true;

equalizer::equalizer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    iir_coeff_array_U = new equalizer_iir_coebkb("iir_coeff_array_U");
    iir_coeff_array_U->clk(ap_clk);
    iir_coeff_array_U->reset(ap_rst_n_inv);
    iir_coeff_array_U->address0(iir_coeff_array_address0);
    iir_coeff_array_U->ce0(iir_coeff_array_ce0);
    iir_coeff_array_U->we0(iir_coeff_array_we0);
    iir_coeff_array_U->d0(coeffs_q0);
    iir_coeff_array_U->q0(iir_coeff_array_q0);
    iir_coeff_array_U->address1(iir_coeff_array_address1);
    iir_coeff_array_U->ce1(iir_coeff_array_ce1);
    iir_coeff_array_U->q1(iir_coeff_array_q1);
    iir_x_1_U = new equalizer_iir_x_1("iir_x_1_U");
    iir_x_1_U->clk(ap_clk);
    iir_x_1_U->reset(ap_rst_n_inv);
    iir_x_1_U->address0(iir_x_1_addr_reg_520);
    iir_x_1_U->ce0(iir_x_1_ce0);
    iir_x_1_U->we0(iir_x_1_we0);
    iir_x_1_U->d0(iir_x_0_load_reg_558);
    iir_x_1_U->q0(iir_x_1_q0);
    iir_x_0_U = new equalizer_iir_x_1("iir_x_0_U");
    iir_x_0_U->clk(ap_clk);
    iir_x_0_U->reset(ap_rst_n_inv);
    iir_x_0_U->address0(iir_x_0_address0);
    iir_x_0_U->ce0(iir_x_0_ce0);
    iir_x_0_U->we0(iir_x_0_we0);
    iir_x_0_U->d0(temp_i_reg_223);
    iir_x_0_U->q0(iir_x_0_q0);
    iir_y_1_U = new equalizer_iir_x_1("iir_y_1_U");
    iir_y_1_U->clk(ap_clk);
    iir_y_1_U->reset(ap_rst_n_inv);
    iir_y_1_U->address0(iir_y_1_addr_reg_530);
    iir_y_1_U->ce0(iir_y_1_ce0);
    iir_y_1_U->we0(iir_y_1_we0);
    iir_y_1_U->d0(reg_292);
    iir_y_1_U->q0(iir_y_1_q0);
    iir_y_2_U = new equalizer_iir_x_1("iir_y_2_U");
    iir_y_2_U->clk(ap_clk);
    iir_y_2_U->reset(ap_rst_n_inv);
    iir_y_2_U->address0(iir_y_2_addr_reg_535);
    iir_y_2_U->ce0(iir_y_2_ce0);
    iir_y_2_U->we0(iir_y_2_we0);
    iir_y_2_U->d0(iir_y_1_load_reg_579);
    iir_y_2_U->q0(iir_y_2_q0);
    equalizer_eq_io_s_axi_U = new equalizer_eq_io_s_axi<C_S_AXI_EQ_IO_ADDR_WIDTH,C_S_AXI_EQ_IO_DATA_WIDTH>("equalizer_eq_io_s_axi_U");
    equalizer_eq_io_s_axi_U->AWVALID(s_axi_eq_io_AWVALID);
    equalizer_eq_io_s_axi_U->AWREADY(s_axi_eq_io_AWREADY);
    equalizer_eq_io_s_axi_U->AWADDR(s_axi_eq_io_AWADDR);
    equalizer_eq_io_s_axi_U->WVALID(s_axi_eq_io_WVALID);
    equalizer_eq_io_s_axi_U->WREADY(s_axi_eq_io_WREADY);
    equalizer_eq_io_s_axi_U->WDATA(s_axi_eq_io_WDATA);
    equalizer_eq_io_s_axi_U->WSTRB(s_axi_eq_io_WSTRB);
    equalizer_eq_io_s_axi_U->ARVALID(s_axi_eq_io_ARVALID);
    equalizer_eq_io_s_axi_U->ARREADY(s_axi_eq_io_ARREADY);
    equalizer_eq_io_s_axi_U->ARADDR(s_axi_eq_io_ARADDR);
    equalizer_eq_io_s_axi_U->RVALID(s_axi_eq_io_RVALID);
    equalizer_eq_io_s_axi_U->RREADY(s_axi_eq_io_RREADY);
    equalizer_eq_io_s_axi_U->RDATA(s_axi_eq_io_RDATA);
    equalizer_eq_io_s_axi_U->RRESP(s_axi_eq_io_RRESP);
    equalizer_eq_io_s_axi_U->BVALID(s_axi_eq_io_BVALID);
    equalizer_eq_io_s_axi_U->BREADY(s_axi_eq_io_BREADY);
    equalizer_eq_io_s_axi_U->BRESP(s_axi_eq_io_BRESP);
    equalizer_eq_io_s_axi_U->ACLK(ap_clk);
    equalizer_eq_io_s_axi_U->ARESET(ap_rst_n_inv);
    equalizer_eq_io_s_axi_U->ACLK_EN(ap_var_for_const0);
    equalizer_eq_io_s_axi_U->ap_start(ap_start);
    equalizer_eq_io_s_axi_U->interrupt(interrupt);
    equalizer_eq_io_s_axi_U->ap_ready(ap_ready);
    equalizer_eq_io_s_axi_U->ap_done(ap_done);
    equalizer_eq_io_s_axi_U->ap_idle(ap_idle);
    equalizer_eq_io_s_axi_U->y(temp_i_reg_223);
    equalizer_eq_io_s_axi_U->y_ap_vld(y_ap_vld);
    equalizer_eq_io_s_axi_U->x(x);
    equalizer_eq_io_s_axi_U->mode(mode);
    equalizer_eq_io_s_axi_U->coeffs_address0(coeffs_address0);
    equalizer_eq_io_s_axi_U->coeffs_ce0(coeffs_ce0);
    equalizer_eq_io_s_axi_U->coeffs_q0(coeffs_q0);
    equalizer_faddfsucud_U0 = new equalizer_faddfsucud<1,7,32,32,32>("equalizer_faddfsucud_U0");
    equalizer_faddfsucud_U0->clk(ap_clk);
    equalizer_faddfsucud_U0->reset(ap_rst_n_inv);
    equalizer_faddfsucud_U0->din0(grp_fu_257_p0);
    equalizer_faddfsucud_U0->din1(grp_fu_257_p1);
    equalizer_faddfsucud_U0->opcode(grp_fu_257_opcode);
    equalizer_faddfsucud_U0->ce(ap_var_for_const0);
    equalizer_faddfsucud_U0->dout(grp_fu_257_p2);
    equalizer_fmul_32dEe_U1 = new equalizer_fmul_32dEe<1,4,32,32,32>("equalizer_fmul_32dEe_U1");
    equalizer_fmul_32dEe_U1->clk(ap_clk);
    equalizer_fmul_32dEe_U1->reset(ap_rst_n_inv);
    equalizer_fmul_32dEe_U1->din0(grp_fu_261_p0);
    equalizer_fmul_32dEe_U1->din1(grp_fu_261_p1);
    equalizer_fmul_32dEe_U1->ce(ap_var_for_const0);
    equalizer_fmul_32dEe_U1->dout(grp_fu_261_p2);
    equalizer_fmul_32dEe_U2 = new equalizer_fmul_32dEe<1,4,32,32,32>("equalizer_fmul_32dEe_U2");
    equalizer_fmul_32dEe_U2->clk(ap_clk);
    equalizer_fmul_32dEe_U2->reset(ap_rst_n_inv);
    equalizer_fmul_32dEe_U2->din0(reg_275);
    equalizer_fmul_32dEe_U2->din1(iir_x_0_load_reg_558);
    equalizer_fmul_32dEe_U2->ce(ap_var_for_const0);
    equalizer_fmul_32dEe_U2->dout(grp_fu_266_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_426_p2 );
    sensitive << ( exitcond1_i_fu_331_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_426_p2 );
    sensitive << ( exitcond1_i_fu_331_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_coeffs_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_11_cast_fu_447_p1 );

    SC_METHOD(thread_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_exitcond1_i_fu_331_p2);
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i1_reg_212 );

    SC_METHOD(thread_exitcond_i2_fu_453_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_i_reg_246 );

    SC_METHOD(thread_exitcond_i_fu_426_p2);
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i_reg_235 );

    SC_METHOD(thread_grp_fu_257_opcode);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_grp_fu_257_p0);
    sensitive << ( reg_281 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( reg_292 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_grp_fu_257_p1);
    sensitive << ( reg_281 );
    sensitive << ( reg_287 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_3_i_reg_574 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_grp_fu_261_p0);
    sensitive << ( reg_270 );
    sensitive << ( reg_275 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( b2_reg_564 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_grp_fu_261_p1);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( iir_x_1_load_reg_569 );
    sensitive << ( iir_y_1_load_reg_579 );
    sensitive << ( iir_y_2_load_reg_585 );
    sensitive << ( temp_i_reg_223 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_i_1_fu_337_p2);
    sensitive << ( i_i1_reg_212 );

    SC_METHOD(thread_i_fu_432_p2);
    sensitive << ( i_i_reg_235 );

    SC_METHOD(thread_i_i_cast3_fu_343_p1);
    sensitive << ( i_i_reg_235 );

    SC_METHOD(thread_iir_coeff_array_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_coeff_array_addr_3_reg_502 );
    sensitive << ( iir_coeff_array_addr_5_reg_545 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_3_cast_fu_377_p1 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_coeff_array_addr_2_reg_497 );
    sensitive << ( iir_coeff_array_addr_4_reg_507 );
    sensitive << ( tmp_4_cast_fu_388_p1 );

    SC_METHOD(thread_iir_coeff_array_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_coeff_array_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_iir_coeff_array_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_iir_x_0_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iir_x_0_addr_reg_525 );
    sensitive << ( i_i_cast3_fu_343_p1 );

    SC_METHOD(thread_iir_x_0_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_iir_x_0_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_iir_x_1_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_iir_x_1_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_iir_y_1_ce0);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_iir_y_1_we0);
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_iir_y_2_ce0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_iir_y_2_we0);
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_j_fu_459_p2);
    sensitive << ( j_i_reg_246 );

    SC_METHOD(thread_j_i_cast1_cast_fu_438_p1);
    sensitive << ( j_i_reg_246 );

    SC_METHOD(thread_p_shl1_cast_fu_367_p1);
    sensitive << ( tmp_2_fu_359_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_321_p1);
    sensitive << ( tmp_9_fu_313_p3 );

    SC_METHOD(thread_tmp_10_fu_442_p2);
    sensitive << ( tmp_s_reg_474 );
    sensitive << ( j_i_cast1_cast_fu_438_p1 );

    SC_METHOD(thread_tmp_11_cast_fu_447_p1);
    sensitive << ( tmp_10_fu_442_p2 );

    SC_METHOD(thread_tmp_1_fu_299_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );

    SC_METHOD(thread_tmp_2_fu_359_p3);
    sensitive << ( i_i_reg_235 );

    SC_METHOD(thread_tmp_3_cast_fu_377_p1);
    sensitive << ( tmp_3_fu_371_p2 );

    SC_METHOD(thread_tmp_3_fu_371_p2);
    sensitive << ( tmp_fu_351_p3 );
    sensitive << ( p_shl1_cast_fu_367_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_388_p1);
    sensitive << ( tmp_4_fu_382_p2 );

    SC_METHOD(thread_tmp_4_fu_382_p2);
    sensitive << ( tmp_3_fu_371_p2 );

    SC_METHOD(thread_tmp_5_cast_fu_399_p1);
    sensitive << ( tmp_5_fu_393_p2 );

    SC_METHOD(thread_tmp_5_fu_393_p2);
    sensitive << ( tmp_3_fu_371_p2 );

    SC_METHOD(thread_tmp_6_cast_fu_410_p1);
    sensitive << ( tmp_6_fu_404_p2 );

    SC_METHOD(thread_tmp_6_fu_404_p2);
    sensitive << ( tmp_3_fu_371_p2 );

    SC_METHOD(thread_tmp_7_cast_fu_421_p1);
    sensitive << ( tmp_7_fu_415_p2 );

    SC_METHOD(thread_tmp_7_fu_415_p2);
    sensitive << ( tmp_3_fu_371_p2 );

    SC_METHOD(thread_tmp_8_fu_305_p3);
    sensitive << ( i_i1_reg_212 );

    SC_METHOD(thread_tmp_9_fu_313_p3);
    sensitive << ( i_i1_reg_212 );

    SC_METHOD(thread_tmp_fu_351_p3);
    sensitive << ( i_i_reg_235 );

    SC_METHOD(thread_tmp_s_fu_325_p2);
    sensitive << ( tmp_8_fu_305_p3 );
    sensitive << ( p_shl3_cast_fu_321_p1 );

    SC_METHOD(thread_y_ap_vld);
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_426_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_reg_470 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_426_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i2_fu_453_p2 );
    sensitive << ( exitcond1_i_fu_331_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "equalizer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_eq_io_AWVALID, "(port)s_axi_eq_io_AWVALID");
    sc_trace(mVcdFile, s_axi_eq_io_AWREADY, "(port)s_axi_eq_io_AWREADY");
    sc_trace(mVcdFile, s_axi_eq_io_AWADDR, "(port)s_axi_eq_io_AWADDR");
    sc_trace(mVcdFile, s_axi_eq_io_WVALID, "(port)s_axi_eq_io_WVALID");
    sc_trace(mVcdFile, s_axi_eq_io_WREADY, "(port)s_axi_eq_io_WREADY");
    sc_trace(mVcdFile, s_axi_eq_io_WDATA, "(port)s_axi_eq_io_WDATA");
    sc_trace(mVcdFile, s_axi_eq_io_WSTRB, "(port)s_axi_eq_io_WSTRB");
    sc_trace(mVcdFile, s_axi_eq_io_ARVALID, "(port)s_axi_eq_io_ARVALID");
    sc_trace(mVcdFile, s_axi_eq_io_ARREADY, "(port)s_axi_eq_io_ARREADY");
    sc_trace(mVcdFile, s_axi_eq_io_ARADDR, "(port)s_axi_eq_io_ARADDR");
    sc_trace(mVcdFile, s_axi_eq_io_RVALID, "(port)s_axi_eq_io_RVALID");
    sc_trace(mVcdFile, s_axi_eq_io_RREADY, "(port)s_axi_eq_io_RREADY");
    sc_trace(mVcdFile, s_axi_eq_io_RDATA, "(port)s_axi_eq_io_RDATA");
    sc_trace(mVcdFile, s_axi_eq_io_RRESP, "(port)s_axi_eq_io_RRESP");
    sc_trace(mVcdFile, s_axi_eq_io_BVALID, "(port)s_axi_eq_io_BVALID");
    sc_trace(mVcdFile, s_axi_eq_io_BREADY, "(port)s_axi_eq_io_BREADY");
    sc_trace(mVcdFile, s_axi_eq_io_BRESP, "(port)s_axi_eq_io_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, y_ap_vld, "y_ap_vld");
    sc_trace(mVcdFile, x, "x");
    sc_trace(mVcdFile, mode, "mode");
    sc_trace(mVcdFile, coeffs_address0, "coeffs_address0");
    sc_trace(mVcdFile, coeffs_ce0, "coeffs_ce0");
    sc_trace(mVcdFile, coeffs_q0, "coeffs_q0");
    sc_trace(mVcdFile, iir_coeff_array_address0, "iir_coeff_array_address0");
    sc_trace(mVcdFile, iir_coeff_array_ce0, "iir_coeff_array_ce0");
    sc_trace(mVcdFile, iir_coeff_array_we0, "iir_coeff_array_we0");
    sc_trace(mVcdFile, iir_coeff_array_q0, "iir_coeff_array_q0");
    sc_trace(mVcdFile, iir_coeff_array_address1, "iir_coeff_array_address1");
    sc_trace(mVcdFile, iir_coeff_array_ce1, "iir_coeff_array_ce1");
    sc_trace(mVcdFile, iir_coeff_array_q1, "iir_coeff_array_q1");
    sc_trace(mVcdFile, iir_x_1_ce0, "iir_x_1_ce0");
    sc_trace(mVcdFile, iir_x_1_we0, "iir_x_1_we0");
    sc_trace(mVcdFile, iir_x_1_q0, "iir_x_1_q0");
    sc_trace(mVcdFile, iir_x_0_address0, "iir_x_0_address0");
    sc_trace(mVcdFile, iir_x_0_ce0, "iir_x_0_ce0");
    sc_trace(mVcdFile, iir_x_0_we0, "iir_x_0_we0");
    sc_trace(mVcdFile, iir_x_0_q0, "iir_x_0_q0");
    sc_trace(mVcdFile, iir_y_1_ce0, "iir_y_1_ce0");
    sc_trace(mVcdFile, iir_y_1_we0, "iir_y_1_we0");
    sc_trace(mVcdFile, iir_y_1_q0, "iir_y_1_q0");
    sc_trace(mVcdFile, iir_y_2_ce0, "iir_y_2_ce0");
    sc_trace(mVcdFile, iir_y_2_we0, "iir_y_2_we0");
    sc_trace(mVcdFile, iir_y_2_q0, "iir_y_2_q0");
    sc_trace(mVcdFile, reg_270, "reg_270");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, reg_275, "reg_275");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, grp_fu_261_p2, "grp_fu_261_p2");
    sc_trace(mVcdFile, reg_281, "reg_281");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, reg_287, "reg_287");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, reg_292, "reg_292");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, tmp_1_fu_299_p2, "tmp_1_fu_299_p2");
    sc_trace(mVcdFile, tmp_1_reg_470, "tmp_1_reg_470");
    sc_trace(mVcdFile, tmp_s_fu_325_p2, "tmp_s_fu_325_p2");
    sc_trace(mVcdFile, tmp_s_reg_474, "tmp_s_reg_474");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_337_p2, "i_1_fu_337_p2");
    sc_trace(mVcdFile, i_1_reg_482, "i_1_reg_482");
    sc_trace(mVcdFile, iir_coeff_array_addr_2_reg_497, "iir_coeff_array_addr_2_reg_497");
    sc_trace(mVcdFile, iir_coeff_array_addr_3_reg_502, "iir_coeff_array_addr_3_reg_502");
    sc_trace(mVcdFile, iir_coeff_array_addr_4_reg_507, "iir_coeff_array_addr_4_reg_507");
    sc_trace(mVcdFile, i_fu_432_p2, "i_fu_432_p2");
    sc_trace(mVcdFile, i_reg_515, "i_reg_515");
    sc_trace(mVcdFile, iir_x_1_addr_reg_520, "iir_x_1_addr_reg_520");
    sc_trace(mVcdFile, exitcond_i_fu_426_p2, "exitcond_i_fu_426_p2");
    sc_trace(mVcdFile, iir_x_0_addr_reg_525, "iir_x_0_addr_reg_525");
    sc_trace(mVcdFile, iir_y_1_addr_reg_530, "iir_y_1_addr_reg_530");
    sc_trace(mVcdFile, iir_y_2_addr_reg_535, "iir_y_2_addr_reg_535");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, iir_coeff_array_addr_5_reg_545, "iir_coeff_array_addr_5_reg_545");
    sc_trace(mVcdFile, j_fu_459_p2, "j_fu_459_p2");
    sc_trace(mVcdFile, j_reg_553, "j_reg_553");
    sc_trace(mVcdFile, iir_x_0_load_reg_558, "iir_x_0_load_reg_558");
    sc_trace(mVcdFile, b2_reg_564, "b2_reg_564");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, iir_x_1_load_reg_569, "iir_x_1_load_reg_569");
    sc_trace(mVcdFile, grp_fu_266_p2, "grp_fu_266_p2");
    sc_trace(mVcdFile, tmp_3_i_reg_574, "tmp_3_i_reg_574");
    sc_trace(mVcdFile, iir_y_1_load_reg_579, "iir_y_1_load_reg_579");
    sc_trace(mVcdFile, iir_y_2_load_reg_585, "iir_y_2_load_reg_585");
    sc_trace(mVcdFile, i_i1_reg_212, "i_i1_reg_212");
    sc_trace(mVcdFile, exitcond_i2_fu_453_p2, "exitcond_i2_fu_453_p2");
    sc_trace(mVcdFile, temp_i_reg_223, "temp_i_reg_223");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, i_i_reg_235, "i_i_reg_235");
    sc_trace(mVcdFile, j_i_reg_246, "j_i_reg_246");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond1_i_fu_331_p2, "exitcond1_i_fu_331_p2");
    sc_trace(mVcdFile, tmp_3_cast_fu_377_p1, "tmp_3_cast_fu_377_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_388_p1, "tmp_4_cast_fu_388_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_399_p1, "tmp_5_cast_fu_399_p1");
    sc_trace(mVcdFile, tmp_6_cast_fu_410_p1, "tmp_6_cast_fu_410_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_421_p1, "tmp_7_cast_fu_421_p1");
    sc_trace(mVcdFile, i_i_cast3_fu_343_p1, "i_i_cast3_fu_343_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_447_p1, "tmp_11_cast_fu_447_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_257_p0, "grp_fu_257_p0");
    sc_trace(mVcdFile, grp_fu_257_p1, "grp_fu_257_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, grp_fu_261_p0, "grp_fu_261_p0");
    sc_trace(mVcdFile, grp_fu_261_p1, "grp_fu_261_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_9_fu_313_p3, "tmp_9_fu_313_p3");
    sc_trace(mVcdFile, tmp_8_fu_305_p3, "tmp_8_fu_305_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_321_p1, "p_shl3_cast_fu_321_p1");
    sc_trace(mVcdFile, tmp_2_fu_359_p3, "tmp_2_fu_359_p3");
    sc_trace(mVcdFile, tmp_fu_351_p3, "tmp_fu_351_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_367_p1, "p_shl1_cast_fu_367_p1");
    sc_trace(mVcdFile, tmp_3_fu_371_p2, "tmp_3_fu_371_p2");
    sc_trace(mVcdFile, tmp_4_fu_382_p2, "tmp_4_fu_382_p2");
    sc_trace(mVcdFile, tmp_5_fu_393_p2, "tmp_5_fu_393_p2");
    sc_trace(mVcdFile, tmp_6_fu_404_p2, "tmp_6_fu_404_p2");
    sc_trace(mVcdFile, tmp_7_fu_415_p2, "tmp_7_fu_415_p2");
    sc_trace(mVcdFile, j_i_cast1_cast_fu_438_p1, "j_i_cast1_cast_fu_438_p1");
    sc_trace(mVcdFile, tmp_10_fu_442_p2, "tmp_10_fu_442_p2");
    sc_trace(mVcdFile, grp_fu_257_opcode, "grp_fu_257_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("equalizer.hdltvin.dat");
    mHdltvoutHandle.open("equalizer.hdltvout.dat");
}

equalizer::~equalizer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete iir_coeff_array_U;
    delete iir_x_1_U;
    delete iir_x_0_U;
    delete iir_y_1_U;
    delete iir_y_2_U;
    delete equalizer_eq_io_s_axi_U;
    delete equalizer_faddfsucud_U0;
    delete equalizer_fmul_32dEe_U1;
    delete equalizer_fmul_32dEe_U2;
}

void equalizer::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void equalizer::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_299_p2.read(), ap_const_lv1_0))) {
        i_i1_reg_212 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i2_fu_453_p2.read()))) {
        i_i1_reg_212 = i_1_reg_482.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_299_p2.read(), ap_const_lv1_1))) {
        i_i_reg_235 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        i_i_reg_235 = i_reg_515.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_331_p2.read()))) {
        j_i_reg_246 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_i_reg_246 = j_reg_553.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_299_p2.read(), ap_const_lv1_1))) {
        temp_i_reg_223 = x.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        temp_i_reg_223 = reg_292.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        b2_reg_564 = iir_coeff_array_q1.read();
        iir_x_1_load_reg_569 = iir_x_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_0))) {
        i_1_reg_482 = i_1_fu_337_p2.read();
        tmp_s_reg_474 = tmp_s_fu_325_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1))) {
        i_reg_515 = i_fu_432_p2.read();
        iir_coeff_array_addr_2_reg_497 =  (sc_lv<5>) (tmp_5_cast_fu_399_p1.read());
        iir_coeff_array_addr_3_reg_502 =  (sc_lv<5>) (tmp_6_cast_fu_410_p1.read());
        iir_coeff_array_addr_4_reg_507 =  (sc_lv<5>) (tmp_7_cast_fu_421_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        iir_coeff_array_addr_5_reg_545 =  (sc_lv<5>) (tmp_11_cast_fu_447_p1.read());
        j_reg_553 = j_fu_459_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_426_p2.read()))) {
        iir_x_0_addr_reg_525 =  (sc_lv<3>) (i_i_cast3_fu_343_p1.read());
        iir_x_1_addr_reg_520 =  (sc_lv<3>) (i_i_cast3_fu_343_p1.read());
        iir_y_1_addr_reg_530 =  (sc_lv<3>) (i_i_cast3_fu_343_p1.read());
        iir_y_2_addr_reg_535 =  (sc_lv<3>) (i_i_cast3_fu_343_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_load_reg_558 = iir_x_0_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        iir_y_1_load_reg_579 = iir_y_1_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        iir_y_2_load_reg_585 = iir_y_2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        reg_270 = iir_coeff_array_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        reg_275 = iir_coeff_array_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        reg_281 = grp_fu_261_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        reg_287 = grp_fu_261_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read()))) {
        reg_292 = grp_fu_257_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_1_reg_470 = tmp_1_fu_299_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_3_i_reg_574 = grp_fu_266_p2.read();
    }
}

void equalizer::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void equalizer::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void equalizer::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void equalizer::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void equalizer::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void equalizer::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void equalizer::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void equalizer::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void equalizer::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void equalizer::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void equalizer::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void equalizer::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void equalizer::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void equalizer::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void equalizer::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void equalizer::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void equalizer::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void equalizer::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void equalizer::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void equalizer::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void equalizer::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void equalizer::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         ((esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_426_p2.read())) || 
          (esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_331_p2.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void equalizer::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void equalizer::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         ((esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_426_p2.read())) || 
          (esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_0) && 
           esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_331_p2.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void equalizer::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void equalizer::thread_coeffs_address0() {
    coeffs_address0 =  (sc_lv<5>) (tmp_11_cast_fu_447_p1.read());
}

void equalizer::thread_coeffs_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        coeffs_ce0 = ap_const_logic_1;
    } else {
        coeffs_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_exitcond1_i_fu_331_p2() {
    exitcond1_i_fu_331_p2 = (!i_i1_reg_212.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_212.read() == ap_const_lv3_5);
}

void equalizer::thread_exitcond_i2_fu_453_p2() {
    exitcond_i2_fu_453_p2 = (!j_i_reg_246.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_246.read() == ap_const_lv3_6);
}

void equalizer::thread_exitcond_i_fu_426_p2() {
    exitcond_i_fu_426_p2 = (!i_i_reg_235.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_235.read() == ap_const_lv3_5);
}

void equalizer::thread_grp_fu_257_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        grp_fu_257_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        grp_fu_257_opcode = ap_const_lv2_0;
    } else {
        grp_fu_257_opcode = "XX";
    }
}

void equalizer::thread_grp_fu_257_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        grp_fu_257_p0 = reg_292.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_257_p0 = reg_281.read();
    } else {
        grp_fu_257_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_257_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_257_p1 = reg_281.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        grp_fu_257_p1 = reg_287.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_257_p1 = tmp_3_i_reg_574.read();
    } else {
        grp_fu_257_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_261_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_261_p0 = reg_275.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_261_p0 = b2_reg_564.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        grp_fu_261_p0 = reg_270.read();
    } else {
        grp_fu_261_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_grp_fu_261_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_261_p1 = iir_y_2_load_reg_585.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_261_p1 = iir_y_1_load_reg_579.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_261_p1 = iir_x_1_load_reg_569.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_261_p1 = temp_i_reg_223.read();
    } else {
        grp_fu_261_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void equalizer::thread_i_1_fu_337_p2() {
    i_1_fu_337_p2 = (!i_i1_reg_212.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i1_reg_212.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_i_fu_432_p2() {
    i_fu_432_p2 = (!i_i_reg_235.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_i_reg_235.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_i_i_cast3_fu_343_p1() {
    i_i_cast3_fu_343_p1 = esl_zext<32,3>(i_i_reg_235.read());
}

void equalizer::thread_iir_coeff_array_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        iir_coeff_array_address0 = iir_coeff_array_addr_3_reg_502.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        iir_coeff_array_address0 = iir_coeff_array_addr_5_reg_545.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_coeff_array_address0 =  (sc_lv<5>) (tmp_3_cast_fu_377_p1.read());
    } else {
        iir_coeff_array_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void equalizer::thread_iir_coeff_array_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        iir_coeff_array_address1 = iir_coeff_array_addr_4_reg_507.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_coeff_array_address1 = iir_coeff_array_addr_2_reg_497.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_coeff_array_address1 =  (sc_lv<5>) (tmp_4_cast_fu_388_p1.read());
    } else {
        iir_coeff_array_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void equalizer::thread_iir_coeff_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_coeff_array_ce0 = ap_const_logic_1;
    } else {
        iir_coeff_array_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_coeff_array_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        iir_coeff_array_ce1 = ap_const_logic_1;
    } else {
        iir_coeff_array_ce1 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_coeff_array_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        iir_coeff_array_we0 = ap_const_logic_1;
    } else {
        iir_coeff_array_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_address0 = iir_x_0_addr_reg_525.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        iir_x_0_address0 =  (sc_lv<3>) (i_i_cast3_fu_343_p1.read());
    } else {
        iir_x_0_address0 =  (sc_lv<3>) ("XXX");
    }
}

void equalizer::thread_iir_x_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        iir_x_0_ce0 = ap_const_logic_1;
    } else {
        iir_x_0_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iir_x_0_we0 = ap_const_logic_1;
    } else {
        iir_x_0_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        iir_x_1_ce0 = ap_const_logic_1;
    } else {
        iir_x_1_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_x_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        iir_x_1_we0 = ap_const_logic_1;
    } else {
        iir_x_1_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        iir_y_1_ce0 = ap_const_logic_1;
    } else {
        iir_y_1_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        iir_y_1_we0 = ap_const_logic_1;
    } else {
        iir_y_1_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        iir_y_2_ce0 = ap_const_logic_1;
    } else {
        iir_y_2_ce0 = ap_const_logic_0;
    }
}

void equalizer::thread_iir_y_2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        iir_y_2_we0 = ap_const_logic_1;
    } else {
        iir_y_2_we0 = ap_const_logic_0;
    }
}

void equalizer::thread_j_fu_459_p2() {
    j_fu_459_p2 = (!j_i_reg_246.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_i_reg_246.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void equalizer::thread_j_i_cast1_cast_fu_438_p1() {
    j_i_cast1_cast_fu_438_p1 = esl_zext<6,3>(j_i_reg_246.read());
}

void equalizer::thread_p_shl1_cast_fu_367_p1() {
    p_shl1_cast_fu_367_p1 = esl_zext<6,4>(tmp_2_fu_359_p3.read());
}

void equalizer::thread_p_shl3_cast_fu_321_p1() {
    p_shl3_cast_fu_321_p1 = esl_zext<6,4>(tmp_9_fu_313_p3.read());
}

void equalizer::thread_tmp_10_fu_442_p2() {
    tmp_10_fu_442_p2 = (!tmp_s_reg_474.read().is_01() || !j_i_cast1_cast_fu_438_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_s_reg_474.read()) + sc_biguint<6>(j_i_cast1_cast_fu_438_p1.read()));
}

void equalizer::thread_tmp_11_cast_fu_447_p1() {
    tmp_11_cast_fu_447_p1 = esl_sext<32,6>(tmp_10_fu_442_p2.read());
}

void equalizer::thread_tmp_1_fu_299_p2() {
    tmp_1_fu_299_p2 = (!mode.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(mode.read() == ap_const_lv32_1);
}

void equalizer::thread_tmp_2_fu_359_p3() {
    tmp_2_fu_359_p3 = esl_concat<3,1>(i_i_reg_235.read(), ap_const_lv1_0);
}

void equalizer::thread_tmp_3_cast_fu_377_p1() {
    tmp_3_cast_fu_377_p1 = esl_sext<32,6>(tmp_3_fu_371_p2.read());
}

void equalizer::thread_tmp_3_fu_371_p2() {
    tmp_3_fu_371_p2 = (!tmp_fu_351_p3.read().is_01() || !p_shl1_cast_fu_367_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_fu_351_p3.read()) - sc_biguint<6>(p_shl1_cast_fu_367_p1.read()));
}

void equalizer::thread_tmp_4_cast_fu_388_p1() {
    tmp_4_cast_fu_388_p1 = esl_zext<32,6>(tmp_4_fu_382_p2.read());
}

void equalizer::thread_tmp_4_fu_382_p2() {
    tmp_4_fu_382_p2 = (tmp_3_fu_371_p2.read() | ap_const_lv6_1);
}

void equalizer::thread_tmp_5_cast_fu_399_p1() {
    tmp_5_cast_fu_399_p1 = esl_sext<32,6>(tmp_5_fu_393_p2.read());
}

void equalizer::thread_tmp_5_fu_393_p2() {
    tmp_5_fu_393_p2 = (!tmp_3_fu_371_p2.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_371_p2.read()) + sc_biguint<6>(ap_const_lv6_2));
}

void equalizer::thread_tmp_6_cast_fu_410_p1() {
    tmp_6_cast_fu_410_p1 = esl_sext<32,6>(tmp_6_fu_404_p2.read());
}

void equalizer::thread_tmp_6_fu_404_p2() {
    tmp_6_fu_404_p2 = (!tmp_3_fu_371_p2.read().is_01() || !ap_const_lv6_4.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_371_p2.read()) + sc_biguint<6>(ap_const_lv6_4));
}

void equalizer::thread_tmp_7_cast_fu_421_p1() {
    tmp_7_cast_fu_421_p1 = esl_sext<32,6>(tmp_7_fu_415_p2.read());
}

void equalizer::thread_tmp_7_fu_415_p2() {
    tmp_7_fu_415_p2 = (!tmp_3_fu_371_p2.read().is_01() || !ap_const_lv6_5.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_fu_371_p2.read()) + sc_biguint<6>(ap_const_lv6_5));
}

void equalizer::thread_tmp_8_fu_305_p3() {
    tmp_8_fu_305_p3 = esl_concat<3,3>(i_i1_reg_212.read(), ap_const_lv3_0);
}

void equalizer::thread_tmp_9_fu_313_p3() {
    tmp_9_fu_313_p3 = esl_concat<3,1>(i_i1_reg_212.read(), ap_const_lv1_0);
}

void equalizer::thread_tmp_fu_351_p3() {
    tmp_fu_351_p3 = esl_concat<3,3>(i_i_reg_235.read(), ap_const_lv3_0);
}

void equalizer::thread_tmp_s_fu_325_p2() {
    tmp_s_fu_325_p2 = (!tmp_8_fu_305_p3.read().is_01() || !p_shl3_cast_fu_321_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_fu_305_p3.read()) - sc_biguint<6>(p_shl3_cast_fu_321_p1.read()));
}

void equalizer::thread_y_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_426_p2.read()))) {
        y_ap_vld = ap_const_logic_1;
    } else {
        y_ap_vld = ap_const_logic_0;
    }
}

void equalizer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && ((esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_426_p2.read())) || 
  (esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_i_fu_331_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_1_reg_470.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_426_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i2_fu_453_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<38>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void equalizer::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_AWVALID\" :  \"" << s_axi_eq_io_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_eq_io_AWREADY\" :  \"" << s_axi_eq_io_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_AWADDR\" :  \"" << s_axi_eq_io_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WVALID\" :  \"" << s_axi_eq_io_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_WREADY\" :  \"" << s_axi_eq_io_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WDATA\" :  \"" << s_axi_eq_io_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_WSTRB\" :  \"" << s_axi_eq_io_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_ARVALID\" :  \"" << s_axi_eq_io_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_ARREADY\" :  \"" << s_axi_eq_io_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_ARADDR\" :  \"" << s_axi_eq_io_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RVALID\" :  \"" << s_axi_eq_io_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_RREADY\" :  \"" << s_axi_eq_io_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RDATA\" :  \"" << s_axi_eq_io_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_RRESP\" :  \"" << s_axi_eq_io_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_BVALID\" :  \"" << s_axi_eq_io_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_eq_io_BREADY\" :  \"" << s_axi_eq_io_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_eq_io_BRESP\" :  \"" << s_axi_eq_io_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

