'@startuml
'https://plantuml.com/object-diagram
left to right direction
frame "ibd System Context" as SC {
    actor User as USC
    component "Audio Source" as ASSC {
        portout audioOut as AOSC
    }
    component Equalizer as EQSC {
        portin audioIn as AIEQSC
        portout audioOut as AOEQSC
        portin UI as IEQSC
    }
    component Speakers as SSC {
        portin audioIn as AISSC
    }

    USC --> IEQSC : Configures the Equalizer
    AOSC --> AIEQSC
    AOEQSC --> AISSC : Outputs sound with configuration
}

frame "ibd Equalizer" as EQ {
    portin audioIn as AIEQ
    portout audioOut as AOEQ
    portin UI as UIEQ
    '-lass
}


@enduml
