@startuml
'https://plantuml.com/class-diagram
left to right direction
interface AudioInterface
class AudioInput
class AudioOutput
class ADC
class DAC
AudioInterface <|-- AudioInput
AudioInterface <|-- AudioOutput

class Equalizer
class EqualizerState {
    isOn: bool
    coefficients: Matrix2D<float>
}
AudioInput --> ADC : outputs audio
ADC --> Equalizer : EQ reads a sample
Equalizer --> DAC : Applies filter coefficients to the sample, if on
DAC --> AudioOutput : Outputs sample
Equalizer --> EqualizerState
@enduml