@startuml
'https://plantuml.com/state-diagram
left to right direction
'scale 350 width
[*] --> SendAudioState

state SendAudioState {
}


state SetGainState {
}

SendAudioState -[#0000FF]-> SetGainState :<color #0000FF>Thread detected\n<color #0000FF>EQSettings changed
SetGainState --> SendAudioState : New gains \nwere sent and saved \nto the IP core
@enduml