@startuml
'https://plantuml.com/sequence-diagram
title Normal flow with no errors
autonumber
participant User as U
participant EmbeddedSystem as E
participant "RealTimeLoop (RTL)" as RTL

U -> E: Turns on system
activate E #FF6666
E -> E: Starts with \nPowerOnSelfTest \nstate.
E -> E: selfTestOk() called.\nInitialized state.
E -> E: initialized() called.\nOperational state.
E -> E: Initialized and set Ready state\nstart() called.
activate E #FFAAAA



@enduml