-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity equalizer is
generic (
    C_S_AXI_EQ_IO_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_EQ_IO_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_eq_io_AWVALID : IN STD_LOGIC;
    s_axi_eq_io_AWREADY : OUT STD_LOGIC;
    s_axi_eq_io_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_ADDR_WIDTH-1 downto 0);
    s_axi_eq_io_WVALID : IN STD_LOGIC;
    s_axi_eq_io_WREADY : OUT STD_LOGIC;
    s_axi_eq_io_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH-1 downto 0);
    s_axi_eq_io_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH/8-1 downto 0);
    s_axi_eq_io_ARVALID : IN STD_LOGIC;
    s_axi_eq_io_ARREADY : OUT STD_LOGIC;
    s_axi_eq_io_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_ADDR_WIDTH-1 downto 0);
    s_axi_eq_io_RVALID : OUT STD_LOGIC;
    s_axi_eq_io_RREADY : IN STD_LOGIC;
    s_axi_eq_io_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_EQ_IO_DATA_WIDTH-1 downto 0);
    s_axi_eq_io_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_eq_io_BVALID : OUT STD_LOGIC;
    s_axi_eq_io_BREADY : IN STD_LOGIC;
    s_axi_eq_io_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of equalizer is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "equalizer,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.442000,HLS_SYN_LAT=124,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=8,HLS_SYN_FF=1797,HLS_SYN_LUT=1872}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (37 downto 0) := "00000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (37 downto 0) := "00000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (37 downto 0) := "00000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (37 downto 0) := "00000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (37 downto 0) := "00000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (37 downto 0) := "00000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (37 downto 0) := "00001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (37 downto 0) := "00010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (37 downto 0) := "00100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (37 downto 0) := "01000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal y_ap_vld : STD_LOGIC;
    signal x : STD_LOGIC_VECTOR (31 downto 0);
    signal mode : STD_LOGIC_VECTOR (31 downto 0);
    signal coeffs_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal coeffs_ce0 : STD_LOGIC;
    signal coeffs_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_coeff_array_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal iir_coeff_array_ce0 : STD_LOGIC;
    signal iir_coeff_array_we0 : STD_LOGIC;
    signal iir_coeff_array_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_coeff_array_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal iir_coeff_array_ce1 : STD_LOGIC;
    signal iir_coeff_array_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_x_1_ce0 : STD_LOGIC;
    signal iir_x_1_we0 : STD_LOGIC;
    signal iir_x_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_x_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_x_0_ce0 : STD_LOGIC;
    signal iir_x_0_we0 : STD_LOGIC;
    signal iir_x_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_y_1_ce0 : STD_LOGIC;
    signal iir_y_1_we0 : STD_LOGIC;
    signal iir_y_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_y_2_ce0 : STD_LOGIC;
    signal iir_y_2_we0 : STD_LOGIC;
    signal iir_y_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_270 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal reg_275 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_fu_261_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_281 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal reg_287 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal grp_fu_257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_292 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal tmp_1_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_325_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_reg_474 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_1_fu_337_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_1_reg_482 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_coeff_array_addr_2_reg_497 : STD_LOGIC_VECTOR (4 downto 0);
    signal iir_coeff_array_addr_3_reg_502 : STD_LOGIC_VECTOR (4 downto 0);
    signal iir_coeff_array_addr_4_reg_507 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_432_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_reg_515 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_x_1_addr_reg_520 : STD_LOGIC_VECTOR (2 downto 0);
    signal exitcond_i_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal iir_x_0_addr_reg_525 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_y_1_addr_reg_530 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_y_2_addr_reg_535 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal iir_coeff_array_addr_5_reg_545 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_fu_459_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_reg_553 : STD_LOGIC_VECTOR (2 downto 0);
    signal iir_x_0_load_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal b2_reg_564 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal iir_x_1_load_reg_569 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_i_reg_574 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_y_1_load_reg_579 : STD_LOGIC_VECTOR (31 downto 0);
    signal iir_y_2_load_reg_585 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_i1_reg_212 : STD_LOGIC_VECTOR (2 downto 0);
    signal exitcond_i2_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_i_reg_223 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal i_i_reg_235 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_i_reg_246 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal exitcond1_i_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_cast_fu_377_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_cast_fu_388_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_cast_fu_399_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_cast_fu_410_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_cast_fu_421_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_i_cast3_fu_343_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_cast_fu_447_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_257_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_257_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal grp_fu_261_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_261_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal tmp_9_fu_313_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_305_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl3_cast_fu_321_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_359_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_351_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_cast_fu_367_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_3_fu_371_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_fu_382_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_393_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_404_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_fu_415_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_i_cast1_cast_fu_438_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_fu_442_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_257_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (37 downto 0);

    component equalizer_faddfsucud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component equalizer_fmul_32dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component equalizer_iir_coebkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component equalizer_iir_x_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component equalizer_eq_io_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        y : IN STD_LOGIC_VECTOR (31 downto 0);
        y_ap_vld : IN STD_LOGIC;
        x : OUT STD_LOGIC_VECTOR (31 downto 0);
        mode : OUT STD_LOGIC_VECTOR (31 downto 0);
        coeffs_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        coeffs_ce0 : IN STD_LOGIC;
        coeffs_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    iir_coeff_array_U : component equalizer_iir_coebkb
    generic map (
        DataWidth => 32,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => iir_coeff_array_address0,
        ce0 => iir_coeff_array_ce0,
        we0 => iir_coeff_array_we0,
        d0 => coeffs_q0,
        q0 => iir_coeff_array_q0,
        address1 => iir_coeff_array_address1,
        ce1 => iir_coeff_array_ce1,
        q1 => iir_coeff_array_q1);

    iir_x_1_U : component equalizer_iir_x_1
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => iir_x_1_addr_reg_520,
        ce0 => iir_x_1_ce0,
        we0 => iir_x_1_we0,
        d0 => iir_x_0_load_reg_558,
        q0 => iir_x_1_q0);

    iir_x_0_U : component equalizer_iir_x_1
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => iir_x_0_address0,
        ce0 => iir_x_0_ce0,
        we0 => iir_x_0_we0,
        d0 => temp_i_reg_223,
        q0 => iir_x_0_q0);

    iir_y_1_U : component equalizer_iir_x_1
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => iir_y_1_addr_reg_530,
        ce0 => iir_y_1_ce0,
        we0 => iir_y_1_we0,
        d0 => reg_292,
        q0 => iir_y_1_q0);

    iir_y_2_U : component equalizer_iir_x_1
    generic map (
        DataWidth => 32,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => iir_y_2_addr_reg_535,
        ce0 => iir_y_2_ce0,
        we0 => iir_y_2_we0,
        d0 => iir_y_1_load_reg_579,
        q0 => iir_y_2_q0);

    equalizer_eq_io_s_axi_U : component equalizer_eq_io_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_EQ_IO_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_EQ_IO_DATA_WIDTH)
    port map (
        AWVALID => s_axi_eq_io_AWVALID,
        AWREADY => s_axi_eq_io_AWREADY,
        AWADDR => s_axi_eq_io_AWADDR,
        WVALID => s_axi_eq_io_WVALID,
        WREADY => s_axi_eq_io_WREADY,
        WDATA => s_axi_eq_io_WDATA,
        WSTRB => s_axi_eq_io_WSTRB,
        ARVALID => s_axi_eq_io_ARVALID,
        ARREADY => s_axi_eq_io_ARREADY,
        ARADDR => s_axi_eq_io_ARADDR,
        RVALID => s_axi_eq_io_RVALID,
        RREADY => s_axi_eq_io_RREADY,
        RDATA => s_axi_eq_io_RDATA,
        RRESP => s_axi_eq_io_RRESP,
        BVALID => s_axi_eq_io_BVALID,
        BREADY => s_axi_eq_io_BREADY,
        BRESP => s_axi_eq_io_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        y => temp_i_reg_223,
        y_ap_vld => y_ap_vld,
        x => x,
        mode => mode,
        coeffs_address0 => coeffs_address0,
        coeffs_ce0 => coeffs_ce0,
        coeffs_q0 => coeffs_q0);

    equalizer_faddfsucud_U0 : component equalizer_faddfsucud
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_257_p0,
        din1 => grp_fu_257_p1,
        opcode => grp_fu_257_opcode,
        ce => ap_const_logic_1,
        dout => grp_fu_257_p2);

    equalizer_fmul_32dEe_U1 : component equalizer_fmul_32dEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_261_p0,
        din1 => grp_fu_261_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_261_p2);

    equalizer_fmul_32dEe_U2 : component equalizer_fmul_32dEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => reg_275,
        din1 => iir_x_0_load_reg_558,
        ce => ap_const_logic_1,
        dout => grp_fu_266_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_i1_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_1_fu_299_p2 = ap_const_lv1_0))) then 
                i_i1_reg_212 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = exitcond_i2_fu_453_p2))) then 
                i_i1_reg_212 <= i_1_reg_482;
            end if; 
        end if;
    end process;

    i_i_reg_235_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_1_fu_299_p2 = ap_const_lv1_1))) then 
                i_i_reg_235 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
                i_i_reg_235 <= i_reg_515;
            end if; 
        end if;
    end process;

    j_i_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_0) and (ap_const_lv1_0 = exitcond1_i_fu_331_p2))) then 
                j_i_reg_246 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_i_reg_246 <= j_reg_553;
            end if; 
        end if;
    end process;

    temp_i_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (tmp_1_fu_299_p2 = ap_const_lv1_1))) then 
                temp_i_reg_223 <= x;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
                temp_i_reg_223 <= reg_292;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                b2_reg_564 <= iir_coeff_array_q1;
                iir_x_1_load_reg_569 <= iir_x_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_0))) then
                i_1_reg_482 <= i_1_fu_337_p2;
                    tmp_s_reg_474(5 downto 1) <= tmp_s_fu_325_p2(5 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_1))) then
                i_reg_515 <= i_fu_432_p2;
                    iir_coeff_array_addr_2_reg_497(4 downto 1) <= tmp_5_cast_fu_399_p1(5 - 1 downto 0)(4 downto 1);
                    iir_coeff_array_addr_3_reg_502(4 downto 1) <= tmp_6_cast_fu_410_p1(5 - 1 downto 0)(4 downto 1);
                    iir_coeff_array_addr_4_reg_507(4 downto 1) <= tmp_7_cast_fu_421_p1(5 - 1 downto 0)(4 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                iir_coeff_array_addr_5_reg_545 <= tmp_11_cast_fu_447_p1(5 - 1 downto 0);
                j_reg_553 <= j_fu_459_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_0 = exitcond_i_fu_426_p2))) then
                iir_x_0_addr_reg_525 <= i_i_cast3_fu_343_p1(3 - 1 downto 0);
                iir_x_1_addr_reg_520 <= i_i_cast3_fu_343_p1(3 - 1 downto 0);
                iir_y_1_addr_reg_530 <= i_i_cast3_fu_343_p1(3 - 1 downto 0);
                iir_y_2_addr_reg_535 <= i_i_cast3_fu_343_p1(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                iir_x_0_load_reg_558 <= iir_x_0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                iir_y_1_load_reg_579 <= iir_y_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                iir_y_2_load_reg_585 <= iir_y_2_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state19))) then
                reg_270 <= iir_coeff_array_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state20))) then
                reg_275 <= iir_coeff_array_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state23))) then
                reg_281 <= grp_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state24))) then
                reg_287 <= grp_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state30) or (ap_const_logic_1 = ap_CS_fsm_state37))) then
                reg_292 <= grp_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                tmp_1_reg_470 <= tmp_1_fu_299_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                tmp_3_i_reg_574 <= grp_fu_266_p2;
            end if;
        end if;
    end process;
    tmp_s_reg_474(0) <= '0';
    iir_coeff_array_addr_2_reg_497(0) <= '0';
    iir_coeff_array_addr_3_reg_502(0) <= '0';
    iir_coeff_array_addr_4_reg_507(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_1_reg_470, ap_CS_fsm_state2, exitcond_i_fu_426_p2, ap_CS_fsm_state3, exitcond_i2_fu_453_p2, exitcond1_i_fu_331_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (((tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_1 = exitcond_i_fu_426_p2)) or ((tmp_1_reg_470 = ap_const_lv1_0) and (ap_const_lv1_1 = exitcond1_i_fu_331_p2))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_0 = exitcond_i_fu_426_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = exitcond_i2_fu_453_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(tmp_1_reg_470, ap_CS_fsm_state2, exitcond_i_fu_426_p2, exitcond1_i_fu_331_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (((tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_1 = exitcond_i_fu_426_p2)) or ((tmp_1_reg_470 = ap_const_lv1_0) and (ap_const_lv1_1 = exitcond1_i_fu_331_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(tmp_1_reg_470, ap_CS_fsm_state2, exitcond_i_fu_426_p2, exitcond1_i_fu_331_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (((tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_1 = exitcond_i_fu_426_p2)) or ((tmp_1_reg_470 = ap_const_lv1_0) and (ap_const_lv1_1 = exitcond1_i_fu_331_p2))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    coeffs_address0 <= tmp_11_cast_fu_447_p1(5 - 1 downto 0);

    coeffs_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            coeffs_ce0 <= ap_const_logic_1;
        else 
            coeffs_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_i_fu_331_p2 <= "1" when (i_i1_reg_212 = ap_const_lv3_5) else "0";
    exitcond_i2_fu_453_p2 <= "1" when (j_i_reg_246 = ap_const_lv3_6) else "0";
    exitcond_i_fu_426_p2 <= "1" when (i_i_reg_235 = ap_const_lv3_5) else "0";

    grp_fu_257_opcode_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state24, ap_CS_fsm_state17, ap_CS_fsm_state31)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            grp_fu_257_opcode <= ap_const_lv2_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_257_opcode <= ap_const_lv2_0;
        else 
            grp_fu_257_opcode <= "XX";
        end if; 
    end process;


    grp_fu_257_p0_assign_proc : process(reg_281, ap_CS_fsm_state10, ap_CS_fsm_state24, reg_292, ap_CS_fsm_state17, ap_CS_fsm_state31)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            grp_fu_257_p0 <= reg_292;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_257_p0 <= reg_281;
        else 
            grp_fu_257_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_257_p1_assign_proc : process(reg_281, reg_287, ap_CS_fsm_state10, ap_CS_fsm_state24, tmp_3_i_reg_574, ap_CS_fsm_state17, ap_CS_fsm_state31)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_257_p1 <= reg_281;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            grp_fu_257_p1 <= reg_287;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_257_p1 <= tmp_3_i_reg_574;
        else 
            grp_fu_257_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_261_p0_assign_proc : process(reg_270, reg_275, ap_CS_fsm_state20, b2_reg_564, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_261_p0 <= reg_275;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_261_p0 <= b2_reg_564;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_261_p0 <= reg_270;
        else 
            grp_fu_261_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_261_p1_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state6, iir_x_1_load_reg_569, iir_y_1_load_reg_579, iir_y_2_load_reg_585, temp_i_reg_223, ap_CS_fsm_state7, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_261_p1 <= iir_y_2_load_reg_585;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_261_p1 <= iir_y_1_load_reg_579;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_261_p1 <= iir_x_1_load_reg_569;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_261_p1 <= temp_i_reg_223;
        else 
            grp_fu_261_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    i_1_fu_337_p2 <= std_logic_vector(unsigned(i_i1_reg_212) + unsigned(ap_const_lv3_1));
    i_fu_432_p2 <= std_logic_vector(unsigned(i_i_reg_235) + unsigned(ap_const_lv3_1));
    i_i_cast3_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_reg_235),32));

    iir_coeff_array_address0_assign_proc : process(ap_CS_fsm_state2, iir_coeff_array_addr_3_reg_502, iir_coeff_array_addr_5_reg_545, ap_CS_fsm_state4, tmp_3_cast_fu_377_p1, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            iir_coeff_array_address0 <= iir_coeff_array_addr_3_reg_502;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            iir_coeff_array_address0 <= iir_coeff_array_addr_5_reg_545;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            iir_coeff_array_address0 <= tmp_3_cast_fu_377_p1(5 - 1 downto 0);
        else 
            iir_coeff_array_address0 <= "XXXXX";
        end if; 
    end process;


    iir_coeff_array_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state19, ap_CS_fsm_state2, iir_coeff_array_addr_2_reg_497, iir_coeff_array_addr_4_reg_507, tmp_4_cast_fu_388_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            iir_coeff_array_address1 <= iir_coeff_array_addr_4_reg_507;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            iir_coeff_array_address1 <= iir_coeff_array_addr_2_reg_497;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            iir_coeff_array_address1 <= tmp_4_cast_fu_388_p1(5 - 1 downto 0);
        else 
            iir_coeff_array_address1 <= "XXXXX";
        end if; 
    end process;


    iir_coeff_array_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            iir_coeff_array_ce0 <= ap_const_logic_1;
        else 
            iir_coeff_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_coeff_array_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state19, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            iir_coeff_array_ce1 <= ap_const_logic_1;
        else 
            iir_coeff_array_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    iir_coeff_array_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            iir_coeff_array_we0 <= ap_const_logic_1;
        else 
            iir_coeff_array_we0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_x_0_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, iir_x_0_addr_reg_525, i_i_cast3_fu_343_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            iir_x_0_address0 <= iir_x_0_addr_reg_525;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            iir_x_0_address0 <= i_i_cast3_fu_343_p1(3 - 1 downto 0);
        else 
            iir_x_0_address0 <= "XXX";
        end if; 
    end process;


    iir_x_0_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            iir_x_0_ce0 <= ap_const_logic_1;
        else 
            iir_x_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_x_0_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            iir_x_0_we0 <= ap_const_logic_1;
        else 
            iir_x_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_x_1_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            iir_x_1_ce0 <= ap_const_logic_1;
        else 
            iir_x_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_x_1_we0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            iir_x_1_we0 <= ap_const_logic_1;
        else 
            iir_x_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_y_1_ce0_assign_proc : process(ap_CS_fsm_state38, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            iir_y_1_ce0 <= ap_const_logic_1;
        else 
            iir_y_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_y_1_we0_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            iir_y_1_we0 <= ap_const_logic_1;
        else 
            iir_y_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_y_2_ce0_assign_proc : process(ap_CS_fsm_state19, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            iir_y_2_ce0 <= ap_const_logic_1;
        else 
            iir_y_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    iir_y_2_we0_assign_proc : process(ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            iir_y_2_we0 <= ap_const_logic_1;
        else 
            iir_y_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_459_p2 <= std_logic_vector(unsigned(j_i_reg_246) + unsigned(ap_const_lv3_1));
    j_i_cast1_cast_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_i_reg_246),6));
    p_shl1_cast_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_359_p3),6));
    p_shl3_cast_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_313_p3),6));
    tmp_10_fu_442_p2 <= std_logic_vector(unsigned(tmp_s_reg_474) + unsigned(j_i_cast1_cast_fu_438_p1));
        tmp_11_cast_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_442_p2),32));

    tmp_1_fu_299_p2 <= "1" when (mode = ap_const_lv32_1) else "0";
    tmp_2_fu_359_p3 <= (i_i_reg_235 & ap_const_lv1_0);
        tmp_3_cast_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_371_p2),32));

    tmp_3_fu_371_p2 <= std_logic_vector(unsigned(tmp_fu_351_p3) - unsigned(p_shl1_cast_fu_367_p1));
    tmp_4_cast_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_382_p2),32));
    tmp_4_fu_382_p2 <= (tmp_3_fu_371_p2 or ap_const_lv6_1);
        tmp_5_cast_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_393_p2),32));

    tmp_5_fu_393_p2 <= std_logic_vector(unsigned(tmp_3_fu_371_p2) + unsigned(ap_const_lv6_2));
        tmp_6_cast_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_404_p2),32));

    tmp_6_fu_404_p2 <= std_logic_vector(unsigned(tmp_3_fu_371_p2) + unsigned(ap_const_lv6_4));
        tmp_7_cast_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_415_p2),32));

    tmp_7_fu_415_p2 <= std_logic_vector(unsigned(tmp_3_fu_371_p2) + unsigned(ap_const_lv6_5));
    tmp_8_fu_305_p3 <= (i_i1_reg_212 & ap_const_lv3_0);
    tmp_9_fu_313_p3 <= (i_i1_reg_212 & ap_const_lv1_0);
    tmp_fu_351_p3 <= (i_i_reg_235 & ap_const_lv3_0);
    tmp_s_fu_325_p2 <= std_logic_vector(unsigned(tmp_8_fu_305_p3) - unsigned(p_shl3_cast_fu_321_p1));

    y_ap_vld_assign_proc : process(tmp_1_reg_470, ap_CS_fsm_state2, exitcond_i_fu_426_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_1_reg_470 = ap_const_lv1_1) and (ap_const_lv1_1 = exitcond_i_fu_426_p2))) then 
            y_ap_vld <= ap_const_logic_1;
        else 
            y_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
