// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="equalizer,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.442000,HLS_SYN_LAT=124,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=8,HLS_SYN_FF=1797,HLS_SYN_LUT=1872}" *)

module equalizer (
        ap_clk,
        ap_rst_n,
        s_axi_eq_io_AWVALID,
        s_axi_eq_io_AWREADY,
        s_axi_eq_io_AWADDR,
        s_axi_eq_io_WVALID,
        s_axi_eq_io_WREADY,
        s_axi_eq_io_WDATA,
        s_axi_eq_io_WSTRB,
        s_axi_eq_io_ARVALID,
        s_axi_eq_io_ARREADY,
        s_axi_eq_io_ARADDR,
        s_axi_eq_io_RVALID,
        s_axi_eq_io_RREADY,
        s_axi_eq_io_RDATA,
        s_axi_eq_io_RRESP,
        s_axi_eq_io_BVALID,
        s_axi_eq_io_BREADY,
        s_axi_eq_io_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;
parameter    C_S_AXI_EQ_IO_DATA_WIDTH = 32;
parameter    C_S_AXI_EQ_IO_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_EQ_IO_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_eq_io_AWVALID;
output   s_axi_eq_io_AWREADY;
input  [C_S_AXI_EQ_IO_ADDR_WIDTH - 1:0] s_axi_eq_io_AWADDR;
input   s_axi_eq_io_WVALID;
output   s_axi_eq_io_WREADY;
input  [C_S_AXI_EQ_IO_DATA_WIDTH - 1:0] s_axi_eq_io_WDATA;
input  [C_S_AXI_EQ_IO_WSTRB_WIDTH - 1:0] s_axi_eq_io_WSTRB;
input   s_axi_eq_io_ARVALID;
output   s_axi_eq_io_ARREADY;
input  [C_S_AXI_EQ_IO_ADDR_WIDTH - 1:0] s_axi_eq_io_ARADDR;
output   s_axi_eq_io_RVALID;
input   s_axi_eq_io_RREADY;
output  [C_S_AXI_EQ_IO_DATA_WIDTH - 1:0] s_axi_eq_io_RDATA;
output  [1:0] s_axi_eq_io_RRESP;
output   s_axi_eq_io_BVALID;
input   s_axi_eq_io_BREADY;
output  [1:0] s_axi_eq_io_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    y_ap_vld;
wire   [31:0] x;
wire   [31:0] mode;
wire   [4:0] coeffs_address0;
reg    coeffs_ce0;
wire   [31:0] coeffs_q0;
reg   [4:0] iir_coeff_array_address0;
reg    iir_coeff_array_ce0;
reg    iir_coeff_array_we0;
wire   [31:0] iir_coeff_array_q0;
reg   [4:0] iir_coeff_array_address1;
reg    iir_coeff_array_ce1;
wire   [31:0] iir_coeff_array_q1;
reg    iir_x_1_ce0;
reg    iir_x_1_we0;
wire   [31:0] iir_x_1_q0;
reg   [2:0] iir_x_0_address0;
reg    iir_x_0_ce0;
reg    iir_x_0_we0;
wire   [31:0] iir_x_0_q0;
reg    iir_y_1_ce0;
reg    iir_y_1_we0;
wire   [31:0] iir_y_1_q0;
reg    iir_y_2_ce0;
reg    iir_y_2_we0;
wire   [31:0] iir_y_2_q0;
reg   [31:0] reg_270;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state19;
reg   [31:0] reg_275;
wire    ap_CS_fsm_state20;
wire   [31:0] grp_fu_261_p2;
reg   [31:0] reg_281;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state23;
reg   [31:0] reg_287;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state24;
wire   [31:0] grp_fu_257_p2;
reg   [31:0] reg_292;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state37;
wire   [0:0] tmp_1_fu_299_p2;
reg   [0:0] tmp_1_reg_470;
wire   [5:0] tmp_s_fu_325_p2;
reg   [5:0] tmp_s_reg_474;
wire    ap_CS_fsm_state2;
wire   [2:0] i_1_fu_337_p2;
reg   [2:0] i_1_reg_482;
reg   [4:0] iir_coeff_array_addr_2_reg_497;
reg   [4:0] iir_coeff_array_addr_3_reg_502;
reg   [4:0] iir_coeff_array_addr_4_reg_507;
wire   [2:0] i_fu_432_p2;
reg   [2:0] i_reg_515;
reg   [2:0] iir_x_1_addr_reg_520;
wire   [0:0] exitcond_i_fu_426_p2;
reg   [2:0] iir_x_0_addr_reg_525;
reg   [2:0] iir_y_1_addr_reg_530;
reg   [2:0] iir_y_2_addr_reg_535;
wire    ap_CS_fsm_state3;
reg   [4:0] iir_coeff_array_addr_5_reg_545;
wire   [2:0] j_fu_459_p2;
reg   [2:0] j_reg_553;
reg   [31:0] iir_x_0_load_reg_558;
reg   [31:0] b2_reg_564;
wire    ap_CS_fsm_state6;
reg   [31:0] iir_x_1_load_reg_569;
wire   [31:0] grp_fu_266_p2;
reg   [31:0] tmp_3_i_reg_574;
reg   [31:0] iir_y_1_load_reg_579;
reg   [31:0] iir_y_2_load_reg_585;
reg   [2:0] i_i1_reg_212;
wire   [0:0] exitcond_i2_fu_453_p2;
reg   [31:0] temp_i_reg_223;
wire    ap_CS_fsm_state38;
reg   [2:0] i_i_reg_235;
reg   [2:0] j_i_reg_246;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond1_i_fu_331_p2;
wire  signed [31:0] tmp_3_cast_fu_377_p1;
wire   [31:0] tmp_4_cast_fu_388_p1;
wire  signed [31:0] tmp_5_cast_fu_399_p1;
wire  signed [31:0] tmp_6_cast_fu_410_p1;
wire  signed [31:0] tmp_7_cast_fu_421_p1;
wire   [31:0] i_i_cast3_fu_343_p1;
wire  signed [31:0] tmp_11_cast_fu_447_p1;
wire    ap_CS_fsm_state18;
reg   [31:0] grp_fu_257_p0;
reg   [31:0] grp_fu_257_p1;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state31;
reg   [31:0] grp_fu_261_p0;
reg   [31:0] grp_fu_261_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state21;
wire   [3:0] tmp_9_fu_313_p3;
wire   [5:0] tmp_8_fu_305_p3;
wire   [5:0] p_shl3_cast_fu_321_p1;
wire   [3:0] tmp_2_fu_359_p3;
wire   [5:0] tmp_fu_351_p3;
wire   [5:0] p_shl1_cast_fu_367_p1;
wire   [5:0] tmp_3_fu_371_p2;
wire   [5:0] tmp_4_fu_382_p2;
wire   [5:0] tmp_5_fu_393_p2;
wire   [5:0] tmp_6_fu_404_p2;
wire   [5:0] tmp_7_fu_415_p2;
wire   [5:0] j_i_cast1_cast_fu_438_p1;
wire   [5:0] tmp_10_fu_442_p2;
reg   [1:0] grp_fu_257_opcode;
reg   [37:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 38'd1;
end

equalizer_iir_coebkb #(
    .DataWidth( 32 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
iir_coeff_array_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(iir_coeff_array_address0),
    .ce0(iir_coeff_array_ce0),
    .we0(iir_coeff_array_we0),
    .d0(coeffs_q0),
    .q0(iir_coeff_array_q0),
    .address1(iir_coeff_array_address1),
    .ce1(iir_coeff_array_ce1),
    .q1(iir_coeff_array_q1)
);

equalizer_iir_x_1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
iir_x_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(iir_x_1_addr_reg_520),
    .ce0(iir_x_1_ce0),
    .we0(iir_x_1_we0),
    .d0(iir_x_0_load_reg_558),
    .q0(iir_x_1_q0)
);

equalizer_iir_x_1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
iir_x_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(iir_x_0_address0),
    .ce0(iir_x_0_ce0),
    .we0(iir_x_0_we0),
    .d0(temp_i_reg_223),
    .q0(iir_x_0_q0)
);

equalizer_iir_x_1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
iir_y_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(iir_y_1_addr_reg_530),
    .ce0(iir_y_1_ce0),
    .we0(iir_y_1_we0),
    .d0(reg_292),
    .q0(iir_y_1_q0)
);

equalizer_iir_x_1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
iir_y_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(iir_y_2_addr_reg_535),
    .ce0(iir_y_2_ce0),
    .we0(iir_y_2_we0),
    .d0(iir_y_1_load_reg_579),
    .q0(iir_y_2_q0)
);

equalizer_eq_io_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_EQ_IO_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_EQ_IO_DATA_WIDTH ))
equalizer_eq_io_s_axi_U(
    .AWVALID(s_axi_eq_io_AWVALID),
    .AWREADY(s_axi_eq_io_AWREADY),
    .AWADDR(s_axi_eq_io_AWADDR),
    .WVALID(s_axi_eq_io_WVALID),
    .WREADY(s_axi_eq_io_WREADY),
    .WDATA(s_axi_eq_io_WDATA),
    .WSTRB(s_axi_eq_io_WSTRB),
    .ARVALID(s_axi_eq_io_ARVALID),
    .ARREADY(s_axi_eq_io_ARREADY),
    .ARADDR(s_axi_eq_io_ARADDR),
    .RVALID(s_axi_eq_io_RVALID),
    .RREADY(s_axi_eq_io_RREADY),
    .RDATA(s_axi_eq_io_RDATA),
    .RRESP(s_axi_eq_io_RRESP),
    .BVALID(s_axi_eq_io_BVALID),
    .BREADY(s_axi_eq_io_BREADY),
    .BRESP(s_axi_eq_io_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .y(temp_i_reg_223),
    .y_ap_vld(y_ap_vld),
    .x(x),
    .mode(mode),
    .coeffs_address0(coeffs_address0),
    .coeffs_ce0(coeffs_ce0),
    .coeffs_q0(coeffs_q0)
);

equalizer_faddfsucud #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalizer_faddfsucud_U0(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .opcode(grp_fu_257_opcode),
    .ce(1'b1),
    .dout(grp_fu_257_p2)
);

equalizer_fmul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalizer_fmul_32dEe_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_261_p0),
    .din1(grp_fu_261_p1),
    .ce(1'b1),
    .dout(grp_fu_261_p2)
);

equalizer_fmul_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
equalizer_fmul_32dEe_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(reg_275),
    .din1(iir_x_0_load_reg_558),
    .ce(1'b1),
    .dout(grp_fu_266_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_1_fu_299_p2 == 1'd0))) begin
        i_i1_reg_212 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == exitcond_i2_fu_453_p2))) begin
        i_i1_reg_212 <= i_1_reg_482;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_1_fu_299_p2 == 1'd1))) begin
        i_i_reg_235 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        i_i_reg_235 <= i_reg_515;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd0) & (1'd0 == exitcond1_i_fu_331_p2))) begin
        j_i_reg_246 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        j_i_reg_246 <= j_reg_553;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (tmp_1_fu_299_p2 == 1'd1))) begin
        temp_i_reg_223 <= x;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        temp_i_reg_223 <= reg_292;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b2_reg_564 <= iir_coeff_array_q1;
        iir_x_1_load_reg_569 <= iir_x_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd0))) begin
        i_1_reg_482 <= i_1_fu_337_p2;
        tmp_s_reg_474[5 : 1] <= tmp_s_fu_325_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd1))) begin
        i_reg_515 <= i_fu_432_p2;
        iir_coeff_array_addr_2_reg_497[4 : 1] <= tmp_5_cast_fu_399_p1[4 : 1];
        iir_coeff_array_addr_3_reg_502[4 : 1] <= tmp_6_cast_fu_410_p1[4 : 1];
        iir_coeff_array_addr_4_reg_507[4 : 1] <= tmp_7_cast_fu_421_p1[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        iir_coeff_array_addr_5_reg_545 <= tmp_11_cast_fu_447_p1;
        j_reg_553 <= j_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd1) & (1'd0 == exitcond_i_fu_426_p2))) begin
        iir_x_0_addr_reg_525 <= i_i_cast3_fu_343_p1;
        iir_x_1_addr_reg_520 <= i_i_cast3_fu_343_p1;
        iir_y_1_addr_reg_530 <= i_i_cast3_fu_343_p1;
        iir_y_2_addr_reg_535 <= i_i_cast3_fu_343_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        iir_x_0_load_reg_558 <= iir_x_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        iir_y_1_load_reg_579 <= iir_y_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        iir_y_2_load_reg_585 <= iir_y_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_270 <= iir_coeff_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state20))) begin
        reg_275 <= iir_coeff_array_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state23))) begin
        reg_281 <= grp_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state24))) begin
        reg_287 <= grp_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state37))) begin
        reg_292 <= grp_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_1_reg_470 <= tmp_1_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_3_i_reg_574 <= grp_fu_266_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((tmp_1_reg_470 == 1'd1) & (1'd1 == exitcond_i_fu_426_p2)) | ((tmp_1_reg_470 == 1'd0) & (1'd1 == exitcond1_i_fu_331_p2))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((tmp_1_reg_470 == 1'd1) & (1'd1 == exitcond_i_fu_426_p2)) | ((tmp_1_reg_470 == 1'd0) & (1'd1 == exitcond1_i_fu_331_p2))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        coeffs_ce0 = 1'b1;
    end else begin
        coeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state31))) begin
        grp_fu_257_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_257_opcode = 2'd0;
    end else begin
        grp_fu_257_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state31))) begin
        grp_fu_257_p0 = reg_292;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_257_p0 = reg_281;
    end else begin
        grp_fu_257_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_257_p1 = reg_281;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state31))) begin
        grp_fu_257_p1 = reg_287;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_257_p1 = tmp_3_i_reg_574;
    end else begin
        grp_fu_257_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_261_p0 = reg_275;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_261_p0 = b2_reg_564;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_261_p0 = reg_270;
    end else begin
        grp_fu_261_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_261_p1 = iir_y_2_load_reg_585;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_261_p1 = iir_y_1_load_reg_579;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_261_p1 = iir_x_1_load_reg_569;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_261_p1 = temp_i_reg_223;
    end else begin
        grp_fu_261_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        iir_coeff_array_address0 = iir_coeff_array_addr_3_reg_502;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        iir_coeff_array_address0 = iir_coeff_array_addr_5_reg_545;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        iir_coeff_array_address0 = tmp_3_cast_fu_377_p1;
    end else begin
        iir_coeff_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        iir_coeff_array_address1 = iir_coeff_array_addr_4_reg_507;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        iir_coeff_array_address1 = iir_coeff_array_addr_2_reg_497;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        iir_coeff_array_address1 = tmp_4_cast_fu_388_p1;
    end else begin
        iir_coeff_array_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state18))) begin
        iir_coeff_array_ce0 = 1'b1;
    end else begin
        iir_coeff_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state2))) begin
        iir_coeff_array_ce1 = 1'b1;
    end else begin
        iir_coeff_array_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        iir_coeff_array_we0 = 1'b1;
    end else begin
        iir_coeff_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        iir_x_0_address0 = iir_x_0_addr_reg_525;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        iir_x_0_address0 = i_i_cast3_fu_343_p1;
    end else begin
        iir_x_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        iir_x_0_ce0 = 1'b1;
    end else begin
        iir_x_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        iir_x_0_we0 = 1'b1;
    end else begin
        iir_x_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        iir_x_1_ce0 = 1'b1;
    end else begin
        iir_x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        iir_x_1_we0 = 1'b1;
    end else begin
        iir_x_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state18))) begin
        iir_y_1_ce0 = 1'b1;
    end else begin
        iir_y_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        iir_y_1_we0 = 1'b1;
    end else begin
        iir_y_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state20))) begin
        iir_y_2_ce0 = 1'b1;
    end else begin
        iir_y_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        iir_y_2_we0 = 1'b1;
    end else begin
        iir_y_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd1) & (1'd1 == exitcond_i_fu_426_p2))) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (((tmp_1_reg_470 == 1'd1) & (1'd1 == exitcond_i_fu_426_p2)) | ((tmp_1_reg_470 == 1'd0) & (1'd1 == exitcond1_i_fu_331_p2))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_reg_470 == 1'd1) & (1'd0 == exitcond_i_fu_426_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == exitcond_i2_fu_453_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign coeffs_address0 = tmp_11_cast_fu_447_p1;

assign exitcond1_i_fu_331_p2 = ((i_i1_reg_212 == 3'd5) ? 1'b1 : 1'b0);

assign exitcond_i2_fu_453_p2 = ((j_i_reg_246 == 3'd6) ? 1'b1 : 1'b0);

assign exitcond_i_fu_426_p2 = ((i_i_reg_235 == 3'd5) ? 1'b1 : 1'b0);

assign i_1_fu_337_p2 = (i_i1_reg_212 + 3'd1);

assign i_fu_432_p2 = (i_i_reg_235 + 3'd1);

assign i_i_cast3_fu_343_p1 = i_i_reg_235;

assign j_fu_459_p2 = (j_i_reg_246 + 3'd1);

assign j_i_cast1_cast_fu_438_p1 = j_i_reg_246;

assign p_shl1_cast_fu_367_p1 = tmp_2_fu_359_p3;

assign p_shl3_cast_fu_321_p1 = tmp_9_fu_313_p3;

assign tmp_10_fu_442_p2 = (tmp_s_reg_474 + j_i_cast1_cast_fu_438_p1);

assign tmp_11_cast_fu_447_p1 = $signed(tmp_10_fu_442_p2);

assign tmp_1_fu_299_p2 = ((mode == 32'd1) ? 1'b1 : 1'b0);

assign tmp_2_fu_359_p3 = {{i_i_reg_235}, {1'd0}};

assign tmp_3_cast_fu_377_p1 = $signed(tmp_3_fu_371_p2);

assign tmp_3_fu_371_p2 = (tmp_fu_351_p3 - p_shl1_cast_fu_367_p1);

assign tmp_4_cast_fu_388_p1 = tmp_4_fu_382_p2;

assign tmp_4_fu_382_p2 = (tmp_3_fu_371_p2 | 6'd1);

assign tmp_5_cast_fu_399_p1 = $signed(tmp_5_fu_393_p2);

assign tmp_5_fu_393_p2 = (tmp_3_fu_371_p2 + 6'd2);

assign tmp_6_cast_fu_410_p1 = $signed(tmp_6_fu_404_p2);

assign tmp_6_fu_404_p2 = (tmp_3_fu_371_p2 + 6'd4);

assign tmp_7_cast_fu_421_p1 = $signed(tmp_7_fu_415_p2);

assign tmp_7_fu_415_p2 = (tmp_3_fu_371_p2 + 6'd5);

assign tmp_8_fu_305_p3 = {{i_i1_reg_212}, {3'd0}};

assign tmp_9_fu_313_p3 = {{i_i1_reg_212}, {1'd0}};

assign tmp_fu_351_p3 = {{i_i_reg_235}, {3'd0}};

assign tmp_s_fu_325_p2 = (tmp_8_fu_305_p3 - p_shl3_cast_fu_321_p1);

always @ (posedge ap_clk) begin
    tmp_s_reg_474[0] <= 1'b0;
    iir_coeff_array_addr_2_reg_497[0] <= 1'b0;
    iir_coeff_array_addr_3_reg_502[0] <= 1'b0;
    iir_coeff_array_addr_4_reg_507[0] <= 1'b1;
end

endmodule //equalizer
